"""created equipment and floc table

Revision ID: 866d8f8c15c1
Revises: 034358a696db
Create Date: 2023-03-07 07:27:13.212888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866d8f8c15c1'
down_revision = '034358a696db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_floc_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['parent_id'], ['floc.id'], name=op.f('fk_floc_parent_id_floc')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floc'))
    )
    op.create_index(op.f('ix_floc_id'), 'floc', ['id'], unique=False)
    op.add_column('equipment', sa.Column('description', sa.String(), nullable=False))
    op.drop_constraint('uq_equip_location_description', 'equipment', type_='unique')
    op.create_unique_constraint(None, 'equipment', ['description'])
    op.drop_column('equipment', 'equipment_description')
    op.drop_column('equipment', 'functional_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('functional_location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('equipment_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'equipment', type_='unique')
    op.create_unique_constraint('uq_equip_location_description', 'equipment', ['functional_location', 'equipment_description'])
    op.drop_column('equipment', 'description')
    op.drop_index(op.f('ix_floc_id'), table_name='floc')
    op.drop_table('floc')
    # ### end Alembic commands ###
