"""remove old initiative table; add many-to-one triggers for initiative

Revision ID: 343eaef7bf73
Revises: be40b83036c4
Create Date: 2023-03-21 14:12:34.000554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '343eaef7bf73'
down_revision = 'be40b83036c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_improvement_initiative_triggers_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('initiative_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['general_improvement_initiative.id'], name=op.f('fk_general_improvement_initiative_triggers_association_initiative_id_general_improvement_initiative'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], name=op.f('fk_general_improvement_initiative_triggers_association_trigger_id_trigger'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_improvement_initiative_triggers_association'))
    )
    op.create_index(op.f('ix_general_improvement_initiative_triggers_association_id'), 'general_improvement_initiative_triggers_association', ['id'], unique=False)
    op.drop_index('ix_initiative_id', table_name='initiative')
    op.drop_table('initiative')
    op.drop_constraint('fk_general_improvement_initiative_trigger_id_trigger', 'general_improvement_initiative', type_='foreignkey')
    op.drop_column('general_improvement_initiative', 'trigger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_improvement_initiative', sa.Column('trigger_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_general_improvement_initiative_trigger_id_trigger', 'general_improvement_initiative', 'trigger', ['trigger_id'], ['id'])
    op.create_table('initiative',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_opened', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('target_completion_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tonnes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('safety', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('events', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimate_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], name='fk_initiative_priority_id_priority'),
    sa.ForeignKeyConstraint(['project_owner_id'], ['user.id'], name='fk_initiative_project_owner_id_user'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='fk_initiative_status_id_status'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], name='fk_initiative_supervisor_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_initiative')
    )
    op.create_index('ix_initiative_id', 'initiative', ['id'], unique=False)
    op.drop_index(op.f('ix_general_improvement_initiative_triggers_association_id'), table_name='general_improvement_initiative_triggers_association')
    op.drop_table('general_improvement_initiative_triggers_association')
    # ### end Alembic commands ###
