"""Add user fields to initiative schema; add sap_number to user schema

Revision ID: a5b3bc1d6eda
Revises: 221f003085b6
Create Date: 2023-02-23 07:26:51.962684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5b3bc1d6eda"
down_revision = "221f003085b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiative", sa.Column("project_owner_id", sa.Integer(), nullable=True))
    op.add_column("initiative", sa.Column("supervisor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_initiative_project_owner_id_user"),
        "initiative",
        "user",
        ["project_owner_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_initiative_supervisor_id_user"), "initiative", "user", ["supervisor_id"], ["id"]
    )
    op.add_column("user", sa.Column("sap_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "sap_number")
    op.drop_constraint(op.f("fk_initiative_supervisor_id_user"), "initiative", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_initiative_project_owner_id_user"), "initiative", type_="foreignkey"
    )
    op.drop_column("initiative", "supervisor_id")
    op.drop_column("initiative", "project_owner_id")
    # ### end Alembic commands ###
