"""fkey ref

Revision ID: 9f550aa8f63e
Revises: 791adee8c2e8
Create Date: 2023-03-14 15:26:04.627738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f550aa8f63e'
down_revision = '791adee8c2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_improvement_initiative', sa.Column('initiative_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_general_improvement_initiative_initiative_base_initiative', 'general_improvement_initiative', type_='foreignkey')
    op.create_foreign_key(op.f('fk_general_improvement_initiative_initiative_id_base_initiative'), 'general_improvement_initiative', 'base_initiative', ['initiative_id'], ['id'], ondelete='CASCADE')
    op.drop_column('general_improvement_initiative', 'initiative')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_improvement_initiative', sa.Column('initiative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_general_improvement_initiative_initiative_id_base_initiative'), 'general_improvement_initiative', type_='foreignkey')
    op.create_foreign_key('fk_general_improvement_initiative_initiative_base_initiative', 'general_improvement_initiative', 'base_initiative', ['initiative'], ['id'])
    op.drop_column('general_improvement_initiative', 'initiative_id')
    # ### end Alembic commands ###
