"""initiatives/joined table inheritance

Revision ID: f012478a893d
Revises: 8da8e9fcd8c9
Create Date: 2023-03-22 04:56:53.052728

"""
import enum

import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = "f012478a893d"
down_revision = "8da8e9fcd8c9"
branch_labels = None
depends_on = None


Base = declarative_base()


class BaseInitiative(Base):
    __tablename__ = "base_initiative"
    id = sa.Column(sa.Integer, primary_key=True)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "base_initiative",
        "type",
        existing_type=sa.Integer(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    Session = sessionmaker(op.get_bind())
    with Session.begin() as session:
        session.query(BaseInitiative).delete()


def downgrade():
    Session = sessionmaker(op.get_bind())
    with Session.begin() as session:
        session.query(BaseInitiative).delete()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("base_initiative", "type")
    op.add_column(
        "base_initiative",
        sa.Column(
            "type",
            sa.String(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
