"""create static tables; equipment and organisational_unit

Revision ID: 221f003085b6
Revises: 34eecc811952
Create Date: 2023-02-23 07:25:45.678736

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "221f003085b6"
down_revision = "34eecc811952"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("functional_location", sa.String(), nullable=False),
        sa.Column("equipment_description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
    )
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_table(
        "organisational_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("area", sa.String(), nullable=False),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("team", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisational_unit")),
    )
    op.create_index(op.f("ix_organisational_unit_id"), "organisational_unit", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organisational_unit_id"), table_name="organisational_unit")
    op.drop_table("organisational_unit")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_table("equipment")
    # ### end Alembic commands ###
