"""status enums

Revision ID: cd16bde2a14e
Revises: 866d8f8c15c1
Create Date: 2023-03-10 07:05:42.699516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd16bde2a14e'
down_revision = '866d8f8c15c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_initiative_status_id_status'), 'initiative', 'status', ['status_id'], ['id'])
    op.drop_column('initiative', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_initiative_status_id_status'), 'initiative', type_='foreignkey')
    op.drop_column('initiative', 'status_id')
    # ### end Alembic commands ###
