"""enum lists

Revision ID: 80b459cdc891
Revises: 64353257144f
Create Date: 2023-02-27 06:29:58.274246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b459cdc891'
down_revision = '64353257144f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit__frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benefit__frequency'))
    )
    op.create_index(op.f('ix_benefit__frequency_id'), 'benefit__frequency', ['id'], unique=False)
    op.create_table('primary__driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_primary__driver'))
    )
    op.create_index(op.f('ix_primary__driver_id'), 'primary__driver', ['id'], unique=False)
    op.create_table('priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority'))
    )
    op.create_index(op.f('ix_priority_id'), 'priority', ['id'], unique=False)
    op.create_table('secondary__driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secondary__driver'))
    )
    op.create_index(op.f('ix_secondary__driver_id'), 'secondary__driver', ['id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status'))
    )
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trigger'))
    )
    op.create_index(op.f('ix_trigger_id'), 'trigger', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_id'), table_name='trigger')
    op.drop_table('trigger')
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_secondary__driver_id'), table_name='secondary__driver')
    op.drop_table('secondary__driver')
    op.drop_index(op.f('ix_priority_id'), table_name='priority')
    op.drop_table('priority')
    op.drop_index(op.f('ix_primary__driver_id'), table_name='primary__driver')
    op.drop_table('primary__driver')
    op.drop_index(op.f('ix_benefit__frequency_id'), table_name='benefit__frequency')
    op.drop_table('benefit__frequency')
    # ### end Alembic commands ###
