"""priority enum table; ref in initiative table

Revision ID: 034358a696db
Revises: cf418cb583b7
Create Date: 2023-03-01 23:13:29.859600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034358a696db'
down_revision = 'cf418cb583b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('priority_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_initiative_priority_id_priority'), 'initiative', 'priority', ['priority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_initiative_priority_id_priority'), 'initiative', type_='foreignkey')
    op.drop_column('initiative', 'priority_id')
    # ### end Alembic commands ###
