"""basic initiative schema - pass 1

Revision ID: 562096a9b571
Revises: 3ac09449c015
Create Date: 2023-02-16 09:38:27.757787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562096a9b571'
down_revision = '3ac09449c015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiative'))
    )
    op.create_index(op.f('ix_initiative_id'), 'initiative', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_initiative_id'), table_name='initiative')
    op.drop_table('initiative')
    # ### end Alembic commands ###
