"""initiative benefits add

Revision ID: 26af3a44eb20
Revises: 562096a9b571
Create Date: 2023-02-20 06:59:06.577684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26af3a44eb20'
down_revision = '562096a9b571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('initiative', sa.Column('tonnes', sa.Integer(), nullable=True))
    op.add_column('initiative', sa.Column('safety', sa.Integer(), nullable=True))
    op.add_column('initiative', sa.Column('availability', sa.Integer(), nullable=True))
    op.add_column('initiative', sa.Column('events', sa.Integer(), nullable=True))
    op.add_column('initiative', sa.Column('estimate_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initiative', 'estimate_notes')
    op.drop_column('initiative', 'events')
    op.drop_column('initiative', 'availability')
    op.drop_column('initiative', 'safety')
    op.drop_column('initiative', 'tonnes')
    op.drop_column('initiative', 'cost')
    # ### end Alembic commands ###
