"""add supervisor id to user table

Revision ID: be40b83036c4
Revises: 9f550aa8f63e
Create Date: 2023-03-21 12:07:04.256069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be40b83036c4'
down_revision = '9f550aa8f63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_supervisor_id_user'), 'user', 'user', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_supervisor_id_user'), 'user', type_='foreignkey')
    op.drop_column('user', 'supervisor_id')
    # ### end Alembic commands ###
