"""add benefit frequency

Revision ID: 3513ce8c4ee1
Revises: 011d84fdb7ac
Create Date: 2023-03-29 04:56:52.421879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3513ce8c4ee1'
down_revision = '011d84fdb7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('benefit_frequency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_initiative_benefit_frequency_id_benefit_frequency'), 'initiative', 'benefit_frequency', ['benefit_frequency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_initiative_benefit_frequency_id_benefit_frequency'), 'initiative', type_='foreignkey')
    op.drop_column('initiative', 'benefit_frequency_id')
    # ### end Alembic commands ###
