"""enums add cost_benefit_category_id

Revision ID: 8da8e9fcd8c9
Revises: 343eaef7bf73
Create Date: 2023-03-22 04:30:16.721641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da8e9fcd8c9'
down_revision = '343eaef7bf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_benefit_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_benefit_category'))
    )
    op.create_index(op.f('ix_cost_benefit_category_id'), 'cost_benefit_category', ['id'], unique=False)
    op.add_column('general_improvement_initiative', sa.Column('cost_benefit_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_general_improvement_initiative_cost_benefit_category_id_cost_benefit_category'), 'general_improvement_initiative', 'cost_benefit_category', ['cost_benefit_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_general_improvement_initiative_cost_benefit_category_id_cost_benefit_category'), 'general_improvement_initiative', type_='foreignkey')
    op.drop_column('general_improvement_initiative', 'cost_benefit_category_id')
    op.drop_index(op.f('ix_cost_benefit_category_id'), table_name='cost_benefit_category')
    op.drop_table('cost_benefit_category')
    # ### end Alembic commands ###
