"""enums implemented ; enums modularised

Revision ID: 33d7626403ed
Revises: cd16bde2a14e
Create Date: 2023-03-14 12:28:24.327053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7626403ed'
down_revision = 'cd16bde2a14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit__frequency', sa.Column('color', sa.String(), nullable=True))
    op.add_column('primary__driver', sa.Column('color', sa.String(), nullable=True))
    op.add_column('secondary__driver', sa.Column('color', sa.String(), nullable=True))
    op.add_column('trigger', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trigger', 'color')
    op.drop_column('secondary__driver', 'color')
    op.drop_column('primary__driver', 'color')
    op.drop_column('benefit__frequency', 'color')
    # ### end Alembic commands ###
