"""remove benefit frequency

Revision ID: 011d84fdb7ac
Revises: f59b62b1607a
Create Date: 2023-03-29 04:55:37.024896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011d84fdb7ac'
down_revision = 'f59b62b1607a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initiative', 'benefit_frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('benefit_frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
