"""base initiative fkey change

Revision ID: fd40196a795f
Revises: c462dcc58c5f
Create Date: 2023-03-14 13:15:52.670517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd40196a795f'
down_revision = 'c462dcc58c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_general_improvement_initiative_initiative_initiative', 'general_improvement_initiative', type_='foreignkey')
    op.create_foreign_key(op.f('fk_general_improvement_initiative_initiative_base_initiative'), 'general_improvement_initiative', 'base_initiative', ['initiative'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_general_improvement_initiative_initiative_base_initiative'), 'general_improvement_initiative', type_='foreignkey')
    op.create_foreign_key('fk_general_improvement_initiative_initiative_initiative', 'general_improvement_initiative', 'initiative', ['initiative'], ['id'])
    # ### end Alembic commands ###
