"""fixed initiative fks

Revision ID: 45bb9717b720
Revises: f59b62b1607a
Create Date: 2023-03-29 04:10:21.328639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bb9717b720'
down_revision = 'f59b62b1607a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('impact_ou_id', sa.Integer(), nullable=True))
    op.add_column('initiative', sa.Column('owner_ou_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_initiative_owner_ou_organisational_unit', 'initiative', type_='foreignkey')
    op.drop_constraint('fk_initiative_impact_ou_organisational_unit', 'initiative', type_='foreignkey')
    op.create_foreign_key(op.f('fk_initiative_impact_ou_id_organisational_unit'), 'initiative', 'organisational_unit', ['impact_ou_id'], ['id'])
    op.create_foreign_key(op.f('fk_initiative_owner_ou_id_organisational_unit'), 'initiative', 'organisational_unit', ['owner_ou_id'], ['id'])
    op.drop_column('initiative', 'owner_ou')
    op.drop_column('initiative', 'impact_ou')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('impact_ou', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('initiative', sa.Column('owner_ou', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_initiative_owner_ou_id_organisational_unit'), 'initiative', type_='foreignkey')
    op.drop_constraint(op.f('fk_initiative_impact_ou_id_organisational_unit'), 'initiative', type_='foreignkey')
    op.create_foreign_key('fk_initiative_impact_ou_organisational_unit', 'initiative', 'organisational_unit', ['impact_ou'], ['id'])
    op.create_foreign_key('fk_initiative_owner_ou_organisational_unit', 'initiative', 'organisational_unit', ['owner_ou'], ['id'])
    op.drop_column('initiative', 'owner_ou_id')
    op.drop_column('initiative', 'impact_ou_id')
    # ### end Alembic commands ###
