"""base initiative; general improvement initiative

Revision ID: c462dcc58c5f
Revises: 09a4c01801b0
Create Date: 2023-03-14 12:42:15.259823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c462dcc58c5f'
down_revision = '09a4c01801b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_initiative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_initiative', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('date_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_owner_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('change_request', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_initiative'], ['base_initiative.id'], name=op.f('fk_base_initiative_parent_initiative_base_initiative')),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], name=op.f('fk_base_initiative_priority_id_priority')),
    sa.ForeignKeyConstraint(['project_owner_id'], ['user.id'], name=op.f('fk_base_initiative_project_owner_id_user')),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_base_initiative_status_id_status')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], name=op.f('fk_base_initiative_supervisor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_initiative'))
    )
    op.create_index(op.f('ix_base_initiative_id'), 'base_initiative', ['id'], unique=False)
    op.create_table('general_improvement_initiative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('impact_ou', sa.Integer(), nullable=True),
    sa.Column('owner_ou', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.Integer(), nullable=True),
    sa.Column('primary_driver', sa.Integer(), nullable=True),
    sa.Column('secondary_driver', sa.Integer(), nullable=True),
    sa.Column('tonnes', sa.Integer(), nullable=True),
    sa.Column('safety', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('benefit_frequency', sa.Integer(), nullable=True),
    sa.Column('benefit_estimate_notes', sa.String(), nullable=True),
    sa.Column('notification', sa.String(), nullable=True),
    sa.Column('workorder', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['impact_ou'], ['organisational_unit.id'], name=op.f('fk_general_improvement_initiative_impact_ou_organisational_unit')),
    sa.ForeignKeyConstraint(['initiative'], ['initiative.id'], name=op.f('fk_general_improvement_initiative_initiative_initiative')),
    sa.ForeignKeyConstraint(['owner_ou'], ['organisational_unit.id'], name=op.f('fk_general_improvement_initiative_owner_ou_organisational_unit')),
    sa.ForeignKeyConstraint(['primary_driver'], ['primary_driver.id'], name=op.f('fk_general_improvement_initiative_primary_driver_primary_driver')),
    sa.ForeignKeyConstraint(['secondary_driver'], ['secondary_driver.id'], name=op.f('fk_general_improvement_initiative_secondary_driver_secondary_driver')),
    sa.ForeignKeyConstraint(['trigger'], ['trigger.id'], name=op.f('fk_general_improvement_initiative_trigger_trigger')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_improvement_initiative'))
    )
    op.create_index(op.f('ix_general_improvement_initiative_id'), 'general_improvement_initiative', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_general_improvement_initiative_id'), table_name='general_improvement_initiative')
    op.drop_table('general_improvement_initiative')
    op.drop_index(op.f('ix_base_initiative_id'), table_name='base_initiative')
    op.drop_table('base_initiative')
    # ### end Alembic commands ###
