"""add job_title to user

Revision ID: 34eecc811952
Revises: 26af3a44eb20
Create Date: 2023-02-21 22:44:58.406695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eecc811952'
down_revision = '26af3a44eb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job_title')
    # ### end Alembic commands ###
