"""initiatives/joined inheritance real setup

Revision ID: 853b26a6118b
Revises: f012478a893d
Create Date: 2023-03-22 09:42:51.356598

"""
import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = "1b70d19c641e"
down_revision = "f012478a893d"
branch_labels = None
depends_on = None


Base = declarative_base()


class GeneralImprovementInitiative(Base):
    __tablename__ = "general_improvement_initiative"
    id = sa.Column(sa.Integer(), primary_key=True)
    created = sa.Column(postgresql.TIMESTAMP(timezone=True))
    updated = sa.Column(postgresql.TIMESTAMP(timezone=True))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_general_improvement_initiative_id", table_name="general_improvement_initiative"
    )
    op.drop_constraint(
        "fk_general_improvement_initiative_initiative_id_base_initiative",
        "general_improvement_initiative",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_general_improvement_initiative_id_base_initiative"),
        "general_improvement_initiative",
        "base_initiative",
        ["id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("general_improvement_initiative", "updated")
    op.drop_column("general_improvement_initiative", "initiative_id")
    op.drop_column("general_improvement_initiative", "created")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "general_improvement_initiative",
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "general_improvement_initiative",
        sa.Column("initiative_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "general_improvement_initiative",
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_general_improvement_initiative_id_base_initiative"),
        "general_improvement_initiative",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_general_improvement_initiative_initiative_id_base_initiative",
        "general_improvement_initiative",
        "base_initiative",
        ["initiative_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_general_improvement_initiative_id",
        "general_improvement_initiative",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###
    Session = sessionmaker(op.get_bind())
    with Session.begin() as session:
        all_rows = session.query(GeneralImprovementInitiative).all()
        for row in all_rows:
            row.created = datetime.datetime.utcnow()
            row.updated = datetime.datetime.utcnow()
    op.alter_column("general_improvement_initiative", "created", nullable=False)
    op.alter_column("general_improvement_initiative", "updated", nullable=False)
