"""enums name changes -- camelcase

Revision ID: 09a4c01801b0
Revises: 33d7626403ed
Create Date: 2023-03-14 12:34:24.073476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09a4c01801b0'
down_revision = '33d7626403ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benefit_frequency'))
    )
    op.create_index(op.f('ix_benefit_frequency_id'), 'benefit_frequency', ['id'], unique=False)
    op.create_table('primary_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_primary_driver'))
    )
    op.create_index(op.f('ix_primary_driver_id'), 'primary_driver', ['id'], unique=False)
    op.create_table('secondary_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secondary_driver'))
    )
    op.create_index(op.f('ix_secondary_driver_id'), 'secondary_driver', ['id'], unique=False)
    op.drop_index('ix_primary__driver_id', table_name='primary__driver')
    op.drop_table('primary__driver')
    op.drop_index('ix_benefit__frequency_id', table_name='benefit__frequency')
    op.drop_table('benefit__frequency')
    op.drop_index('ix_secondary__driver_id', table_name='secondary__driver')
    op.drop_table('secondary__driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secondary__driver',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delete_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_secondary__driver')
    )
    op.create_index('ix_secondary__driver_id', 'secondary__driver', ['id'], unique=False)
    op.create_table('benefit__frequency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delete_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_benefit__frequency')
    )
    op.create_index('ix_benefit__frequency_id', 'benefit__frequency', ['id'], unique=False)
    op.create_table('primary__driver',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delete_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_primary__driver')
    )
    op.create_index('ix_primary__driver_id', 'primary__driver', ['id'], unique=False)
    op.drop_index(op.f('ix_secondary_driver_id'), table_name='secondary_driver')
    op.drop_table('secondary_driver')
    op.drop_index(op.f('ix_primary_driver_id'), table_name='primary_driver')
    op.drop_table('primary_driver')
    op.drop_index(op.f('ix_benefit_frequency_id'), table_name='benefit_frequency')
    op.drop_table('benefit_frequency')
    # ### end Alembic commands ###
