"""enum classes are deletable; enum classes scoped out

Revision ID: f73ed8ca1e5a
Revises: 80b459cdc891
Create Date: 2023-03-01 05:22:07.322843

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f73ed8ca1e5a"
down_revision = "80b459cdc891"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("benefit__frequency", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "benefit__frequency",
        sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("benefit__frequency", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("benefit__frequency", sa.Column("order", sa.Integer(), nullable=True))
    op.alter_column("benefit__frequency", "label", existing_type=sa.VARCHAR(), nullable=False)
    # op.drop_constraint('benefit__frequency_label_key', 'benefit__frequency', type_='unique')
    op.add_column("primary__driver", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "primary__driver", sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("primary__driver", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("primary__driver", sa.Column("order", sa.Integer(), nullable=True))
    op.alter_column("primary__driver", "label", existing_type=sa.VARCHAR(), nullable=False)
    # op.drop_constraint('primary__driver_label_key', 'primary__driver', type_='unique')
    op.add_column("priority", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "priority", sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("priority", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("priority", sa.Column("order", sa.Integer(), nullable=True))
    op.add_column("priority", sa.Column("color", sa.String(), nullable=True))
    op.alter_column("priority", "label", existing_type=sa.VARCHAR(), nullable=False)
    # op.drop_constraint('priority_label_key', 'priority', type_='unique')
    op.add_column("secondary__driver", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "secondary__driver", sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("secondary__driver", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("secondary__driver", sa.Column("order", sa.Integer(), nullable=True))
    op.alter_column("secondary__driver", "label", existing_type=sa.VARCHAR(), nullable=False)
    # op.drop_constraint('secondary__driver_label_key', 'secondary__driver', type_='unique')
    op.add_column("status", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column("status", sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True))
    op.add_column("status", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("status", sa.Column("order", sa.Integer(), nullable=True))
    op.add_column("status", sa.Column("color", sa.String(), nullable=True))
    op.alter_column("status", "label", existing_type=sa.VARCHAR(), nullable=False)
    # op.drop_constraint('status_label_key', 'status', type_='unique')
    op.add_column("trigger", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "trigger", sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("trigger", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("trigger", sa.Column("order", sa.Integer(), nullable=True))
    op.alter_column("trigger", "label", existing_type=sa.VARCHAR(), nullable=False)
    # op.drop_constraint("trigger_label_key", "trigger", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("trigger_label_key", "trigger", ["label"])
    op.alter_column("trigger", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("trigger", "order")
    op.drop_column("trigger", "is_deleted")
    op.drop_column("trigger", "delete_datetime")
    op.drop_column("trigger", "delete_user_id")
    op.create_unique_constraint("status_label_key", "status", ["label"])
    op.alter_column("status", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("status", "color")
    op.drop_column("status", "order")
    op.drop_column("status", "is_deleted")
    op.drop_column("status", "delete_datetime")
    op.drop_column("status", "delete_user_id")
    op.create_unique_constraint("secondary__driver_label_key", "secondary__driver", ["label"])
    op.alter_column("secondary__driver", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("secondary__driver", "order")
    op.drop_column("secondary__driver", "is_deleted")
    op.drop_column("secondary__driver", "delete_datetime")
    op.drop_column("secondary__driver", "delete_user_id")
    op.create_unique_constraint("priority_label_key", "priority", ["label"])
    op.alter_column("priority", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("priority", "color")
    op.drop_column("priority", "order")
    op.drop_column("priority", "is_deleted")
    op.drop_column("priority", "delete_datetime")
    op.drop_column("priority", "delete_user_id")
    op.create_unique_constraint("primary__driver_label_key", "primary__driver", ["label"])
    op.alter_column("primary__driver", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("primary__driver", "order")
    op.drop_column("primary__driver", "is_deleted")
    op.drop_column("primary__driver", "delete_datetime")
    op.drop_column("primary__driver", "delete_user_id")
    op.create_unique_constraint("benefit__frequency_label_key", "benefit__frequency", ["label"])
    op.alter_column("benefit__frequency", "label", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("benefit__frequency", "order")
    op.drop_column("benefit__frequency", "is_deleted")
    op.drop_column("benefit__frequency", "delete_datetime")
    op.drop_column("benefit__frequency", "delete_user_id")
    # ### end Alembic commands ###
