"""priority rem from initiative table

Revision ID: cf418cb583b7
Revises: f73ed8ca1e5a
Create Date: 2023-03-01 23:10:51.860434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf418cb583b7'
down_revision = 'f73ed8ca1e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initiative', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
