"""enum id ref change

Revision ID: 791adee8c2e8
Revises: fd40196a795f
Create Date: 2023-03-14 13:29:41.231670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791adee8c2e8'
down_revision = 'fd40196a795f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_improvement_initiative', sa.Column('trigger_id', sa.Integer(), nullable=True))
    op.add_column('general_improvement_initiative', sa.Column('primary_driver_id', sa.Integer(), nullable=True))
    op.add_column('general_improvement_initiative', sa.Column('secondary_driver_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_general_improvement_initiative_trigger_trigger', 'general_improvement_initiative', type_='foreignkey')
    op.drop_constraint('fk_general_improvement_initiative_primary_driver_primary_driver', 'general_improvement_initiative', type_='foreignkey')
    op.drop_constraint('fk_general_improvement_initiative_secondary_driver_seco_ba0e', 'general_improvement_initiative', type_='foreignkey')
    op.create_foreign_key(op.f('fk_general_improvement_initiative_primary_driver_id_primary_driver'), 'general_improvement_initiative', 'primary_driver', ['primary_driver_id'], ['id'])
    op.create_foreign_key(op.f('fk_general_improvement_initiative_trigger_id_trigger'), 'general_improvement_initiative', 'trigger', ['trigger_id'], ['id'])
    op.create_foreign_key(op.f('fk_general_improvement_initiative_secondary_driver_id_secondary_driver'), 'general_improvement_initiative', 'secondary_driver', ['secondary_driver_id'], ['id'])
    op.drop_column('general_improvement_initiative', 'primary_driver')
    op.drop_column('general_improvement_initiative', 'trigger')
    op.drop_column('general_improvement_initiative', 'secondary_driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_improvement_initiative', sa.Column('secondary_driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('general_improvement_initiative', sa.Column('trigger', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('general_improvement_initiative', sa.Column('primary_driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_general_improvement_initiative_secondary_driver_id_secondary_driver'), 'general_improvement_initiative', type_='foreignkey')
    op.drop_constraint(op.f('fk_general_improvement_initiative_trigger_id_trigger'), 'general_improvement_initiative', type_='foreignkey')
    op.drop_constraint(op.f('fk_general_improvement_initiative_primary_driver_id_primary_driver'), 'general_improvement_initiative', type_='foreignkey')
    op.create_foreign_key('fk_general_improvement_initiative_secondary_driver_seco_ba0e', 'general_improvement_initiative', 'secondary_driver', ['secondary_driver'], ['id'])
    op.create_foreign_key('fk_general_improvement_initiative_primary_driver_primary_driver', 'general_improvement_initiative', 'primary_driver', ['primary_driver'], ['id'])
    op.create_foreign_key('fk_general_improvement_initiative_trigger_trigger', 'general_improvement_initiative', 'trigger', ['trigger'], ['id'])
    op.drop_column('general_improvement_initiative', 'secondary_driver_id')
    op.drop_column('general_improvement_initiative', 'primary_driver_id')
    op.drop_column('general_improvement_initiative', 'trigger_id')
    # ### end Alembic commands ###
