"""merged initatives into one table

Revision ID: f59b62b1607a
Revises: 1b70d19c641e
Create Date: 2023-03-29 01:05:49.999459

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f59b62b1607a"
down_revision = "1b70d19c641e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initiative",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parent_initiative", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("date_opened", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_completion_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("project_owner_id", sa.Integer(), nullable=True),
        sa.Column("supervisor_id", sa.Integer(), nullable=True),
        sa.Column("priority_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("change_request", sa.String(), nullable=True),
        sa.Column("tonnes", sa.Integer(), nullable=True),
        sa.Column("safety", sa.Integer(), nullable=True),
        sa.Column("availability", sa.Integer(), nullable=True),
        sa.Column("events", sa.Integer(), nullable=True),
        sa.Column("benefit_frequency", sa.Integer(), nullable=True),
        sa.Column("benefit_estimate_notes", sa.String(), nullable=True),
        sa.Column("notification", sa.String(), nullable=True),
        sa.Column("workorder", sa.String(), nullable=True),
        sa.Column("impact_ou", sa.Integer(), nullable=True),
        sa.Column("owner_ou", sa.Integer(), nullable=True),
        sa.Column("primary_driver_id", sa.Integer(), nullable=True),
        sa.Column("secondary_driver_id", sa.Integer(), nullable=True),
        sa.Column("cost_benefit_category_id", sa.Integer(), nullable=True),
        sa.Column("floc_id", sa.Integer(), nullable=True),
        sa.Column("equipment_id", sa.Integer(), nullable=True),
        sa.Column("maintenance_plan", sa.String(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("purchase_request", sa.String(), nullable=True),
        sa.Column("purchase_order", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cost_benefit_category_id"],
            ["cost_benefit_category.id"],
            name=op.f("fk_initiative_cost_benefit_category_id_cost_benefit_category"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.id"], name=op.f("fk_initiative_equipment_id_equipment")
        ),
        sa.ForeignKeyConstraint(["floc_id"], ["floc.id"], name=op.f("fk_initiative_floc_id_floc")),
        sa.ForeignKeyConstraint(
            ["impact_ou"],
            ["organisational_unit.id"],
            name=op.f("fk_initiative_impact_ou_organisational_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_ou"],
            ["organisational_unit.id"],
            name=op.f("fk_initiative_owner_ou_organisational_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_initiative"],
            ["initiative.id"],
            name=op.f("fk_initiative_parent_initiative_initiative"),
        ),
        sa.ForeignKeyConstraint(
            ["primary_driver_id"],
            ["primary_driver.id"],
            name=op.f("fk_initiative_primary_driver_id_primary_driver"),
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"], ["priority.id"], name=op.f("fk_initiative_priority_id_priority")
        ),
        sa.ForeignKeyConstraint(
            ["project_owner_id"], ["user.id"], name=op.f("fk_initiative_project_owner_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["secondary_driver_id"],
            ["secondary_driver.id"],
            name=op.f("fk_initiative_secondary_driver_id_secondary_driver"),
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["status.id"], name=op.f("fk_initiative_status_id_status")
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"], ["user.id"], name=op.f("fk_initiative_supervisor_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_initiative")),
    )
    op.create_index(op.f("ix_initiative_id"), "initiative", ["id"], unique=False)
    op.create_table(
        "initiative_trigger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger_id", sa.Integer(), nullable=True),
        sa.Column("initiative_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["initiative_id"],
            ["initiative.id"],
            name=op.f("fk_initiative_trigger_initiative_id_initiative"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["trigger.id"],
            name=op.f("fk_initiative_trigger_trigger_id_trigger"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_initiative_trigger")),
    )
    op.create_index(op.f("ix_initiative_trigger_id"), "initiative_trigger", ["id"], unique=False)
    op.drop_index("ix_base_initiative_id", table_name="base_initiative")
    op.drop_index(
        "ix_general_improvement_initiative_triggers_association_id",
        table_name="general_improvement_initiative_triggers_association",
    )
    op.drop_table("general_improvement_initiative_triggers_association")
    op.drop_table("general_improvement_initiative")
    op.drop_table("base_initiative")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "general_improvement_initiative_triggers_association",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("trigger_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("initiative_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["initiative_id"],
            ["general_improvement_initiative.id"],
            name="fk_general_improvement_initiative_triggers_association__609f",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["trigger.id"],
            name="fk_general_improvement_initiative_triggers_association__9038",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name="pk_general_improvement_initiative_triggers_association"
        ),
    )
    op.create_index(
        "ix_general_improvement_initiative_triggers_association_id",
        "general_improvement_initiative_triggers_association",
        ["id"],
        unique=False,
    )
    op.create_table(
        "base_initiative",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('base_initiative_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("parent_initiative", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "date_opened", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "target_completion_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("project_owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("supervisor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("priority_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("change_request", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_initiative"],
            ["base_initiative.id"],
            name="fk_base_initiative_parent_initiative_base_initiative",
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"], ["priority.id"], name="fk_base_initiative_priority_id_priority"
        ),
        sa.ForeignKeyConstraint(
            ["project_owner_id"], ["user.id"], name="fk_base_initiative_project_owner_id_user"
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["status.id"], name="fk_base_initiative_status_id_status"
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"], ["user.id"], name="fk_base_initiative_supervisor_id_user"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_base_initiative"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_base_initiative_id", "base_initiative", ["id"], unique=False)
    op.create_table(
        "general_improvement_initiative",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("impact_ou", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("owner_ou", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tonnes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("safety", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("availability", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("events", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("benefit_frequency", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("benefit_estimate_notes", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("notification", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("workorder", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("primary_driver_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("secondary_driver_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cost_benefit_category_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["cost_benefit_category_id"],
            ["cost_benefit_category.id"],
            name="fk_general_improvement_initiative_cost_benefit_category_d133",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["base_initiative.id"],
            name="fk_general_improvement_initiative_id_base_initiative",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["impact_ou"],
            ["organisational_unit.id"],
            name="fk_general_improvement_initiative_impact_ou_organisational_unit",
        ),
        sa.ForeignKeyConstraint(
            ["owner_ou"],
            ["organisational_unit.id"],
            name="fk_general_improvement_initiative_owner_ou_organisational_unit",
        ),
        sa.ForeignKeyConstraint(
            ["primary_driver_id"],
            ["primary_driver.id"],
            name="fk_general_improvement_initiative_primary_driver_id_pri_a3a4",
        ),
        sa.ForeignKeyConstraint(
            ["secondary_driver_id"],
            ["secondary_driver.id"],
            name="fk_general_improvement_initiative_secondary_driver_id_s_bb39",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_general_improvement_initiative"),
    )
    op.drop_index(op.f("ix_initiative_trigger_id"), table_name="initiative_trigger")
    op.drop_table("initiative_trigger")
    op.drop_index(op.f("ix_initiative_id"), table_name="initiative")
    op.drop_table("initiative")
    # ### end Alembic commands ###
