"""todo

Revision ID: 64353257144f
Revises: a5b3bc1d6eda
Create Date: 2023-02-23 10:02:10.045451

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64353257144f"
down_revision = "a5b3bc1d6eda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_equip_location_description",
        "equipment",
        ["functional_location", "equipment_description"],
    )
    op.create_unique_constraint(
        "uq_ou_area_dep_team", "organisational_unit", ["area", "department", "team"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ou_area_dep_team", "organisational_unit", type_="unique")
    op.drop_constraint("uq_equip_location_description", "equipment", type_="unique")
    # ### end Alembic commands ###
