import StatusEnumIcon from "@/components/Global/StatusEnumIcon";
import PriorityEnumIcon from "@/components/Global/PriorityEnumIcon";
import UsersTooltip from "@/components/TableHelpers/UsersTooltip.vue";

export default ({ app, store }, inject) => {
  inject("table_headers", {
    // ----------------------------------
    // INVESTIGATION TABLES
    // ----------------------------------
    investigation: [
      {
        text: "#",
        align: "center",
        value: "id",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Investigation",
        value: "investigation",
        sortable: false,
        divider: true,
        align: "center",
        hide: false,
        width: "10",
      },
      {
        text: "Actions",
        value: "actions",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Title",
        value: "title",
        hide: false,
        divider: true,
        cellClass: "title-cell",
      },
      {
        text: "Incident Date",
        value: "event_datetime",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        width: "10",
      },
      {
        text: "Status",
        value: "status",
        divider: true,
        align: "center",
        component: StatusEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Priority",
        value: "priority",
        align: "center",
        divider: true,
        component: PriorityEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Investigation Type",
        value: "investigation_type",
        divider: true,
        align: "center",
        formatter: (x) => app.$enums.investigation_types[x],
        hide: false,
        width: "10",
      },
      {
        text: "Site",
        value: "site",
        hide: false,
        divider: true,
        cellClass: "nowrap",
        sortable: false,
      },
      {
        text: "Department",
        value: "department",
        hide: false,
        divider: true,
        cellClass: "nowrap",
        sortable: false,
      },
      {
        text: "FLOC",
        value: "function_location",
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Owners",
        value: "owner_ids",
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a))
            .sort()
            .join(", "),
        sortable: false,
        hide: false,
        divider: true,
        cellClass: "title-cell",
      },
      {
        text: "Total Event Duration (hrs)",
        value: "total_event_duration",
        formatter: (x) => (x || x == 0 ? x.toFixed(1) : ""),
        hide: false,
        divider: true,
        width: "10",
        class: "wrap-header",
      },
      {
        text: "Total Effective Duration (hrs)",
        value: "total_effective_duration",
        formatter: (x) => (x || x == 0 ? x.toFixed(1) : ""),
        hide: false,
        divider: true,
        width: "10",
        class: "wrap-header",
      },
      {
        text: "Total Lost Tonnes",
        value: "total_tonnes_lost",
        formatter: (x) => app.$format.commarize(Math.round(x)),
        hide: false,
        divider: true,
        width: "10",
        class: "wrap-header",
      },
      {
        text: "Equipment",
        value: "equipment_description",
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Object Type",
        value: "object_type",
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Object Part",
        value: "object_part_description",
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Damage Code",
        value: "damage_code",
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Cause",
        value: "cause_code",
        formatter: (x) => (x ? x : ""),
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Supervisor",
        value: "supervisor_id",
        formatter: (x) => app.$utils.getUserName(x),
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Last Updated",
        value: "updated",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        width: "10",
      },
      {
        text: "Investigation Due",
        value: "completion_due_date",
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: "110",
        class: "wrap-header",
      },
      {
        text: "Created",
        value: "created",
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: "10",
      },
      {
        text: "Date Closed",
        value: "date_closed",
        formatter: (x) => (x ? app.$format.date(x) : ""),
        divider: true,
        width: "10",
      },
      {
        text: "Archive Status",
        value: "is_archived",
        align: "center",
        divider: true,
        width: "10",
      },
    ],
    relevant_investigation: [
      {
        text: "Relevant",
        value: "relevant",
        sortable: false,
        divider: true,
        hide: false,
      },
      {
        text: "#",
        align: "center",
        value: "id",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "View",
        value: "view",
        sortable: false,
        divider: true,
        hide: false,
      },
      {
        text: "Title",
        value: "title",
        hide: false,
        divider: true,
        cellClass: "wrap-text",
        width: "320",
      },
      {
        text: "Incident Date",
        value: "event_datetime",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        width: "10",
      },
      {
        text: "Status",
        value: "status",
        divider: true,
        align: "center",
        component: StatusEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Priority",
        value: "priority",
        align: "center",
        divider: true,
        component: PriorityEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Investigation Type",
        value: "investigation_type",
        divider: true,
        align: "center",
        formatter: (x) => app.$enums.investigation_types[x],
        hide: false,
        width: "10",
      },
      {
        text: "Site",
        value: "site",
        hide: false,
        divider: true,
        width: "100",
      },
      {
        text: "Department",
        value: "department",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "FLOC",
        value: "function_location",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Owners",
        value: "owners",
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a?.user_id))
            .sort()
            .join(", "),
        hide: false,
        divider: true,
        width: "150",
        sortable: false,
      },
      {
        text: "Total Event Duration (hrs)",
        value: "total_event_duration",
        formatter: (x) => (x || x == 0 ? x.toFixed(1) : ""),
        hide: false,
        divider: true,
        width: "110",
        class: "wrap-header",
      },
      {
        text: "Total Effective Duration (hrs)",
        value: "total_effective_duration",
        formatter: (x) => (x || x == 0 ? x.toFixed(1) : ""),
        hide: false,
        divider: true,
        width: "150",
        class: "wrap-header",
      },
      {
        text: "Total Lost Tonnes",
        value: "total_tonnes_lost",
        formatter: (x) => (x || x == 0 ? x.toFixed().toLocaleString() : ""),
        hide: false,
        divider: true,
        width: "110",
        class: "wrap-header",
      },
      {
        text: "Equipment",
        value: "equipment_description",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Object Type",
        value: "object_type",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Object Part",
        value: "object_part_description",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Damage Code",
        value: "damage_code",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Cause",
        value: "cause_code",
        formatter: (x) => (x ? x : ""),
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Supervisor",
        value: "supervisor_id",
        formatter: (x) => app.$utils.getUserName(x),
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Last Updated",
        value: "updated",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        width: "10",
      },

      {
        text: "Date Closed",
        value: "date_closed",
        formatter: (x) => (x ? app.$format.date(x) : ""),
        divider: true,
        width: "10",
      },
      {
        text: "Created",
        value: "created",
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: "10",
      },
      {
        text: "Investigation Due",
        value: "completion_due_date",
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: "110",
        class: "wrap-header",
      },
    ],
    investigation_alert: [
      {
        text: "#",
        align: "center",
        value: "id",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Investigation",
        value: "investigation",
        sortable: false,
        divider: true,
        align: "center",
        hide: false,
      },

      {
        text: "Actions",
        value: "actions",
        sortable: false,
        divider: true,
        hide: false,
      },
      {
        text: "Title",
        value: "title",
        hide: false,
        divider: true,
        cellClass: "wrap-text",
        width: "320",
      },
      {
        text: "Incident Date",
        value: "event_datetime",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        width: "10",
      },
      {
        text: "Status",
        value: "status",
        divider: true,
        align: "center",
        component: StatusEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Priority",
        value: "priority",
        align: "center",
        divider: true,
        component: PriorityEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Investigation Type",
        value: "investigation_type",
        divider: true,
        align: "center",
        formatter: (x) => app.$enums.investigation_types[x],
        hide: false,
        width: "10",
      },
      {
        text: "Site",
        value: "site",
        hide: false,
        divider: true,
        width: "100",
      },
      {
        text: "Department",
        value: "department",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "FLOC",
        value: "function_location",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Owners",
        value: "owners",
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a?.user_id))
            .sort()
            .join(", "),
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Total Event Duration (hrs)",
        value: "total_event_duration",
        formatter: (x) => (x || x == 0 ? x.toFixed(1) : ""),
        hide: false,
        divider: true,
        width: "110",
        class: "wrap-header",
      },
      {
        text: "Total Effective Duration (hrs)",
        value: "total_effective_duration",
        formatter: (x) => (x || x == 0 ? x.toFixed(1) : ""),
        hide: false,
        divider: true,
        width: "150",
        class: "wrap-header",
      },
      {
        text: "Total Lost Tonnes",
        value: "total_tonnes_lost",
        formatter: (x) => (x || x == 0 ? x.toFixed().toLocaleString() : ""),
        hide: false,
        divider: true,
        width: "110",
        class: "wrap-header",
      },

      {
        text: "Equipment",
        value: "equipment_description",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Object Type",
        value: "object_type",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Object Part",
        value: "object_part_description",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Damage Code",
        value: "damage_code",
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Cause",
        value: "root_cause_detail.cause_code",
        formatter: (x) => (x ? x : ""),
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Supervisor",
        value: "supervisor_id",
        formatter: (x) => app.$utils.getUserName(x),
        hide: false,
        divider: true,
        width: "150",
      },
      {
        text: "Last Updated",
        value: "updated",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        width: "10",
      },
      {
        text: "Date Closed",
        value: "date_closed",
        formatter: (x) => (x ? app.$format.date(x) : ""),
        divider: true,
        width: "10",
      },
      {
        text: "Created",
        value: "created",
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: "10",
      },
      {
        text: "Investigation Due",
        value: "completion_due_date",
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: "110",
        class: "wrap-header",
      },
    ],
    // ----------------------------------
    // ACTION TABLES
    // ----------------------------------
    action: [
      {
        text: "#",
        align: "center",
        value: "id",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Edit",
        value: "edit",
        align: "center",
        divider: true,
        sortable: false,
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Action",
        value: "title",
        cellClass: "title-cell",
        hide: false,
        divider: true,
      },
      {
        text: "Investigation",
        value: "investigation",
        divider: true,
        sortable: false,
        hide: false,
        cellClass: "title-cell",
        divider: true,
      },
      {
        text: "Date Due",
        value: "date_due",
        formatter: (x) => app.$format.date(x),
        hide: false,
        divider: true,
        cellClass: "nowrap",
      },
      {
        text: "Owner",
        value: "owners",
        hide: false,
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a?.user_id))
            .sort()
            .join(", "),
        cellClass: "title-cell",
        divider: true,
        sortable: false,
      },
      {
        text: "Members",
        value: "members",
        hide: false,
        component: UsersTooltip,
        cellClass: "title-cell",
        divider: true,
        sortable: false,
      },
      {
        text: "Priority",
        value: "priority",
        align: "center",
        divider: true,
        component: PriorityEnumIcon,
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Status",
        value: "status",
        align: "center",
        component: StatusEnumIcon,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Date Closed",
        value: "date_closed",
        cellClass: "nowrap",
        hide: false,
        formatter: (x) => (x ? app.$format.date(x) : ""),
        width: "10",
        divider: true,
      },
      {
        text: "Supervisor",
        value: "supervisor_id",
        formatter: (x) => app.$utils.getUserName(x),
        cellClass: "nowrap",
        hide: false,
        divider: true,
      },
      {
        text: "Source",
        value: "source",
        align: "center",
        divider: true,
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Date Created",
        value: "created",
        formatter: (x) => app.$format.date(x),
        hide: false,
        cellClass: "nowrap",
        divider: true,
      },
      {
        text: "Last Updated",
        value: "updated",
        formatter: (x) => app.$format.date(x),
        cellClass: "nowrap",
        hide: false,
        width: "10",
        divider: true,
      },
      // ---
      // {
      //   text: "Description",
      //   value: "description",
      //   cellClass: "wrap-text",
      //   hide: false,
      //   width: "320",
      //   divider: true,
      // },

      // {
      //   text: "Image",
      //   value: "image",
      //   sortable: false,
      //   divider: true,
      //   hide: false,
      //   width: "10",
      // },
      {
        text: "Archive Status",
        value: "is_archived",
        align: "center",
        divider: true,
        width: "10",
      },
    ],
    simple_action: [
      {
        text: "#",
        align: "center",
        value: "id",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Edit",
        value: "edit",
        width: "20",
        align: "center",
        divider: true,
        sortable: false,
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Action",
        value: "title",
        cellClass: "wrap-text",
        hide: false,
        width: "320",
        divider: true,
      },
      {
        text: "Date Due",
        value: "date_due",
        formatter: (x) => app.$format.date(x),
        width: "120",
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Owner",
        value: "owners",
        hide: false,
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a?.user_id))
            .sort()
            .join(", "),
        width: "150",
        divider: true,
      },
      {
        text: "Members",
        value: "members",
        hide: false,
        component: UsersTooltip,
        cellClass: "title-cell",
        divider: true,
        sortable: false,
      },
      {
        text: "Priority",
        value: "priority",
        align: "center",
        divider: true,
        component: PriorityEnumIcon,
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Status",
        value: "status",
        align: "center",
        divider: true,
        component: StatusEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Image",
        value: "image",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Date Closed",
        value: "date_closed",
        width: "120",
        hide: false,
        formatter: (x) => (x ? app.$format.date(x) : ""),
        width: "10",
        // divider: true,
      },
      {
        text: "Supervisor",
        value: "supervisor_id",
        formatter: (x) => app.$utils.getUserName(x),
        cellClass: "nowrap",
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Date Created",
        value: "created",
        formatter: (x) => app.$format.date(x),
        width: "125",
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Last Updated",
        value: "updated",
        formatter: (x) => app.$format.date(x),
        width: "125",
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Remove",
        value: "remove",
        hide: false,
        width: "10",
        align: "center",
        sortable: false,
      },
    ],
    action_alert: [
      {
        text: "#",
        align: "center",
        value: "id",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Action",
        value: "action",
        sortable: false,
        divider: true,
        align: "center",
        hide: false,
        width: "20",
      },
      {
        text: "Title",
        value: "title",
        cellClass: "wrap-text",
        hide: false,
        width: "320",
        divider: true,
      },
      {
        text: "Date Due",
        value: "date_due",
        formatter: (x) => app.$format.date(x),
        width: "120",
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Owner",
        value: "owners",
        hide: false,
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a?.user_id))
            .sort()
            .join(", "),
        width: "150",
        divider: true,
      },
      {
        text: "Members",
        value: "members",
        hide: false,
        component: UsersTooltip,
        cellClass: "title-cell",
        divider: true,
        sortable: false,
      },
      {
        text: "Priority",
        value: "priority",
        align: "center",
        divider: true,
        component: PriorityEnumIcon,
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Status",
        value: "status",
        align: "center",
        divider: true,
        component: StatusEnumIcon,
        hide: false,
        width: "10",
      },
      {
        text: "Image",
        value: "image",
        sortable: false,
        divider: true,
        hide: false,
        width: "10",
      },
      {
        text: "Date Closed",
        value: "date_closed",
        width: "120",
        hide: false,
        formatter: (x) => (x ? app.$format.date(x) : ""),
        width: "10",
        divider: true,
      },
      {
        text: "Supervisor",
        value: "supervisor_id",
        formatter: (x) => app.$utils.getUserName(x),
        cellClass: "nowrap",
        hide: false,
        width: "10",
        divider: true,
      },
      // ---

      // {
      //   text: "Description",
      //   value: "description",
      //   cellClass: "wrap-text",
      //   hide: false,
      //   width: "320",
      //   divider: true,
      // },

      {
        text: "Date Created",
        value: "created",
        formatter: (x) => app.$format.date(x),
        width: "125",
        hide: false,
        width: "10",
        divider: true,
      },
      {
        text: "Last Updated",
        value: "updated",
        formatter: (x) => app.$format.date(x),
        width: "125",
        hide: false,
        width: "10",
        divider: true,
      },
    ],
  });
};
