"""Fmg Employees Table

Revision ID: 8176b6268dd0
Revises: 4061ab48197d
Create Date: 2022-06-02 09:52:39.196175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8176b6268dd0'
down_revision = '4061ab48197d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fmg_Employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sap_number', sa.Integer(), nullable=False),
    sa.Column('key_vendor_employer', sa.Integer(), nullable=True),
    sa.Column('key_org_unit', sa.Integer(), nullable=True),
    sa.Column('key_employee_supervisor', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('employment_basis', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sap_number')
    )
    op.create_index(op.f('ix_Fmg_Employees_id'), 'Fmg_Employees', ['id'], unique=False)
    op.create_foreign_key(None, 'Action', 'User', ['supervisor_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Action', type_='foreignkey')
    op.drop_index(op.f('ix_Fmg_Employees_id'), table_name='Fmg_Employees')
    op.drop_table('Fmg_Employees')
    # ### end Alembic commands ###
