"""Foreign Key Changes

Revision ID: 597954080913
Revises: 1aefe1f8d356
Create Date: 2022-06-23 01:39:06.332240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597954080913'
down_revision = '1aefe1f8d356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Action', 'Fmg_Employees', ['supervisor_user_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Action', type_='foreignkey')
    # ### end Alembic commands ###
