"""rem all schemas (well most of them)

Revision ID: 0f3c6b549907
Revises: 1dd2486b0956
Create Date: 2022-10-07 07:20:41.684002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0f3c6b549907"
down_revision = "1dd2486b0956"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_General_Attachment_id", table_name="General_Attachment")
    op.drop_table("General_Attachment")
    op.drop_index("ix_Attachment_id", table_name="Attachment")
    op.drop_table("Attachment")
    op.drop_index("ix_Workgroup_Action_Association_id", table_name="Workgroup_Action_Association")
    op.drop_table("Workgroup_Action_Association")
    op.drop_index("ix_Workgroup_Admin_Association_id", table_name="Workgroup_Admin_Association")
    op.drop_table("Workgroup_Admin_Association")
    op.drop_index("ix_Workgroup_Owner_Association_id", table_name="Workgroup_Owner_Association")
    op.drop_table("Workgroup_Owner_Association")
    op.drop_index("ix_Workgroup_id", table_name="Workgroup")
    op.drop_table("Workgroup")
    op.drop_index("ix_Action_Owner_Association_id", table_name="Action_Owner_Association")
    op.drop_table("Action_Owner_Association")
    op.drop_index("ix_Action_Comments_id", table_name="Action_Comments")
    op.drop_table("Action_Comments")
    op.drop_index("ix_Action_id", table_name="Action")
    op.drop_table("Action")
    # ### end Alembic commands ###


def downgrade():
    # I DOUBT THIS DOWNGRADE WILL WORK...
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Workgroup_Action_Association",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Workgroup_Action_Association_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("action_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("workgroup_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["Action.id"],
            name="fk_Workgroup_Action_Association_action_id_Action",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workgroup_id"],
            ["Workgroup.id"],
            name="fk_Workgroup_Action_Association_workgroup_id_Workgroup",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Workgroup_Action_Association"),
    )
    op.create_index(
        "ix_Workgroup_Action_Association_id", "Workgroup_Action_Association", ["id"], unique=False
    )
    op.create_table(
        "Attachment",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Attachment_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("action_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("extension", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("uploaded_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "deleted_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("unique_filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"], ["Action.id"], name="fk_Attachment_action_id_Action", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Attachment"),
    )
    op.create_index("ix_Attachment_id", "Attachment", ["id"], unique=False)
    op.create_table(
        "Workgroup",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Workgroup_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("functional_location", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("closed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "date_closed", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("privacy_rating", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_archived", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("archived_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_confidential", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_Workgroup"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_Workgroup_id", "Workgroup", ["id"], unique=False)
    op.create_table(
        "General_Attachment",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"General_Attachment_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("unique_filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("uploaded_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "deleted_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("deleted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("feedback_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["Action.id"],
            name="fk_General_Attachment_action_id_Action",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["User.id"],
            name="fk_General_Attachment_deleted_by_User",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["Feedback.id"],
            name="fk_General_Attachment_feedback_id_Feedback",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["User.id"],
            name="fk_General_Attachment_uploaded_by_User",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_General_Attachment"),
    )
    op.create_index("ix_General_Attachment_id", "General_Attachment", ["id"], unique=False)
    op.create_table(
        "Action",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Action_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "date_due", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("completion", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action_status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "date_closed", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("function_location", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("linked_system_event_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("supervisor_user_email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("action_tag", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("linked_system", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_archived", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("archived_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("workgroup_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_confidential", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["supervisor_user_email"],
            ["Fmg_Employees.email"],
            name="fk_Action_supervisor_user_email_Fmg_Employees",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Action"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_Action_id", "Action", ["id"], unique=False)
    op.create_table(
        "Action_Comments",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Action_Comments_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("action_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "datetime", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("fullname", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["action_id"], ["Action.id"], name="fk_Action_Comments_action_id_Action"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"], name="fk_Action_Comments_user_id_User"),
        sa.PrimaryKeyConstraint("id", name="pk_Action_Comments"),
    )
    op.create_index("ix_Action_Comments_id", "Action_Comments", ["id"], unique=False)
    op.create_table(
        "Action_Owner_Association",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Action_Owner_Association_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("action_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["Action.id"],
            name="fk_Action_Owner_Association_action_id_Action",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_email"],
            ["Fmg_Employees.email"],
            name="fk_Action_Owner_Association_user_email_Fmg_Employees",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Action_Owner_Association"),
    )
    op.create_index(
        "ix_Action_Owner_Association_id", "Action_Owner_Association", ["id"], unique=False
    )
    op.create_table(
        "Workgroup_Owner_Association",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Workgroup_Owner_Association_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("workgroup_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_email"],
            ["Fmg_Employees.email"],
            name="fk_Workgroup_Owner_Association_user_email_Fmg_Employees",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workgroup_id"],
            ["Workgroup.id"],
            name="fk_Workgroup_Owner_Association_workgroup_id_Workgroup",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Workgroup_Owner_Association"),
    )
    op.create_index(
        "ix_Workgroup_Owner_Association_id", "Workgroup_Owner_Association", ["id"], unique=False
    )
    op.create_table(
        "Workgroup_Admin_Association",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Workgroup_Admin_Association_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("workgroup_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_email"],
            ["Fmg_Employees.email"],
            name="fk_Workgroup_Admin_Association_user_email_Fmg_Employees",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workgroup_id"],
            ["Workgroup.id"],
            name="fk_Workgroup_Admin_Association_workgroup_id_Workgroup",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Workgroup_Admin_Association"),
    )
    op.create_index(
        "ix_Workgroup_Admin_Association_id", "Workgroup_Admin_Association", ["id"], unique=False
    )
    # ### end Alembic commands ###
