"""Action Table expansion

Revision ID: eef74adf543f
Revises: f8b6bcc00be4
Create Date: 2022-06-01 07:31:15.405492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef74adf543f'
down_revision = 'f8b6bcc00be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('function_location', sa.String(), nullable=True))
    op.add_column('Action', sa.Column('supervisor_user_id', sa.Integer(), nullable=True))
    op.add_column('Action', sa.Column('linked_system_event_id', sa.String(), nullable=True))
    op.add_column('Action', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_column('Action', 'floc')
    op.drop_column('Action', 'linked_system')
    op.drop_column('Action', 'supervisor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('supervisor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Action', sa.Column('linked_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Action', sa.Column('floc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Action', 'created_by')
    op.drop_column('Action', 'created_date')
    op.drop_column('Action', 'linked_system_event_id')
    op.drop_column('Action', 'supervisor_user_id')
    op.drop_column('Action', 'function_location')
    # ### end Alembic commands ###
