"""Action Changes and removal of useless

Revision ID: e3e27b45ffc4
Revises: 66e46da061d6
Create Date: 2022-07-27 03:42:29.856454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3e27b45ffc4'
down_revision = '66e46da061d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('action_tag', sa.String(), nullable=True))
    op.drop_column('Action', 'last_updated_date')
    op.drop_column('Action', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Action', sa.Column('last_updated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Action', 'action_tag')
    # ### end Alembic commands ###
