"""Changes to TxOilSample

Revision ID: 86c4a8ee8297
Revises: 8f07e19a1ff5
Create Date: 2022-07-06 00:37:28.318150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c4a8ee8297'
down_revision = '8f07e19a1ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ahm_TxOilSample', sa.Column('site_name', sa.String(), nullable=True))
    op.add_column('Ahm_TxOilSample', sa.Column('area_name', sa.String(), nullable=True))
    op.add_column('Ahm_TxOilSample', sa.Column('asset_class', sa.String(), nullable=True))
    op.add_column('Ahm_TxOilSample', sa.Column('tag_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Ahm_TxOilSample', 'tag_number')
    op.drop_column('Ahm_TxOilSample', 'asset_class')
    op.drop_column('Ahm_TxOilSample', 'area_name')
    op.drop_column('Ahm_TxOilSample', 'site_name')
    # ### end Alembic commands ###
