"""action 2, dates

Revision ID: d15c930eb80a
Revises: ea89c1d509be
Create Date: 2022-10-21 07:22:50.055528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15c930eb80a'
down_revision = 'ea89c1d509be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action2', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action2', sa.Column('date_due', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action2', 'date_due')
    op.drop_column('Action2', 'start_date')
    # ### end Alembic commands ###
