"""Foreign Key Changes

Revision ID: 1aefe1f8d356
Revises: 6f085d81e7dc
Create Date: 2022-06-23 01:38:33.975765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aefe1f8d356'
down_revision = '6f085d81e7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Fmg_Employees', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Fmg_Employees', type_='unique')
    # ### end Alembic commands ###
