"""schemas.Action holds owner_ids array as column now

Revision ID: 64338efc9960
Revises: 5c2f6bc395c9
Create Date: 2022-10-09 10:54:25.384950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64338efc9960'
down_revision = '5c2f6bc395c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('owner_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'owner_ids')
    # ### end Alembic commands ###
