"""Is_archived addition

Revision ID: b3c7a660188b
Revises: d5fce547b542
Create Date: 2022-08-24 02:14:32.800513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c7a660188b'
down_revision = 'd5fce547b542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('Action', sa.Column('archived_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'archived_by')
    op.drop_column('Action', 'is_archived')
    # ### end Alembic commands ###
