"""remove

Revision ID: 0abc370d106b
Revises: ed12f25f1129
Create Date: 2022-06-09 00:51:40.584781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abc370d106b'
down_revision = 'ed12f25f1129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_IngestedUser_email', table_name='IngestedUser')
    op.drop_index('ix_IngestedUser_id', table_name='IngestedUser')
    op.drop_index('ix_IngestedUser_sap_number', table_name='IngestedUser')
    op.drop_table('IngestedUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IngestedUser',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"IngestedUser_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sap_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='IngestedUser_pkey')
    )
    op.create_index('ix_IngestedUser_sap_number', 'IngestedUser', ['sap_number'], unique=False)
    op.create_index('ix_IngestedUser_id', 'IngestedUser', ['id'], unique=False)
    op.create_index('ix_IngestedUser_email', 'IngestedUser', ['email'], unique=False)
    # ### end Alembic commands ###
