"""Action assoc changes

Revision ID: 6f085d81e7dc
Revises: 42f728bef685
Create Date: 2022-06-22 06:07:06.758173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f085d81e7dc'
down_revision = '42f728bef685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action_Owner_Association', sa.Column('user_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Action_Owner_Association', 'User', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('Action_Owner_Association', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action_Owner_Association', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Action_Owner_Association', type_='foreignkey')
    op.drop_column('Action_Owner_Association', 'user_email')
    # ### end Alembic commands ###
