"""schemas.Action_Association table remove

Revision ID: 5d7bbc0353a8
Revises: 64338efc9960
Create Date: 2022-10-09 10:57:52.916330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d7bbc0353a8'
down_revision = '64338efc9960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Action_Owner_Association_id', table_name='Action_Owner_Association')
    op.drop_table('Action_Owner_Association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action_Owner_Association',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Action_Owner_Association_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name='fk_Action_Owner_Association_action_id_Action', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_Action_Owner_Association_user_id_User', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_Action_Owner_Association')
    )
    op.create_index('ix_Action_Owner_Association_id', 'Action_Owner_Association', ['id'], unique=False)
    # ### end Alembic commands ###
