"""Changes to actions

Revision ID: 4760369ceb4c
Revises: 86c4a8ee8297
Create Date: 2022-07-06 05:21:31.291837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4760369ceb4c'
down_revision = '86c4a8ee8297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('last_updated_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action', sa.Column('last_updated_by', sa.String(), nullable=True))
    op.alter_column('Action', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Action', 'created_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('Action', 'last_updated_by')
    op.drop_column('Action', 'last_updated_date')
    # ### end Alembic commands ###
