"""user schema workcenters array

Revision ID: e227e097e6c4
Revises: f24b4a8c9df6
Create Date: 2022-11-18 03:35:22.870491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e227e097e6c4'
down_revision = 'f24b4a8c9df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('work_centers', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'work_centers')
    # ### end Alembic commands ###
