"""added all db's again, removed ID constraint

Revision ID: df9cd1081266
Revises: 5d21ea7cdc00
Create Date: 2022-05-09 06:04:34.429322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9cd1081266'
down_revision = '5d21ea7cdc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ahm_Equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('asset_number', sa.String(), nullable=True),
    sa.Column('floc_object_number', sa.String(), nullable=True),
    sa.Column('floc_name', sa.String(), nullable=True),
    sa.Column('equipment_number', sa.String(), nullable=True),
    sa.Column('equipment_description', sa.String(), nullable=True),
    sa.Column('object_type_text', sa.String(), nullable=True),
    sa.Column('asset_health_id', sa.String(), nullable=True),
    sa.Column('asset_condition', sa.String(), nullable=True),
    sa.Column('failure_mode', sa.String(), nullable=True),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('notification_number', sa.String(), nullable=True),
    sa.Column('work_order_number', sa.String(), nullable=True),
    sa.Column('uinno', sa.String(), nullable=True),
    sa.Column('is_not_monitor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ahm_Equipment_id'), 'Ahm_Equipment', ['id'], unique=False)
    op.create_table('Ahm_Simp_Defect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simp_defect_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('notification_number', sa.String(), nullable=True),
    sa.Column('work_order_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('assembly', sa.String(), nullable=True),
    sa.Column('floc_name', sa.String(), nullable=True),
    sa.Column('equipment_number', sa.String(), nullable=True),
    sa.Column('priority_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ahm_Simp_Defect_id'), 'Ahm_Simp_Defect', ['id'], unique=False)
    op.create_table('Ahm_TxOilSample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_oil_sample_id', sa.Integer(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('condition_code', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('date_reported', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ahm_TxOilSample_id'), 'Ahm_TxOilSample', ['id'], unique=False)
    op.create_table('Equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Equipment_id'), 'Equipment', ['id'], unique=False)
    op.create_table('Favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sap_order_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Favorites_id'), 'Favorites', ['id'], unique=False)
    op.create_table('Sap_floc_historical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('functional_location_label', sa.String(), nullable=True),
    sa.Column('functional_location_description', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_description', sa.String(), nullable=True),
    sa.Column('system_status', sa.String(), nullable=True),
    sa.Column('user_status', sa.String(), nullable=True),
    sa.Column('maintenance_plant', sa.Integer(), nullable=True),
    sa.Column('maintenance_plant_description', sa.String(), nullable=True),
    sa.Column('notification_number', sa.String(), nullable=True),
    sa.Column('maintenance_activity_type_description', sa.String(), nullable=True),
    sa.Column('basic_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basic_finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_text', sa.String(), nullable=True),
    sa.Column('maintenance_processing_phase', sa.String(), nullable=True),
    sa.Column('date_changed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sap_floc_historical_id'), 'Sap_floc_historical', ['id'], unique=False)
    op.create_table('Sap_floc_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('functional_location_label', sa.String(), nullable=True),
    sa.Column('functional_location_description', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_description', sa.String(), nullable=True),
    sa.Column('system_status', sa.String(), nullable=True),
    sa.Column('user_status', sa.String(), nullable=True),
    sa.Column('maintenance_plant', sa.Integer(), nullable=True),
    sa.Column('maintenance_plant_description', sa.String(), nullable=True),
    sa.Column('notification_number', sa.String(), nullable=True),
    sa.Column('maintenance_activity_type_description', sa.String(), nullable=True),
    sa.Column('basic_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basic_finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_text', sa.String(), nullable=True),
    sa.Column('maintenance_processing_phase', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sap_floc_orders_id'), 'Sap_floc_orders', ['id'], unique=False)
    op.create_table('Shutdown_management_hub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emailid', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'dbid')
    )
    op.create_index(op.f('ix_Shutdown_management_hub_id'), 'Shutdown_management_hub', ['id'], unique=False)
    op.add_column('User', sa.Column('functional_loc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'functional_loc')
    op.drop_index(op.f('ix_Shutdown_management_hub_id'), table_name='Shutdown_management_hub')
    op.drop_table('Shutdown_management_hub')
    op.drop_index(op.f('ix_Sap_floc_orders_id'), table_name='Sap_floc_orders')
    op.drop_table('Sap_floc_orders')
    op.drop_index(op.f('ix_Sap_floc_historical_id'), table_name='Sap_floc_historical')
    op.drop_table('Sap_floc_historical')
    op.drop_index(op.f('ix_Favorites_id'), table_name='Favorites')
    op.drop_table('Favorites')
    op.drop_index(op.f('ix_Equipment_id'), table_name='Equipment')
    op.drop_table('Equipment')
    op.drop_index(op.f('ix_Ahm_TxOilSample_id'), table_name='Ahm_TxOilSample')
    op.drop_table('Ahm_TxOilSample')
    op.drop_index(op.f('ix_Ahm_Simp_Defect_id'), table_name='Ahm_Simp_Defect')
    op.drop_table('Ahm_Simp_Defect')
    op.drop_index(op.f('ix_Ahm_Equipment_id'), table_name='Ahm_Equipment')
    op.drop_table('Ahm_Equipment')
    # ### end Alembic commands ###
