"""Adding BMS users db

Revision ID: 44a39d248ff0
Revises: 5eea6d2ff00f
Create Date: 2022-05-10 07:22:26.301179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a39d248ff0'
down_revision = '5eea6d2ff00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bms_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sap_id_number', sa.Integer(), nullable=True),
    sa.Column('supervisor_sap_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bms_Users_id'), 'Bms_Users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bms_Users_id'), table_name='Bms_Users')
    op.drop_table('Bms_Users')
    # ### end Alembic commands ###
