"""Actions Table update 2

Revision ID: 5ec0b067a4e0
Revises: 6ec345f2173e
Create Date: 2022-05-30 08:49:21.107331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec0b067a4e0'
down_revision = '6ec345f2173e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('floc', sa.String(), nullable=True))
    op.add_column('Action', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action', sa.Column('supervisor', sa.Integer(), nullable=True))
    op.add_column('Action', sa.Column('completion', sa.Integer(), nullable=True))
    op.add_column('Action', sa.Column('action_status', sa.String(), nullable=True))
    op.add_column('Action', sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action', sa.Column('linked_system', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'linked_system')
    op.drop_column('Action', 'date_closed')
    op.drop_column('Action', 'action_status')
    op.drop_column('Action', 'completion')
    op.drop_column('Action', 'supervisor')
    op.drop_column('Action', 'start_date')
    op.drop_column('Action', 'floc')
    # ### end Alembic commands ###
