"""schemas.Action is_archived

Revision ID: 492df022315b
Revises: f2856900d63c
Create Date: 2022-10-10 00:21:37.626503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492df022315b'
down_revision = 'f2856900d63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'is_archived')
    # ### end Alembic commands ###
