"""admin users in workgroups

Revision ID: 03b177e4ae8c
Revises: b0af7ddd1592
Create Date: 2022-06-08 13:47:33.630831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b177e4ae8c'
down_revision = 'b0af7ddd1592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workgroup_Admin_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workgroup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workgroup_id'], ['Workgroup.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Workgroup_Admin_Association_id'), 'Workgroup_Admin_Association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Workgroup_Admin_Association_id'), table_name='Workgroup_Admin_Association')
    op.drop_table('Workgroup_Admin_Association')
    # ### end Alembic commands ###
