"""remove priority col

Revision ID: 72fd1c756f26
Revises: 470e1842c8fd
Create Date: 2022-11-20 11:39:50.736302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fd1c756f26'
down_revision = '470e1842c8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
