"""Action Privacy

Revision ID: 3a9165c7a85b
Revises: 749ab629fec8
Create Date: 2022-09-01 03:15:53.185058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9165c7a85b'
down_revision = '749ab629fec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'is_private')
    # ### end Alembic commands ###
