"""Add link relationships

Revision ID: c240e56991dc
Revises: 2e50f4c58910
Create Date: 2022-10-25 07:55:46.243831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c240e56991dc'
down_revision = '2e50f4c58910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Action_Member_Association_user_id_User', 'Action_Member_Association', type_='foreignkey')
    op.drop_constraint('fk_Action_Member_Association_action_id_Action', 'Action_Member_Association', type_='foreignkey')
    op.drop_column('Action_Member_Association', 'action_id')
    op.drop_column('Action_Member_Association', 'user_id')
    op.drop_constraint('fk_Comment_action_id_Action', 'Comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Comment_action_id_Action2'), 'Comment', 'Action2', ['action_id'], ['id'])
    op.drop_constraint('fk_General_Attachment_action_id_Action', 'General_Attachment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_General_Attachment_action_id_Action2'), 'General_Attachment', 'Action2', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_General_Attachment_action_id_Action2'), 'General_Attachment', type_='foreignkey')
    op.create_foreign_key('fk_General_Attachment_action_id_Action', 'General_Attachment', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_Comment_action_id_Action2'), 'Comment', type_='foreignkey')
    op.create_foreign_key('fk_Comment_action_id_Action', 'Comment', 'Action', ['action_id'], ['id'])
    op.add_column('Action_Member_Association', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Action_Member_Association', sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_Action_Member_Association_action_id_Action', 'Action_Member_Association', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_Action_Member_Association_user_id_User', 'Action_Member_Association', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
