"""Workgroup updatedBy

Revision ID: e765fef2229c
Revises: 2ead0bc70a18
Create Date: 2022-09-05 02:59:20.980681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e765fef2229c'
down_revision = '2ead0bc70a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'updated_by')
    # ### end Alembic commands ###
