"""BMS Changes to update

Revision ID: 33c89b766565
Revises: e3e27b45ffc4
Create Date: 2022-08-07 12:12:13.088626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33c89b766565'
down_revision = 'e3e27b45ffc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bms_Actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bms_action_id', sa.String(), nullable=True),
    sa.Column('date_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('detailed_description', sa.String(), nullable=True),
    sa.Column('date_raised', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_email', sa.String(), nullable=True),
    sa.Column('incident_title', sa.String(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=True),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bms_Actions_id'), 'Bms_Actions', ['id'], unique=False)
    op.drop_index('ix_Bms_Users_id', table_name='Bms_Users')
    op.drop_table('Bms_Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bms_Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Bms_Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('sap_id_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supervisor_sap_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Bms_Users_pkey')
    )
    op.create_index('ix_Bms_Users_id', 'Bms_Users', ['id'], unique=False)
    op.drop_index(op.f('ix_Bms_Actions_id'), table_name='Bms_Actions')
    op.drop_table('Bms_Actions')
    # ### end Alembic commands ###
