"""Changes to Workgroup

Revision ID: d3e353e10eeb
Revises: 76627138fa33
Create Date: 2022-06-27 03:32:04.596096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e353e10eeb'
down_revision = '76627138fa33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('functional_location', sa.String(), nullable=True))
    op.add_column('Workgroup', sa.Column('closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'closed')
    op.drop_column('Workgroup', 'functional_location')
    # ### end Alembic commands ###
