"""action 2 - floc

Revision ID: 949f85989ddf
Revises: d06c95e210b0
Create Date: 2022-10-21 08:58:01.536005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949f85989ddf'
down_revision = 'd06c95e210b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action2', sa.Column('functional_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action2', 'functional_location')
    # ### end Alembic commands ###
