"""workgroup schemas first pass

Revision ID: 28cdeac9bb76
Revises: 8176b6268dd0
Create Date: 2022-06-07 01:45:52.042211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cdeac9bb76'
down_revision = '8176b6268dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Workgroup_id'), 'Workgroup', ['id'], unique=False)
    op.create_table('Workgroup_Owner_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workgroup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workgroup_id'], ['Workgroup.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Workgroup_Owner_Association_id'), 'Workgroup_Owner_Association', ['id'], unique=False)
    op.create_table('Workgroup_Action_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workfroup_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workfroup_id'], ['Workgroup.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Workgroup_Action_Association_id'), 'Workgroup_Action_Association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Workgroup_Action_Association_id'), table_name='Workgroup_Action_Association')
    op.drop_table('Workgroup_Action_Association')
    op.drop_index(op.f('ix_Workgroup_Owner_Association_id'), table_name='Workgroup_Owner_Association')
    op.drop_table('Workgroup_Owner_Association')
    op.drop_index(op.f('ix_Workgroup_id'), table_name='Workgroup')
    op.drop_table('Workgroup')
    # ### end Alembic commands ###
