"""Revised Attachment with UUID

Revision ID: 66e46da061d6
Revises: 5b0946f7e7e3
Create Date: 2022-07-21 04:14:34.678688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e46da061d6'
down_revision = '5b0946f7e7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachment', sa.Column('unique_filename', sa.String(), nullable=True))
    op.drop_column('Attachment', 'upload_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachment', sa.Column('upload_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Attachment', 'unique_filename')
    # ### end Alembic commands ###
