"""BMS Employee Field

Revision ID: 0ec4b8189340
Revises: 45a4276a7617
Create Date: 2022-08-15 08:22:48.946712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec4b8189340'
down_revision = '45a4276a7617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bms_Actions', sa.Column('employee_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bms_Actions', 'employee_name')
    # ### end Alembic commands ###
