"""add privacy to actions

Revision ID: 2de4140d5792
Revises: f8d097bc820e
Create Date: 2022-10-14 06:54:55.140861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de4140d5792'
down_revision = 'f8d097bc820e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('privacy', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'privacy')
    # ### end Alembic commands ###
