"""Sap Work Order changes

Revision ID: 8f07e19a1ff5
Revises: f976092391d4
Create Date: 2022-07-04 03:23:23.190361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f07e19a1ff5'
down_revision = 'f976092391d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sap_workorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('functional_location_label', sa.String(), nullable=True),
    sa.Column('functional_location_description', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_description', sa.String(), nullable=True),
    sa.Column('system_status', sa.String(), nullable=True),
    sa.Column('user_status', sa.String(), nullable=True),
    sa.Column('main_work_center', sa.String(), nullable=True),
    sa.Column('notification_number', sa.String(), nullable=True),
    sa.Column('basic_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basic_finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_text', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sap_workorders_id'), 'Sap_workorders', ['id'], unique=False)
    op.drop_index('ix_Sap_floc_orders_id', table_name='Sap_floc_orders')
    op.drop_table('Sap_floc_orders')
    op.add_column('Sap_floc_historical', sa.Column('main_work_center', sa.String(), nullable=True))
    op.add_column('Sap_floc_historical', sa.Column('group', sa.String(), nullable=True))
    op.drop_column('Sap_floc_historical', 'reference_date')
    op.drop_column('Sap_floc_historical', 'maintenance_processing_phase')
    op.drop_column('Sap_floc_historical', 'maintenance_plant')
    op.drop_column('Sap_floc_historical', 'maintenance_plant_description')
    op.drop_column('Sap_floc_historical', 'maintenance_activity_type_description')
    op.drop_column('Sap_floc_historical', 'actual_start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sap_floc_historical', sa.Column('actual_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Sap_floc_historical', sa.Column('maintenance_activity_type_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Sap_floc_historical', sa.Column('maintenance_plant_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Sap_floc_historical', sa.Column('maintenance_plant', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Sap_floc_historical', sa.Column('maintenance_processing_phase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Sap_floc_historical', sa.Column('reference_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Sap_floc_historical', 'group')
    op.drop_column('Sap_floc_historical', 'main_work_center')
    op.create_table('Sap_floc_orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sap_floc_orders_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maintenance_plant', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maintenance_plant_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maintenance_activity_type_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('basic_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('actual_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('basic_finish_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reference_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maintenance_processing_phase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Sap_floc_orders_pkey')
    )
    op.create_index('ix_Sap_floc_orders_id', 'Sap_floc_orders', ['id'], unique=False)
    op.drop_index(op.f('ix_Sap_workorders_id'), table_name='Sap_workorders')
    op.drop_table('Sap_workorders')
    # ### end Alembic commands ###
