"""rem asset

Revision ID: d8245e4c0826
Revises: 2dd5afe9c9c4
Create Date: 2022-11-07 05:01:10.396552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8245e4c0826'
down_revision = '2dd5afe9c9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('asset', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
