"""AHM Legacy Removal

Revision ID: 24d8884c0ba4
Revises: d8245e4c0826
Create Date: 2022-11-07 07:12:56.345992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24d8884c0ba4'
down_revision = 'd8245e4c0826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Ahm_Equipment_id', table_name='Ahm_Equipment')
    op.drop_table('Ahm_Equipment')
    op.drop_index('ix_Ahm_AlsSampleData_id', table_name='Ahm_AlsSampleData')
    op.drop_table('Ahm_AlsSampleData')
    op.drop_index('ix_Ahm_TxOilSample_id', table_name='Ahm_TxOilSample')
    op.drop_table('Ahm_TxOilSample')
    op.drop_index('ix_Ahm_Simp_Defect_id', table_name='Ahm_Simp_Defect')
    op.drop_table('Ahm_Simp_Defect')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ahm_Simp_Defect',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Ahm_Simp_Defect_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('simp_defect_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assembly', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floc_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('equipment_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Ahm_Simp_Defect')
    )
    op.create_index('ix_Ahm_Simp_Defect_id', 'Ahm_Simp_Defect', ['id'], unique=False)
    op.create_table('Ahm_TxOilSample',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Ahm_TxOilSample_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tx_oil_sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('condition_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_reported', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('site_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('area_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tag_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Ahm_TxOilSample')
    )
    op.create_index('ix_Ahm_TxOilSample_id', 'Ahm_TxOilSample', ['id'], unique=False)
    op.create_table('Ahm_AlsSampleData',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Ahm_AlsSampleData_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('sif_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('compartment_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('compartment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floc_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('problem_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Ahm_AlsSampleData')
    )
    op.create_index('ix_Ahm_AlsSampleData_id', 'Ahm_AlsSampleData', ['id'], unique=False)
    op.create_table('Ahm_Equipment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Ahm_Equipment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysis_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floc_object_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floc_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('equipment_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('equipment_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object_type_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_health_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('failure_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technology', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uinno', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_not_monitor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Ahm_Equipment')
    )
    op.create_index('ix_Ahm_Equipment_id', 'Ahm_Equipment', ['id'], unique=False)
    # ### end Alembic commands ###
