"""User schemas tweak

Revision ID: 3e42c6250c7d
Revises: 0abc370d106b
Create Date: 2022-06-09 01:40:18.940068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e42c6250c7d'
down_revision = '0abc370d106b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('job_title', sa.String(), nullable=True))
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('User_email_key', 'User', type_='unique')
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_microsoft_id'), 'User', ['microsoft_id'], unique=True)
    op.drop_column('User', 'first_name')
    op.drop_column('User', 'last_name')
    op.drop_column('User', 'sap_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('sap_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_User_microsoft_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.create_unique_constraint('User_email_key', 'User', ['email'])
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('User', 'job_title')
    op.drop_column('User', 'fullname')
    # ### end Alembic commands ###
