"""workgroup initial schema

Revision ID: ee00ae9e8438
Revises: d2220c91c77b
Create Date: 2022-10-11 00:48:47.593124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee00ae9e8438'
down_revision = 'd2220c91c77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archive_user_id', sa.Integer(), nullable=True),
    sa.Column('archive_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_ids', sa.JSON(), nullable=True),
    sa.Column('admin_ids', sa.JSON(), nullable=True),
    sa.Column('functional_location', sa.String(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('action_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Workgroup'))
    )
    op.create_index(op.f('ix_Workgroup_id'), 'Workgroup', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Workgroup_id'), table_name='Workgroup')
    op.drop_table('Workgroup')
    # ### end Alembic commands ###
