"""REMOVE workgroup id to actions schema fk

Revision ID: b0af7ddd1592
Revises: ea158666b2d2
Create Date: 2022-06-07 08:06:17.618458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0af7ddd1592'
down_revision = 'ea158666b2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'workgroup_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('workgroup_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
