"""ingested user schema

Revision ID: 48e5953d5c10
Revises: 03b177e4ae8c
Create Date: 2022-06-08 23:30:20.111483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e5953d5c10'
down_revision = '03b177e4ae8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IngestedUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('sap_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IngestedUser_email'), 'IngestedUser', ['email'], unique=True)
    op.create_index(op.f('ix_IngestedUser_id'), 'IngestedUser', ['id'], unique=False)
    op.create_index(op.f('ix_IngestedUser_sap_number'), 'IngestedUser', ['sap_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_IngestedUser_sap_number'), table_name='IngestedUser')
    op.drop_index(op.f('ix_IngestedUser_id'), table_name='IngestedUser')
    op.drop_index(op.f('ix_IngestedUser_email'), table_name='IngestedUser')
    op.drop_table('IngestedUser')
    # ### end Alembic commands ###
