"""ace action add values

Revision ID: e60540afc118
Revises: a542a8f2fe75
Create Date: 2022-10-24 01:34:06.601182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60540afc118'
down_revision = 'a542a8f2fe75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action2', sa.Column('archive_user_id', sa.Integer(), nullable=True))
    op.add_column('Action2', sa.Column('archive_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action2', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action2', 'is_archived')
    op.drop_column('Action2', 'archive_datetime')
    op.drop_column('Action2', 'archive_user_id')
    # ### end Alembic commands ###
