"""Fmg Legacy Removal

Revision ID: 7dad9c0a6ae9
Revises: 29a8e15d35e0
Create Date: 2022-11-07 07:22:53.170053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dad9c0a6ae9'
down_revision = '29a8e15d35e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Fmg_Employees_id', table_name='Fmg_Employees')
    op.drop_table('Fmg_Employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fmg_Employees',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sap_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_employee_supervisor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'sap_number', name='pk_Fmg_Employees'),
    sa.UniqueConstraint('email', name='Fmg_Employees_email_key')
    )
    op.create_index('ix_Fmg_Employees_id', 'Fmg_Employees', ['id'], unique=False)
    # ### end Alembic commands ###
