"""FMG Employees Field

Revision ID: 4a23e2ab0c6e
Revises: 0ec4b8189340
Create Date: 2022-08-17 03:26:50.623346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a23e2ab0c6e'
down_revision = '0ec4b8189340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Fmg_Employees_id'), 'Fmg_Employees', ['id'], unique=False)
    op.drop_column('Fmg_Employees', 'key_vendor_employer')
    op.drop_column('Fmg_Employees', 'employment_basis')
    op.drop_column('Fmg_Employees', 'role')
    op.drop_column('Fmg_Employees', 'key_org_unit')
    op.drop_column('Fmg_Employees', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Fmg_Employees', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Fmg_Employees', sa.Column('key_org_unit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Fmg_Employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Fmg_Employees', sa.Column('employment_basis', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Fmg_Employees', sa.Column('key_vendor_employer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Fmg_Employees_id'), table_name='Fmg_Employees')
    # ### end Alembic commands ###
