"""Add members association

Revision ID: 8aeb52fe9130
Revises: c240e56991dc
Create Date: 2022-10-25 07:56:13.306269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aeb52fe9130'
down_revision = 'c240e56991dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action_Member_Association', sa.Column('action_id', sa.Integer(), nullable=True))
    op.add_column('Action_Member_Association', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Action_Member_Association_action_id_Action2'), 'Action_Member_Association', 'Action2', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Action_Member_Association_user_id_User'), 'Action_Member_Association', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Action_Member_Association_user_id_User'), 'Action_Member_Association', type_='foreignkey')
    op.drop_constraint(op.f('fk_Action_Member_Association_action_id_Action2'), 'Action_Member_Association', type_='foreignkey')
    op.drop_column('Action_Member_Association', 'user_id')
    op.drop_column('Action_Member_Association', 'action_id')
    # ### end Alembic commands ###
