"""action 2

Revision ID: 510e96e991b9
Revises: 2de4140d5792
Create Date: 2022-10-21 05:41:16.515187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '510e96e991b9'
down_revision = '2de4140d5792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name=op.f('fk_Action2_created_by_id_User')),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], name=op.f('fk_Action2_owner_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action2'))
    )
    op.create_index(op.f('ix_Action2_id'), 'Action2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Action2_id'), table_name='Action2')
    op.drop_table('Action2')
    # ### end Alembic commands ###
