"""New Floc and Equipment

Revision ID: 04a5f4130377
Revises: ecac7d1098c9
Create Date: 2022-06-22 00:24:20.146972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a5f4130377'
down_revision = 'ecac7d1098c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Equipment', sa.Column('catalog_profile', sa.String(), nullable=True))
    op.add_column('Equipment', sa.Column('equipment_description', sa.String(), nullable=True))
    op.add_column('Equipment', sa.Column('object_type', sa.String(), nullable=True))
    op.drop_column('Equipment', 'type')
    op.drop_column('Equipment', 'description')
    op.drop_column('Equipment', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Equipment', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Equipment', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Equipment', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Equipment', 'object_type')
    op.drop_column('Equipment', 'equipment_description')
    op.drop_column('Equipment', 'catalog_profile')
    # ### end Alembic commands ###
