"""feedback comments

Revision ID: 531cd01c2aa5
Revises: 08dc0aac3ee8
Create Date: 2022-11-25 05:58:37.131840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531cd01c2aa5'
down_revision = '08dc0aac3ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('feedback_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Comment_feedback_id_Feedback'), 'Comment', 'Feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Comment_feedback_id_Feedback'), 'Comment', type_='foreignkey')
    op.drop_column('Comment', 'feedback_id')
    # ### end Alembic commands ###
