"""attachment update and install

Revision ID: 121d8741243d
Revises: 4760369ceb4c
Create Date: 2022-07-08 05:44:11.909639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121d8741243d'
down_revision = '4760369ceb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachment', sa.Column('upload_date', sa.String(), nullable=True))
    op.add_column('Attachment', sa.Column('uploaded_by', sa.String(), nullable=True))
    op.add_column('Attachment', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('Attachment', sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Attachment', sa.Column('deleted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Attachment', 'deleted_by')
    op.drop_column('Attachment', 'deleted_date')
    op.drop_column('Attachment', 'deleted')
    op.drop_column('Attachment', 'uploaded_by')
    op.drop_column('Attachment', 'upload_date')
    # ### end Alembic commands ###
