"""add workcenter to schemas.Action

Revision ID: 86577ccba553
Revises: b4f7091aefa4
Create Date: 2022-11-14 03:44:58.501562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86577ccba553'
down_revision = 'b4f7091aefa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('work_center', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'work_center')
    # ### end Alembic commands ###
