"""B2B id -> Email

Revision ID: ecac7d1098c9
Revises: 846c624214e7
Create Date: 2022-06-21 06:15:33.051284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecac7d1098c9'
down_revision = '846c624214e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('back_to_back_email', sa.String(), nullable=True))
    op.drop_column('User', 'back_to_back_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('back_to_back_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'back_to_back_email')
    # ### end Alembic commands ###
