"""workgroup schema v2

Revision ID: e031de9085a3
Revises: ee00ae9e8438
Create Date: 2022-10-11 01:32:45.604870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e031de9085a3'
down_revision = 'ee00ae9e8438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workgroup_Action_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workgroup_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Workgroup_Action_Association_action_id_Action'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workgroup_id'], ['Workgroup.id'], name=op.f('fk_Workgroup_Action_Association_workgroup_id_Workgroup'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Workgroup_Action_Association'))
    )
    op.create_index(op.f('ix_Workgroup_Action_Association_id'), 'Workgroup_Action_Association', ['id'], unique=False)
    op.drop_column('Workgroup', 'action_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('action_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Workgroup_Action_Association_id'), table_name='Workgroup_Action_Association')
    op.drop_table('Workgroup_Action_Association')
    # ### end Alembic commands ###
