"""BMS Legacy Removal

Revision ID: 88d635b277d8
Revises: 24d8884c0ba4
Create Date: 2022-11-07 07:16:20.969404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d635b277d8'
down_revision = '24d8884c0ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Bms_Actions_id', table_name='Bms_Actions')
    op.drop_table('Bms_Actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bms_Actions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Bms_Actions_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bms_action_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detailed_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_raised', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('employee_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incident_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('criticality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discipline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incident_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_Bms_Actions')
    )
    op.create_index('ix_Bms_Actions_id', 'Bms_Actions', ['id'], unique=False)
    # ### end Alembic commands ###
