"""feedback remove old schema

Revision ID: 08dde57cce17
Revises: 531cd01c2aa5
Create Date: 2022-11-25 06:04:12.817547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08dde57cce17'
down_revision = '531cd01c2aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Feedback_Comment_id', table_name='Feedback_Comment')
    op.drop_table('Feedback_Comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback_Comment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Feedback_Comment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['Feedback.id'], name='fk_Feedback_Comment_feedback_id_Feedback'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_Feedback_Comment_user_id_User'),
    sa.PrimaryKeyConstraint('id', name='pk_Feedback_Comment')
    )
    op.create_index('ix_Feedback_Comment_id', 'Feedback_Comment', ['id'], unique=False)
    # ### end Alembic commands ###
