"""association table logic for arrays

Revision ID: 60726b66cb32
Revises: aecb2ff3aa8d
Create Date: 2022-10-13 14:55:42.657876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60726b66cb32'
down_revision = 'aecb2ff3aa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workgroup_Admin_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workgroup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Workgroup_Admin_Association_user_id_User'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workgroup_id'], ['Workgroup.id'], name=op.f('fk_Workgroup_Admin_Association_workgroup_id_Workgroup'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Workgroup_Admin_Association'))
    )
    op.create_index(op.f('ix_Workgroup_Admin_Association_id'), 'Workgroup_Admin_Association', ['id'], unique=False)
    op.create_table('Workgroup_Member_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workgroup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Workgroup_Member_Association_user_id_User'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workgroup_id'], ['Workgroup.id'], name=op.f('fk_Workgroup_Member_Association_workgroup_id_Workgroup'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Workgroup_Member_Association'))
    )
    op.create_index(op.f('ix_Workgroup_Member_Association_id'), 'Workgroup_Member_Association', ['id'], unique=False)
    op.drop_column('Workgroup', 'admin_ids')
    op.drop_column('Workgroup', 'member_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('member_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('Workgroup', sa.Column('admin_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Workgroup_Member_Association_id'), table_name='Workgroup_Member_Association')
    op.drop_table('Workgroup_Member_Association')
    op.drop_index(op.f('ix_Workgroup_Admin_Association_id'), table_name='Workgroup_Admin_Association')
    op.drop_table('Workgroup_Admin_Association')
    # ### end Alembic commands ###
