"""Base Created/Updated Fields

Revision ID: 5b0946f7e7e3
Revises: 121d8741243d
Create Date: 2022-07-21 03:39:04.298861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b0946f7e7e3"
down_revision = "121d8741243d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "General_Attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("action_id", sa.Integer(), nullable=True),
        sa.Column("unique_filename", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["action_id"], ["Action.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deleted_by"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_General_Attachment_id"), "General_Attachment", ["id"], unique=False)
    op.add_column("Action", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Action", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "Action_Comments", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Action_Comments", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Action_Owner_Association", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Action_Owner_Association", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Ahm_AlsSampleData", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Ahm_AlsSampleData", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("Ahm_Equipment", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Ahm_Equipment", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "Ahm_Simp_Defect", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Ahm_Simp_Defect", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Ahm_TxOilSample", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Ahm_TxOilSample", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("Attachment", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Attachment", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Bms_Users", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Bms_Users", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Equipment", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Equipment", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Favorites", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Favorites", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Fmg_Employees", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Fmg_Employees", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "Sap_Notifications", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Sap_Notifications", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Sap_floc_historical", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Sap_floc_historical", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Sap_work_centres", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Sap_work_centres", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("Sap_workorders", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Sap_workorders", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "Shutdown_management_hub", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Shutdown_management_hub", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("Table_Headers", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Table_Headers", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column("User", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("User", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Workgroup", sa.Column("created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Workgroup", sa.Column("updated", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "Workgroup_Action_Association",
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "Workgroup_Action_Association",
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "Workgroup_Admin_Association",
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "Workgroup_Admin_Association",
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "Workgroup_Owner_Association",
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "Workgroup_Owner_Association",
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Workgroup_Owner_Association", "updated")
    op.drop_column("Workgroup_Owner_Association", "created")
    op.drop_column("Workgroup_Admin_Association", "updated")
    op.drop_column("Workgroup_Admin_Association", "created")
    op.drop_column("Workgroup_Action_Association", "updated")
    op.drop_column("Workgroup_Action_Association", "created")
    op.drop_column("Workgroup", "updated")
    op.drop_column("Workgroup", "created")
    op.drop_column("User", "updated")
    op.drop_column("User", "created")
    op.drop_column("Table_Headers", "updated")
    op.drop_column("Table_Headers", "created")
    op.drop_column("Shutdown_management_hub", "updated")
    op.drop_column("Shutdown_management_hub", "created")
    op.drop_column("Sap_workorders", "updated")
    op.drop_column("Sap_workorders", "created")
    op.drop_column("Sap_work_centres", "updated")
    op.drop_column("Sap_work_centres", "created")
    op.drop_column("Sap_floc_historical", "updated")
    op.drop_column("Sap_floc_historical", "created")
    op.drop_column("Sap_Notifications", "updated")
    op.drop_column("Sap_Notifications", "created")
    op.drop_column("Fmg_Employees", "updated")
    op.drop_column("Fmg_Employees", "created")
    op.drop_column("Favorites", "updated")
    op.drop_column("Favorites", "created")
    op.drop_column("Equipment", "updated")
    op.drop_column("Equipment", "created")
    op.drop_column("Bms_Users", "updated")
    op.drop_column("Bms_Users", "created")
    op.drop_column("Attachment", "updated")
    op.drop_column("Attachment", "created")
    op.drop_column("Ahm_TxOilSample", "updated")
    op.drop_column("Ahm_TxOilSample", "created")
    op.drop_column("Ahm_Simp_Defect", "updated")
    op.drop_column("Ahm_Simp_Defect", "created")
    op.drop_column("Ahm_Equipment", "updated")
    op.drop_column("Ahm_Equipment", "created")
    op.drop_column("Ahm_AlsSampleData", "updated")
    op.drop_column("Ahm_AlsSampleData", "created")
    op.drop_column("Action_Owner_Association", "updated")
    op.drop_column("Action_Owner_Association", "created")
    op.drop_column("Action_Comments", "updated")
    op.drop_column("Action_Comments", "created")
    op.drop_column("Action", "updated")
    op.drop_column("Action", "created")
    op.drop_index(op.f("ix_General_Attachment_id"), table_name="General_Attachment")
    op.drop_table("General_Attachment")
    # ### end Alembic commands ###
