"""workgroup attachments

Revision ID: 2f222666e472
Revises: 3c3702645bf7
Create Date: 2022-11-28 02:29:42.732679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f222666e472'
down_revision = '3c3702645bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('workgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_General_Attachment_workgroup_id_Workgroup'), 'General_Attachment', 'Workgroup', ['workgroup_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_General_Attachment_workgroup_id_Workgroup'), 'General_Attachment', type_='foreignkey')
    op.drop_column('General_Attachment', 'workgroup_id')
    # ### end Alembic commands ###
