"""privacy has default field

Revision ID: 88fad412155d
Revises: ef89d332a597
Create Date: 2022-10-13 12:48:02.762759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fad412155d'
down_revision = 'ef89d332a597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Workgroup', 'privacy',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Workgroup', 'privacy',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
