"""workgroup id to actions schema fk

Revision ID: ea158666b2d2
Revises: e86526fa47f2
Create Date: 2022-06-07 07:59:26.815793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea158666b2d2'
down_revision = 'e86526fa47f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('workgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Action', 'Workgroup', ['workgroup_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Action', type_='foreignkey')
    op.drop_column('Action', 'workgroup_id')
    # ### end Alembic commands ###
