"""PRIVATE -> CONFIDENTIAL

Revision ID: 22dad5b2679c
Revises: 93d060ddd03d
Create Date: 2022-09-29 07:41:30.546100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dad5b2679c'
down_revision = '93d060ddd03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_confidential', sa.Boolean(), nullable=True))
    op.drop_column('Action', 'is_private')
    op.add_column('Workgroup', sa.Column('is_confidential', sa.Boolean(), nullable=True))
    op.drop_column('Workgroup', 'is_private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Workgroup', 'is_confidential')
    op.add_column('Action', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Action', 'is_confidential')
    # ### end Alembic commands ###
