"""workgroup comments

Revision ID: 3c3702645bf7
Revises: 08dde57cce17
Create Date: 2022-11-28 01:34:49.465935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3702645bf7'
down_revision = '08dde57cce17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('workgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Comment_workgroup_id_Workgroup'), 'Comment', 'Workgroup', ['workgroup_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Comment_workgroup_id_Workgroup'), 'Comment', type_='foreignkey')
    op.drop_column('Comment', 'workgroup_id')
    # ### end Alembic commands ###
