"""source created and updated cols added to action achema

Revision ID: f145c7991c8a
Revises: c7f96f502401
Create Date: 2022-11-01 00:54:27.783172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f145c7991c8a'
down_revision = 'c7f96f502401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('source_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Action', sa.Column('source_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'source_updated')
    op.drop_column('Action', 'source_created')
    # ### end Alembic commands ###
