"""schemas.Action archived details added

Revision ID: a68590c11404
Revises: 492df022315b
Create Date: 2022-10-10 00:41:29.821039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68590c11404'
down_revision = '492df022315b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('archive_user_id', sa.Integer(), nullable=True))
    op.add_column('Action', sa.Column('archive_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'archive_datetime')
    op.drop_column('Action', 'archive_user_id')
    # ### end Alembic commands ###
