"""Date Closed added to the database

Revision ID: 0b2692823b29
Revises: d3e353e10eeb
Create Date: 2022-06-27 07:07:59.959565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2692823b29'
down_revision = 'd3e353e10eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'date_closed')
    # ### end Alembic commands ###
