"""workgroup schemas misspelt col

Revision ID: e86526fa47f2
Revises: 28cdeac9bb76
Create Date: 2022-06-07 02:37:35.792993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86526fa47f2'
down_revision = '28cdeac9bb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup_Action_Association', sa.Column('workgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Workgroup_Action_Association', 'Workgroup', ['workgroup_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Workgroup_Action_Association', 'workfroup_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup_Action_Association', sa.Column('workfroup_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Workgroup_Action_Association', type_='foreignkey')
    op.drop_column('Workgroup_Action_Association', 'workgroup_id')
    # ### end Alembic commands ###
