"""Bms Id field

Revision ID: a7c668699134
Revises: 33c89b766565
Create Date: 2022-08-11 02:17:56.722833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c668699134'
down_revision = '33c89b766565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bms_Actions', sa.Column('incident_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bms_Actions', 'incident_id')
    # ### end Alembic commands ###
