"""Sap Work Notifications

Revision ID: f976092391d4
Revises: f5cdf52d60e2
Create Date: 2022-07-01 02:37:13.373474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f976092391d4'
down_revision = 'f5cdf52d60e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sap_Notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_number', sa.String(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('notification_description', sa.String(), nullable=True),
    sa.Column('system_status', sa.String(), nullable=True),
    sa.Column('user_status', sa.String(), nullable=True),
    sa.Column('main_work_centre', sa.String(), nullable=True),
    sa.Column('required_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('functional_location_label', sa.String(), nullable=True),
    sa.Column('functional_location_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sap_Notifications_id'), 'Sap_Notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sap_Notifications_id'), table_name='Sap_Notifications')
    op.drop_table('Sap_Notifications')
    # ### end Alembic commands ###
