"""Supervisor id to Email attempt

Revision ID: 2113d1c62543
Revises: 04a5f4130377
Create Date: 2022-06-22 03:08:48.388176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2113d1c62543'
down_revision = '04a5f4130377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('supervisor_user_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Action', 'User', ['supervisor_user_email'], ['email'])
    op.drop_column('Action', 'supervisor_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('supervisor_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Action', type_='foreignkey')
    op.drop_column('Action', 'supervisor_user_email')
    # ### end Alembic commands ###
