"""Redesign actions

Revision ID: 280ea12942f8
Revises: 8aeb52fe9130
Create Date: 2022-10-25 08:25:14.328278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "280ea12942f8"
down_revision = "8aeb52fe9130"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""DELETE FROM "Action" WHERE 1=1""")

    op.drop_index("ix_Action2_id", table_name="Action2")

    op.drop_constraint("fk_Comment_action_id_Action2", "Comment", type_="foreignkey")
    op.drop_constraint(
        "fk_General_Attachment_action_id_Action2", "General_Attachment", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_Action_Member_Association_action_id_Action2",
        "Action_Member_Association",
        type_="foreignkey",
    )

    op.drop_table("Action2")

    op.drop_column("Action", "completion")
    op.drop_column("Action", "linked_system_event_id")
    op.drop_column("Action", "action_tag")
    op.drop_column("Action", "linked_system")
    op.drop_column("Action", "function_location")

    op.add_column("Action", sa.Column("source_id", sa.String(), nullable=True))
    op.add_column("Action", sa.Column("type", sa.String(), nullable=True))
    op.add_column("Action", sa.Column("functional_location", sa.String(), nullable=True))
    op.add_column(
        "Action",
        sa.Column(
            "action_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
    )

    op.create_foreign_key(
        op.f("fk_Action_Member_Association_action_id_Action"),
        "Action_Member_Association",
        "Action",
        ["action_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        op.f("fk_Comment_action_id_Action"), "Comment", "Action", ["action_id"], ["id"]
    )

    op.create_foreign_key(
        op.f("fk_General_Attachment_action_id_Action"),
        "General_Attachment",
        "Action",
        ["action_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_General_Attachment_action_id_Action"), "General_Attachment", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_General_Attachment_action_id_Action2",
        "General_Attachment",
        "Action2",
        ["action_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_Comment_action_id_Action"), "Comment", type_="foreignkey")
    op.create_foreign_key(
        "fk_Comment_action_id_Action2", "Comment", "Action2", ["action_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_Action_Member_Association_action_id_Action"),
        "Action_Member_Association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_Action_Member_Association_action_id_Action2",
        "Action_Member_Association",
        "Action2",
        ["action_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "Action", sa.Column("function_location", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Action", sa.Column("linked_system", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Action", sa.Column("action_tag", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "Action",
        sa.Column("linked_system_event_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "Action", sa.Column("completion", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("Action", "action_metadata")
    op.drop_column("Action", "functional_location")
    op.drop_column("Action", "type")
    op.drop_column("Action", "source_id")
    op.create_table(
        "Action2",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Action2_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "action_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("source_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_due", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("privacy", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("functional_location", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("archive_user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "archive_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_archived", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("supervisor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "date_closed", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["User.id"], name="fk_Action2_owner_id_User"),
        sa.ForeignKeyConstraint(
            ["supervisor_id"], ["User.id"], name="fk_Action2_supervisor_id_User"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Action2"),
    )
    op.create_index("ix_Action2_id", "Action2", ["id"], unique=False)
    # ### end Alembic commands ###
