"""Revised the user database

Revision ID: 4f614c972cab
Revises: 87068ee11619
Create Date: 2022-05-23 06:37:04.432805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f614c972cab'
down_revision = '87068ee11619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('User', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('User', sa.Column('microsoft_id', sa.String(), nullable=True))
    op.add_column('User', sa.Column('site', sa.String(), nullable=True))
    op.add_column('User', sa.Column('back_to_back_id', sa.String(), nullable=True))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'back_to_back_id')
    op.drop_column('User', 'site')
    op.drop_column('User', 'microsoft_id')
    op.drop_column('User', 'last_name')
    op.drop_column('User', 'first_name')
    # ### end Alembic commands ###
