"""schemas.General_Attachments add title/desc

Revision ID: f2856900d63c
Revises: b07eb7c89887
Create Date: 2022-10-09 12:02:47.702109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2856900d63c'
down_revision = 'b07eb7c89887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('title', sa.String(), nullable=True))
    op.add_column('General_Attachment', sa.Column('description', sa.String(), nullable=True))
    op.add_column('General_Attachment', sa.Column('network_drive_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('General_Attachment', 'network_drive_link')
    op.drop_column('General_Attachment', 'description')
    op.drop_column('General_Attachment', 'title')
    # ### end Alembic commands ###
