"""is active col

Revision ID: f196b52c0661
Revises: bb88066779dc
Create Date: 2022-12-27 01:13:40.908519

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm.session import Session

from app import crud

# revision identifiers, used by Alembic.
revision = "f196b52c0661"
down_revision = "bb88066779dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Workgroup", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # get database session
    db = Session(op.get_bind())

    workgroups = crud.workgroup.all(db)
    for workgroup in workgroups:
        workgroup.is_active = True
        db.add(workgroup)

    db.commit()

    op.alter_column("Workgroup", "is_active", nullable=False)
    op.alter_column("Workgroup", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("Workgroup", "closed")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Workgroup", "is_active")
    op.add_column(
        "Workgroup", sa.Column("closed", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
