"""add link/asset col to schema.Action

Revision ID: 2dd5afe9c9c4
Revises: f145c7991c8a
Create Date: 2022-11-01 02:43:05.755732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd5afe9c9c4'
down_revision = 'f145c7991c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('link', sa.String(), nullable=True))
    op.add_column('Action', sa.Column('asset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'asset')
    op.drop_column('Action', 'link')
    # ### end Alembic commands ###
