"""added work_center to user db

Revision ID: 0e84ad3a6789
Revises: 44a39d248ff0
Create Date: 2022-05-16 05:10:25.613023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e84ad3a6789'
down_revision = '44a39d248ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('work_center', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'work_center')
    # ### end Alembic commands ###
