"""action schema version idk

Revision ID: f8d097bc820e
Revises: 60726b66cb32
Create Date: 2022-10-14 02:46:17.513139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d097bc820e'
down_revision = '60726b66cb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action_Member_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Action_Member_Association_action_id_Action'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Action_Member_Association_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action_Member_Association'))
    )
    op.create_index(op.f('ix_Action_Member_Association_id'), 'Action_Member_Association', ['id'], unique=False)
    op.add_column('Action', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Action_owner_id_User'), 'Action', 'User', ['owner_id'], ['id'])
    op.drop_column('Action', 'owner_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('owner_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_Action_owner_id_User'), 'Action', type_='foreignkey')
    op.drop_column('Action', 'owner_id')
    op.drop_index(op.f('ix_Action_Member_Association_id'), table_name='Action_Member_Association')
    op.drop_table('Action_Member_Association')
    # ### end Alembic commands ###
