"""Action Table Implementation

Revision ID: 99916a0b6f54
Revises: 4f614c972cab
Create Date: 2022-05-30 07:10:00.071015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99916a0b6f54'
down_revision = '4f614c972cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Action_id'), 'Action', ['id'], unique=False)
    op.create_table('Action_Owner_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Action_Owner_Association_id'), 'Action_Owner_Association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Action_Owner_Association_id'), table_name='Action_Owner_Association')
    op.drop_table('Action_Owner_Association')
    op.drop_index(op.f('ix_Action_id'), table_name='Action')
    op.drop_table('Action')
    # ### end Alembic commands ###
