"""remove unused schema

Revision ID: f8d1394ac920
Revises: 0990fc3060cd
Create Date: 2022-11-20 22:43:20.828905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d1394ac920'
down_revision = '0990fc3060cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Table_Headers_id', table_name='Table_Headers')
    op.drop_table('Table_Headers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Table_Headers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Table_Headers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('table', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('settings', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_Table_Headers_user_id_User'),
    sa.PrimaryKeyConstraint('id', name='pk_Table_Headers')
    )
    op.create_index('ix_Table_Headers_id', 'Table_Headers', ['id'], unique=False)
    # ### end Alembic commands ###
