"""user table big changes

Revision ID: 2b838e3e502c
Revises: f29f03663db7
Create Date: 2022-10-06 09:35:55.724000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b838e3e502c'
down_revision = 'f29f03663db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('User', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
