"""add dep_extra_owner_id field to action

Revision ID: 08dc0aac3ee8
Revises: f8d1394ac920
Create Date: 2022-11-21 05:15:22.299924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dc0aac3ee8'
down_revision = 'f8d1394ac920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('dep_extra_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Action_dep_extra_owner_id_User'), 'Action', 'User', ['dep_extra_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Action_dep_extra_owner_id_User'), 'Action', type_='foreignkey')
    op.drop_column('Action', 'dep_extra_owner_id')
    # ### end Alembic commands ###
