"""action 2, privacy

Revision ID: d06c95e210b0
Revises: d15c930eb80a
Create Date: 2022-10-21 07:52:18.134810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06c95e210b0'
down_revision = 'd15c930eb80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action2', sa.Column('privacy', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action2', 'privacy')
    # ### end Alembic commands ###
