"""SAP and SMH Legacy Removal

Revision ID: 0ad03961a062
Revises: 7dad9c0a6ae9
Create Date: 2022-11-07 07:28:44.999325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ad03961a062'
down_revision = '7dad9c0a6ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Sap_floc_historical_id', table_name='Sap_floc_historical')
    op.drop_table('Sap_floc_historical')
    op.drop_index('ix_Sap_work_centres_id', table_name='Sap_work_centres')
    op.drop_table('Sap_work_centres')
    op.drop_index('ix_Sap_workorders_id', table_name='Sap_workorders')
    op.drop_table('Sap_workorders')
    op.drop_index('ix_Shutdown_management_hub_id', table_name='Shutdown_management_hub')
    op.drop_table('Shutdown_management_hub')
    op.drop_index('ix_Sap_Notifications_id', table_name='Sap_Notifications')
    op.drop_table('Sap_Notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sap_Notifications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sap_Notifications_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_work_centre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('required_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Sap_Notifications')
    )
    op.create_index('ix_Sap_Notifications_id', 'Sap_Notifications', ['id'], unique=False)
    op.create_table('Shutdown_management_hub',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dbid', sa.INTEGER(), server_default=sa.text('nextval(\'"Shutdown_management_hub_dbid_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('emailid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'dbid', name='pk_Shutdown_management_hub')
    )
    op.create_index('ix_Shutdown_management_hub_id', 'Shutdown_management_hub', ['id'], unique=False)
    op.create_table('Sap_workorders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sap_workorders_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_work_center', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('basic_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('basic_finish_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Sap_workorders')
    )
    op.create_index('ix_Sap_workorders_id', 'Sap_workorders', ['id'], unique=False)
    op.create_table('Sap_work_centres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sap_work_centres_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('work_centre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Sap_work_centres')
    )
    op.create_index('ix_Sap_work_centres_id', 'Sap_work_centres', ['id'], unique=False)
    op.create_table('Sap_floc_historical',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sap_floc_historical_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_location_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('basic_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('basic_finish_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_changed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('main_work_center', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Sap_floc_historical')
    )
    op.create_index('ix_Sap_floc_historical_id', 'Sap_floc_historical', ['id'], unique=False)
    # ### end Alembic commands ###
