"""cascade rules on commnets

Revision ID: c7f96f502401
Revises: 559f24c08078
Create Date: 2022-10-31 08:21:48.984331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f96f502401'
down_revision = '559f24c08078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Comment_action_id_Action', 'Comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Comment_action_id_Action'), 'Comment', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Comment_action_id_Action'), 'Comment', type_='foreignkey')
    op.create_foreign_key('fk_Comment_action_id_Action', 'Comment', 'Action', ['action_id'], ['id'])
    # ### end Alembic commands ###
