"""rem bad cols from user

Revision ID: 3e2c90d92e1a
Revises: 2f222666e472
Create Date: 2022-11-28 22:56:43.695087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2c90d92e1a'
down_revision = '2f222666e472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'role')
    op.drop_column('User', 'site')
    op.drop_column('User', 'back_to_back_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('back_to_back_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
