"""Fullnameproperty

Revision ID: 4061ab48197d
Revises: eef74adf543f
Create Date: 2022-06-02 01:28:44.951234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4061ab48197d'
down_revision = 'eef74adf543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action_Comments', sa.Column('fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action_Comments', 'fullname')
    # ### end Alembic commands ###
