"""schemas.General_Attachments add

Revision ID: b07eb7c89887
Revises: 5d7bbc0353a8
Create Date: 2022-10-09 11:03:58.203974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07eb7c89887'
down_revision = '5d7bbc0353a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('General_Attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_filename', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_General_Attachment_action_id_Action'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['User.id'], name=op.f('fk_General_Attachment_deleted_by_User'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['Feedback.id'], name=op.f('fk_General_Attachment_feedback_id_Feedback'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['User.id'], name=op.f('fk_General_Attachment_uploaded_by_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_General_Attachment'))
    )
    op.create_index(op.f('ix_General_Attachment_id'), 'General_Attachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_General_Attachment_id'), table_name='General_Attachment')
    op.drop_table('General_Attachment')
    # ### end Alembic commands ###
