"""comment schema

Revision ID: d2220c91c77b
Revises: a68590c11404
Create Date: 2022-10-10 05:10:55.348915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2220c91c77b'
down_revision = 'a68590c11404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Comment_action_id_Action')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Comment_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Comment'))
    )
    op.create_index(op.f('ix_Comment_id'), 'Comment', ['id'], unique=False)
    op.drop_column('General_Attachment', 'network_drive_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('network_drive_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Comment_id'), table_name='Comment')
    op.drop_table('Comment')
    # ### end Alembic commands ###
