"""flip priority values

Revision ID: d6b3655e1538
Revises: f196b52c0661
Create Date: 2022-12-27 01:39:34.206509

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm.session import Session

from app import crud, schemas

# revision identifiers, used by Alembic.
revision = "d6b3655e1538"
down_revision = "f196b52c0661"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # get database session
    db = Session(op.get_bind())

    actions = crud.action.all(db)

    for action in actions:

        if not action or not action.priority:
            continue

        value = 6 - action.priority.value

        if value == 1:
            action.priority = schemas.PriorityEnum.URGENT
        elif value == 2:
            action.priority = schemas.PriorityEnum.HIGH
        elif value == 3:
            action.priority = schemas.PriorityEnum.MEDIUM
        elif value == 4:
            action.priority = schemas.PriorityEnum.LOW
        elif value == 5:
            action.priority = schemas.PriorityEnum.UNKNOWN
        else:
            action.priority = schemas.PriorityEnum.UNKNOWN

    db.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    db = Session(op.get_bind())

    actions = crud.action.all(db)

    for action in actions:

        if not action or not action.priority:
            continue

        value = 6 - action.priority.value

        if value == 1:
            action.priority = schemas.PriorityEnum.URGENT
        elif value == 2:
            action.priority = schemas.PriorityEnum.HIGH
        elif value == 3:
            action.priority = schemas.PriorityEnum.MEDIUM
        elif value == 4:
            action.priority = schemas.PriorityEnum.LOW
        elif value == 5:
            action.priority = schemas.PriorityEnum.UNKNOWN
        else:
            action.priority = schemas.PriorityEnum.UNKNOWN

    db.commit()
    # ### end Alembic commands ###
