"""add completed

Revision ID: a31d416f57de
Revises: d8245e4c0826
Create Date: 2022-11-07 07:34:03.225278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31d416f57de'
down_revision = 'd8245e4c0826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('completed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'completed')
    # ### end Alembic commands ###
