"""Workgroup ArchiveBy

Revision ID: 2ead0bc70a18
Revises: e6aa08fc77d2
Create Date: 2022-09-05 02:55:50.454845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ead0bc70a18'
down_revision = 'e6aa08fc77d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('archived_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'archived_by')
    # ### end Alembic commands ###
