"""Add ACE action cols

Revision ID: 2e50f4c58910
Revises: e60540afc118
Create Date: 2022-10-25 07:38:38.539094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e50f4c58910'
down_revision = 'e60540afc118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action2', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.add_column('Action2', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('Action2', sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('fk_Action2_created_by_id_User', 'Action2', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Action2_supervisor_id_User'), 'Action2', 'User', ['supervisor_id'], ['id'])
    op.drop_column('Action2', 'created_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action2', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_Action2_supervisor_id_User'), 'Action2', type_='foreignkey')
    op.create_foreign_key('fk_Action2_created_by_id_User', 'Action2', 'User', ['created_by_id'], ['id'])
    op.drop_column('Action2', 'date_closed')
    op.drop_column('Action2', 'status')
    op.drop_column('Action2', 'supervisor_id')
    # ### end Alembic commands ###
