"""added als sample data

Revision ID: 5eea6d2ff00f
Revises: df9cd1081266
Create Date: 2022-05-09 08:35:56.008587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eea6d2ff00f'
down_revision = 'df9cd1081266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ahm_AlsSampleData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sif_no', sa.String(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('compartment_location', sa.String(), nullable=True),
    sa.Column('compartment_name', sa.String(), nullable=True),
    sa.Column('floc_name', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('problem_code', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ahm_AlsSampleData_id'), 'Ahm_AlsSampleData', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Ahm_AlsSampleData_id'), table_name='Ahm_AlsSampleData')
    op.drop_table('Ahm_AlsSampleData')
    # ### end Alembic commands ###
