"""add log table

Revision ID: ae0688c2a3ce
Revises: 3e2c90d92e1a
Create Date: 2022-11-29 05:49:40.518435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0688c2a3ce'
down_revision = '3e2c90d92e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('workgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Log_action_id_Action')),
    sa.ForeignKeyConstraint(['workgroup_id'], ['Workgroup.id'], name=op.f('fk_Log_workgroup_id_Workgroup')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Log'))
    )
    op.create_index(op.f('ix_Log_id'), 'Log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Log_id'), table_name='Log')
    op.drop_table('Log')
    # ### end Alembic commands ###
