"""Attachment Table Implementation

Revision ID: 6ec345f2173e
Revises: 99916a0b6f54
Create Date: 2022-05-30 07:24:10.670885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec345f2173e'
down_revision = '99916a0b6f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Attachment_id'), 'Attachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Attachment_id'), table_name='Attachment')
    op.drop_table('Attachment')
    # ### end Alembic commands ###
