"""ID autoincrement

Revision ID: 42f728bef685
Revises: 2113d1c62543
Create Date: 2022-06-22 05:19:36.705261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f728bef685'
down_revision = '2113d1c62543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Fmg_Employees_id', table_name='Fmg_Employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Fmg_Employees_id', 'Fmg_Employees', ['id'], unique=False)
    # ### end Alembic commands ###
