"""Added work_centres db

Revision ID: 95008dcf8074
Revises: 0e84ad3a6789
Create Date: 2022-05-17 05:19:01.584706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95008dcf8074'
down_revision = '0e84ad3a6789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sap_work_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_centre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sap_work_centres_id'), 'Sap_work_centres', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sap_work_centres_id'), table_name='Sap_work_centres')
    op.drop_table('Sap_work_centres')
    # ### end Alembic commands ###
