"""add user_id to log table

Revision ID: bb88066779dc
Revises: ae0688c2a3ce
Create Date: 2022-11-29 06:35:18.090265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb88066779dc"
down_revision = "ae0688c2a3ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Log", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(op.f("fk_Log_user_id_User"), "Log", "User", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_Log_user_id_User"), "Log", type_="foreignkey")
    op.drop_column("Log", "user_id")
    # ### end Alembic commands ###
