"""cheange priority enum to int enum

Revision ID: 0990fc3060cd
Revises: 72fd1c756f26
Create Date: 2022-11-20 11:40:00.763504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0990fc3060cd'
down_revision = '72fd1c756f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'priority')
    # ### end Alembic commands ###
