"""user table big changes

Revision ID: f29f03663db7
Revises: 22dad5b2679c
Create Date: 2022-10-06 09:34:21.925780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29f03663db7'
down_revision = '22dad5b2679c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Action_supervisor_user_email_User', 'Action', type_='foreignkey')
    op.drop_constraint('fk_Action_Owner_Association_user_email_User', 'Action_Owner_Association', type_='foreignkey')
    op.add_column('User', sa.Column('back_to_back_id', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('last_logged_in', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_User_microsoft_id', table_name='User')
    op.create_foreign_key(op.f('fk_User_back_to_back_id_User'), 'User', 'User', ['back_to_back_id'], ['id'])
    op.drop_column('User', 'microsoft_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('microsoft_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_User_back_to_back_id_User'), 'User', type_='foreignkey')
    op.create_index('ix_User_microsoft_id', 'User', ['microsoft_id'], unique=False)
    op.drop_column('User', 'last_logged_in')
    op.drop_column('User', 'is_user')
    op.drop_column('User', 'back_to_back_id')
    op.create_foreign_key('fk_Action_Owner_Association_user_email_User', 'Action_Owner_Association', 'User', ['user_email'], ['email'], ondelete='CASCADE')
    op.create_foreign_key('fk_Action_supervisor_user_email_User', 'Action', 'User', ['supervisor_user_email'], ['email'])
    # ### end Alembic commands ###
