"""change name Ace -> ACE

Revision ID: a542a8f2fe75
Revises: 949f85989ddf
Create Date: 2022-10-24 00:14:30.062432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a542a8f2fe75'
down_revision = '949f85989ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
