"""Workgroup_id added to Action

Revision ID: ca249c6628d0
Revises: 7ee5a8f4fe8a
Create Date: 2022-09-21 07:54:53.315822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca249c6628d0"
down_revision = "7ee5a8f4fe8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Action", sa.Column("workgroup_id", sa.Integer(), nullable=True))
    # op.drop_constraint('fk_Action_supervisor_user_email_User', 'Action', type_='foreignkey')
    # op.drop_constraint('fk_Action_Owner_Association_user_email_User', 'Action_Owner_Association', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key('fk_Action_Owner_Association_user_email_User', 'Action_Owner_Association', 'User', ['user_email'], ['email'], ondelete='CASCADE')
    # op.create_foreign_key('fk_Action_supervisor_user_email_User', 'Action', 'User', ['supervisor_user_email'], ['email'])
    op.drop_column("Action", "workgroup_id")
    # ### end Alembic commands ###
