"""schemas.actions 2.0

Revision ID: 5c2f6bc395c9
Revises: 0f3c6b549907
Create Date: 2022-10-07 08:16:17.689845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2f6bc395c9'
down_revision = '0f3c6b549907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('linked_system', sa.Integer(), nullable=True),
    sa.Column('linked_system_event_id', sa.String(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('action_tag', sa.Integer(), nullable=True),
    sa.Column('completion', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['User.id'], name=op.f('fk_Action_supervisor_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action'))
    )
    op.create_index(op.f('ix_Action_id'), 'Action', ['id'], unique=False)
    op.create_table('Action_Owner_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Action_Owner_Association_action_id_Action'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Action_Owner_Association_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action_Owner_Association'))
    )
    op.create_index(op.f('ix_Action_Owner_Association_id'), 'Action_Owner_Association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Action_Owner_Association_id'), table_name='Action_Owner_Association')
    op.drop_table('Action_Owner_Association')
    op.drop_index(op.f('ix_Action_id'), table_name='Action')
    op.drop_table('Action')
    # ### end Alembic commands ###
