"""FullName fix fmg

Revision ID: 45a4276a7617
Revises: a7c668699134
Create Date: 2022-08-15 01:23:15.876472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a4276a7617'
down_revision = 'a7c668699134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Fmg_Employees', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Fmg_Employees', 'full_name')
    # ### end Alembic commands ###
