"""change colname

Revision ID: ed12f25f1129
Revises: 48e5953d5c10
Create Date: 2022-06-09 00:43:05.503633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed12f25f1129'
down_revision = '48e5953d5c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IngestedUser', sa.Column('fullname', sa.String(), nullable=True))
    op.drop_column('IngestedUser', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IngestedUser', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('IngestedUser', 'fullname')
    # ### end Alembic commands ###
