"""add status

Revision ID: 559f24c08078
Revises: 280ea12942f8
Create Date: 2022-10-25 09:57:13.556913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559f24c08078'
down_revision = '280ea12942f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
