"""user schema remove single floc and workcenter

Revision ID: 470e1842c8fd
Revises: e227e097e6c4
Create Date: 2022-11-18 04:18:32.024563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470e1842c8fd'
down_revision = 'e227e097e6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'work_center')
    op.drop_column('User', 'functional_loc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('functional_loc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('work_center', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
