"""table headers added

Revision ID: f5cdf52d60e2
Revises: 0b2692823b29
Create Date: 2022-06-29 00:35:01.583025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cdf52d60e2'
down_revision = '0b2692823b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Table_Headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Table_Headers_id'), 'Table_Headers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Table_Headers_id'), table_name='Table_Headers')
    op.drop_table('Table_Headers')
    # ### end Alembic commands ###
