"""Workgroup is_private

Revision ID: 749ab629fec8
Revises: 9ccefffbe99c
Create Date: 2022-08-24 07:03:01.622386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749ab629fec8'
down_revision = '9ccefffbe99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'is_private')
    # ### end Alembic commands ###
