"""Change to Workgrup to use emails

Revision ID: 76627138fa33
Revises: 2c02da2bdae5
Create Date: 2022-06-23 03:01:05.569596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76627138fa33'
down_revision = '2c02da2bdae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup_Admin_Association', sa.Column('user_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Workgroup_Admin_Association', 'Fmg_Employees', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('Workgroup_Admin_Association', 'user_id')
    op.add_column('Workgroup_Owner_Association', sa.Column('user_email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Workgroup_Owner_Association', 'Fmg_Employees', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('Workgroup_Owner_Association', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup_Owner_Association', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Workgroup_Owner_Association', type_='foreignkey')
    op.drop_column('Workgroup_Owner_Association', 'user_email')
    op.add_column('Workgroup_Admin_Association', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Workgroup_Admin_Association', type_='foreignkey')
    op.drop_column('Workgroup_Admin_Association', 'user_email')
    # ### end Alembic commands ###
