"""Workgroup Change to privacy

Revision ID: 9ccefffbe99c
Revises: b3c7a660188b
Create Date: 2022-08-24 06:37:04.335984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccefffbe99c'
down_revision = 'b3c7a660188b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('privacy_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'privacy_rating')
    # ### end Alembic commands ###
