"""User schemas add sap_number

Revision ID: 846c624214e7
Revises: 3e42c6250c7d
Create Date: 2022-06-09 01:40:35.582760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846c624214e7'
down_revision = '3e42c6250c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('sap_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_User_sap_number'), 'User', ['sap_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_sap_number'), table_name='User')
    op.drop_column('User', 'sap_number')
    # ### end Alembic commands ###
