"""Action Changes to Link to Actions

Revision ID: d5fce547b542
Revises: 4a23e2ab0c6e
Create Date: 2022-08-22 07:31:04.144817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fce547b542'
down_revision = '4a23e2ab0c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('linked_system', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'linked_system')
    # ### end Alembic commands ###
