"""Workgroup Archive Ability

Revision ID: e6aa08fc77d2
Revises: 3a9165c7a85b
Create Date: 2022-09-05 01:41:08.860097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6aa08fc77d2'
down_revision = '3a9165c7a85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'is_archived')
    # ### end Alembic commands ###
