"""user schema has functional_locations

Revision ID: f24b4a8c9df6
Revises: 2f8eae9772dc
Create Date: 2022-11-18 02:39:04.314783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24b4a8c9df6'
down_revision = '2f8eae9772dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('functional_locations', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'functional_locations')
    # ### end Alembic commands ###
