"""add privacy col to schemas.workgroup

Revision ID: ef89d332a597
Revises: e031de9085a3
Create Date: 2022-10-13 09:35:49.292037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef89d332a597'
down_revision = 'e031de9085a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('privacy', sa.Integer(), nullable=True))
    op.drop_column('Workgroup', 'is_confidential')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('is_confidential', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Workgroup', 'privacy')
    # ### end Alembic commands ###
