"""owners, members

Revision ID: aecb2ff3aa8d
Revises: 88fad412155d
Create Date: 2022-10-13 13:10:47.277260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aecb2ff3aa8d'
down_revision = '88fad412155d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('Workgroup', sa.Column('member_ids', sa.JSON(), nullable=True))
    op.create_foreign_key(op.f('fk_Workgroup_owner_id_User'), 'Workgroup', 'User', ['owner_id'], ['id'])
    op.drop_column('Workgroup', 'owner_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('owner_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_Workgroup_owner_id_User'), 'Workgroup', type_='foreignkey')
    op.drop_column('Workgroup', 'member_ids')
    op.drop_column('Workgroup', 'owner_id')
    # ### end Alembic commands ###
