"""Attachment Fixes

Revision ID: 93d060ddd03d
Revises: ca249c6628d0
Create Date: 2022-09-26 01:29:51.197000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d060ddd03d'
down_revision = 'ca249c6628d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_General_Attachment_action_id_Action'), 'General_Attachment', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_General_Attachment_action_id_Action'), 'General_Attachment', type_='foreignkey')
    op.drop_column('General_Attachment', 'action_id')
    # ### end Alembic commands ###
