"""Favorite Legacy Removal

Revision ID: 29a8e15d35e0
Revises: 88d635b277d8
Create Date: 2022-11-07 07:19:05.666339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29a8e15d35e0'
down_revision = '88d635b277d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Favorites_id', table_name='Favorites')
    op.drop_table('Favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favorites_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sap_order_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Favorites')
    )
    op.create_index('ix_Favorites_id', 'Favorites', ['id'], unique=False)
    # ### end Alembic commands ###
