"""add microsoft id column to users table

Revision ID: 46429075750e
Revises: 116443597ef9
Create Date: 2023-02-14 02:46:09.142644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46429075750e'
down_revision = '116443597ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('microsoft_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'microsoft_id')
    # ### end Alembic commands ###
