"""history schema dont_show_again

Revision ID: 51fa31b1b0c7
Revises: 57bc63fac208
Create Date: 2023-01-25 01:19:21.712627

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51fa31b1b0c7"
down_revision = "57bc63fac208"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("dont_show_news_again", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "dont_show_news_again")
    # ### end Alembic commands ###
