"""add archive_action table


Revision ID: 70d4475647ad
Revises: 11d042257d1a
Create Date: 2023-01-31 09:01:54.602530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d4475647ad'
down_revision = '11d042257d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Archive_Action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archive_user_id', sa.Integer(), nullable=True),
    sa.Column('archive_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('supervisor_email', sa.String(), nullable=True),
    sa.Column('source_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('functional_location', sa.String(), nullable=True),
    sa.Column('work_center', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('action_metadata', sa.String(), nullable=True),
    sa.Column('dep_extra_owner_email', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('member_emails', sa.String(), nullable=True),
    sa.Column('workgroup_titles', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Archive_Action'))
    )
    op.create_index(op.f('ix_Archive_Action_id'), 'Archive_Action', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Archive_Action_id'), table_name='Archive_Action')
    op.drop_table('Archive_Action')
    # ### end Alembic commands ###
