"""add teams sync columns to log table

Revision ID: b47450cf67a1
Revises: a8bbdb84fd04
Create Date: 2023-02-22 09:44:55.380467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47450cf67a1'
down_revision = 'a8bbdb84fd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Log', sa.Column('total_workgroups_created', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('workgroup_ids_involved', sa.String(), nullable=True))
    op.add_column('Log', sa.Column('user_ids_involved', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Log', 'user_ids_involved')
    op.drop_column('Log', 'workgroup_ids_involved')
    op.drop_column('Log', 'total_workgroups_created')
    # ### end Alembic commands ###
