"""new log table

Revision ID: f248b3d6b904
Revises: 70d4475647ad
Create Date: 2023-02-07 03:24:54.931768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f248b3d6b904'
down_revision = '70d4475647ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Log', sa.Column('sync_uuid', sa.String(), nullable=True))
    op.add_column('Log', sa.Column('total_actions_created', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('total_actions_archived', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('total_actions_updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Log', 'total_actions_updated')
    op.drop_column('Log', 'total_actions_archived')
    op.drop_column('Log', 'total_actions_created')
    op.drop_column('Log', 'sync_uuid')
    # ### end Alembic commands ###
