"""Remove Equipment schema

Revision ID: b93f79068922
Revises: d6b3655e1538
Create Date: 2023-01-18 00:13:33.510096

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b93f79068922"
down_revision = "d6b3655e1538"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_Equipment_id", table_name="Equipment")
    op.drop_table("Equipment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Equipment",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Equipment_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("function_location", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("site", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("department", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("catalog_profile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("equipment_description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("object_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_Equipment"),
    )
    op.create_index("ix_Equipment_id", "Equipment", ["id"], unique=False)
    # ### end Alembic commands ###
