"""update history schema

Revision ID: 6cc45847ffdb
Revises: d6b3655e1538
Create Date: 2023-01-24 23:58:11.206961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6cc45847ffdb"
down_revision = "d6b3655e1538"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Update_History",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_Update_History_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Update_History")),
    )
    op.create_index(op.f("ix_Update_History_id"), "Update_History", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Update_History_id"), table_name="Update_History")
    op.drop_table("Update_History")
    # ### end Alembic commands ###
