"""add is_deleted field to actions

Revision ID: 116443597ef9
Revises: 6b037c0d1a34
Create Date: 2023-02-07 08:05:21.811553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116443597ef9'
down_revision = '6b037c0d1a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'is_deleted')
    # ### end Alembic commands ###
