"""history schema active

Revision ID: 57bc63fac208
Revises: 6cc45847ffdb
Create Date: 2023-01-25 00:50:01.753758

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57bc63fac208"
down_revision = "6cc45847ffdb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Update_History", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Update_History", "active")
    # ### end Alembic commands ###
