"""add syncUUID to archive_action table


Revision ID: 6b037c0d1a34
Revises: f248b3d6b904
Create Date: 2023-02-07 05:21:31.877240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b037c0d1a34'
down_revision = 'f248b3d6b904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Archive_Action', sa.Column('syncUUID', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Archive_Action', 'syncUUID')
    # ### end Alembic commands ###
