"""supervisor id

Revision ID: 7cde6311b5a2
Revises: d6b3655e1538
Create Date: 2023-01-07 10:31:56.902793

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cde6311b5a2"
down_revision = "d6b3655e1538"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("supervisor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_User_supervisor_id_User"), "User", "User", ["supervisor_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_User_supervisor_id_User"), "User", type_="foreignkey")
    op.drop_column("User", "supervisor_id")
    # ### end Alembic commands ###
