"""add teams_last_updaed column to workgroup

Revision ID: a8bbdb84fd04
Revises: 9030b4202acf
Create Date: 2023-02-22 04:51:54.428939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bbdb84fd04'
down_revision = '9030b4202acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('teams_last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'teams_last_updated')
    # ### end Alembic commands ###
