"""add teams_id to workgroup

Revision ID: 11d042257d1a
Revises: 2faf018fd8d2
Create Date: 2023-01-18 06:31:22.894143

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '11d042257d1a'
down_revision = '2faf018fd8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workgroup', sa.Column('teams_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workgroup', 'teams_id')
    # ### end Alembic commands ###
