import FeedbackEnumIcon from '@/components/Icon/FeedbackEnumIcon'
import FeedbackStatusIcon from '@/components/Icon/FeedbackStatusIcon'
import PriorityEnumIcon from '@/components/Icon/PriorityEnumIcon.vue'
import StatusEnumIcon from '@/components/Icon/StatusEnumIcon.vue'
import PrivacyEnumIcon from '@/components/Icon/PrivacyEnumIcon.vue'
import ShowMetadataPopup from '@/components/Action/ShowMetadataPopup.vue'

export default ({ app, store }, inject) => {
  inject('table_headers', {
    // -----------------------------------------
    // TABLE HEADERS
    // -----------------------------------------
    action_simple: [
      {
        text: '#',
        align: 'center',
        value: 'id',
        sortable: false,
        divider: true,
        hide: false,
        width: '10',
      },
      {
        text: 'Link',
        value: 'link',
        align: 'center',
        divider: true,
        sortable: false,
        hide: false,
        width: '10',
      },
      {
        text: 'Privacy',
        value: 'privacy',
        hide: false,
        width: '10',
        divider: true,
        align: 'center',
        component: PrivacyEnumIcon,
      },
      {
        text: 'Meta',
        value: 'action_metadata',
        align: 'center',
        divider: true,
        sortable: false,
        hide: false,
        width: '10',
        component: ShowMetadataPopup,
      },
      {
        text: 'Action',
        value: 'title',
        cellClass: 'title-cell',
        divider: true,
      },
      {
        text: 'Source',
        value: 'type',
        width: '10',
        formatter: (x) => x.replaceAll('_', ' '),
        cellClass: 'nowrap',
        divider: true,
      },
      {
        text: 'Assigned To',
        value: 'owner_id',
        cellClass: 'nowrap',
        formatter: (x) => app.$utils.getUserName(x),
        width: '10',
        divider: true,
      },
      {
        text: 'Members',
        value: 'member_ids',
        hide: false,
        formatter: (x) =>
          x
            .map((a) => app.$utils.getUserName(a))
            .sort()
            .join(', '),
        cellClass: 'title-cell',
        divider: true,
        sortable: false,
      },
      {
        text: 'Priority',
        value: 'priority',
        align: 'center',
        component: PriorityEnumIcon,
        width: '10',
        divider: true,
      },
      {
        text: 'Status',
        value: 'status',
        align: 'center',
        component: StatusEnumIcon,
        width: '10',
        divider: true,
      },
      {
        text: 'Date Due',
        value: 'date_due',
        formatter: (x) => app.$format.date(x),
        width: '10',
        divider: true,
      },
      {
        text: 'FLOC',
        value: 'functional_location',
        cellClass: 'nowrap',
        divider: true,
      },
      {
        text: 'Work Center',
        value: 'work_center',
        cellClass: 'nowrap',
        divider: true,
      },
      // other action fields
      {
        text: 'Supervisor',
        value: 'supervisor_id',
        formatter: (x) => app.$utils.getUserName(x),
        cellClass: 'nowrap',
        hide: false,
        divider: true,
      },
      {
        text: 'Start Date',
        value: 'start_date',
        formatter: (x) => app.$format.date(x),
        width: '10',
        divider: true,
      },
      {
        text: 'Date Closed',
        value: 'date_closed',
        cellClass: 'nowrap',
        hide: false,
        formatter: (x) => (x ? app.$format.date(x) : ''),
        width: '10',
        divider: true,
      },
    ],
    feedback: [
      {
        text: '#',
        align: 'center',
        value: 'id',
        sortable: false,
        divider: true,
        hide: false,
        width: '10',
      },
      {
        text: 'Edit',
        value: 'edit',
        width: '10',
        align: 'center',
        divider: true,
        sortable: false,
        hide: false,
      },
      {
        text: 'Reason',
        value: 'reason',
        hide: false,
        divider: true,
        cellClass: 'wrap-text',
        width: '10',
        align: 'center',
        component: FeedbackEnumIcon,
      },
      {
        text: 'Status',
        value: 'status',
        divider: true,
        align: 'center',
        component: FeedbackStatusIcon,
        width: '10',
      },
      {
        text: 'Created',
        value: 'created',
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: '10',
        cellClass: 'nowrap',
      },
      {
        text: 'Last Updated',
        value: 'updated',
        formatter: (x) => app.$format.date(x),
        divider: true,
        width: '10',
        cellClass: 'nowrap',
      },
      {
        text: 'Created By',
        value: 'created_by_id',
        formatter: (x) => app.$utils.getUserName(x),
        hide: false,
        divider: true,
        width: '10',
        cellClass: 'nowrap',
      },
      {
        text: 'Last Updated By',
        value: 'updated_by_id',
        formatter: (x) => app.$utils.getUserName(x),
        hide: false,
        divider: true,
        width: '10',
        cellClass: 'nowrap',
      },
      {
        text: 'Title',
        value: 'title',
        hide: false,
        divider: true,
        cellClass: 'nowrap',
        width: '10',
      },
      {
        text: 'Issue relates to',
        value: 'page',
        hide: false,
        divider: true,
        cellClass: 'nowrap',
        width: '10',
      },
      {
        text: 'Summary',
        value: 'summary',
        hide: false,
        divider: true,
        cellClass: 'title-cell',
        width: '10',
      },
      {
        text: 'How to Replicate',
        value: 'replicate',
        hide: false,
        divider: true,
        cellClass: 'title-cell',
        width: '10',
      },
    ],
  })
}
