"""users have sap_number

Revision ID: 7c6bb4dc068a
Revises: b31df511e015
Create Date: 2022-06-02 05:58:18.339964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6bb4dc068a'
down_revision = 'b31df511e015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('sap_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_User_sap_number'), 'User', ['sap_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_sap_number'), table_name='User')
    op.drop_column('User', 'sap_number')
    # ### end Alembic commands ###
