"""dashboard schema pass 1

Revision ID: f586bb1ec9e7
Revises: eec478c82895
Create Date: 2022-06-15 02:15:11.313467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f586bb1ec9e7'
down_revision = 'eec478c82895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tab_title', sa.String(), nullable=True),
    sa.Column('tab_number', sa.Integer(), nullable=True),
    sa.Column('tab_type', sa.Integer(), nullable=True),
    sa.Column('tableau_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Dashboard'))
    )
    op.create_index(op.f('ix_Dashboard_id'), 'Dashboard', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Dashboard_id'), table_name='Dashboard')
    op.drop_table('Dashboard')
    # ### end Alembic commands ###
