"""action comment schema

Revision ID: b13f42552205
Revises: adf8268e3c10
Create Date: 2022-07-22 05:45:40.903717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13f42552205'
down_revision = 'adf8268e3c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action_Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Action_Comment_action_id_Action')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Action_Comment_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action_Comment'))
    )
    op.create_index(op.f('ix_Action_Comment_id'), 'Action_Comment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Action_Comment_id'), table_name='Action_Comment')
    op.drop_table('Action_Comment')
    # ### end Alembic commands ###
