"""remove not needed col

Revision ID: 7ba414e3b54a
Revises: d4dfacfd73aa
Create Date: 2022-06-27 13:24:35.233738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba414e3b54a'
down_revision = 'd4dfacfd73aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Root_Cause_Detail', 'cause')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Root_Cause_Detail', sa.Column('cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
