"""status to actions

Revision ID: 55bbced0b863
Revises: 6fc063549144
Create Date: 2022-06-23 06:38:34.173555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bbced0b863'
down_revision = '6fc063549144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'status')
    # ### end Alembic commands ###
