"""schemas General_Attachments  add size

Revision ID: dba30cfa3503
Revises: b13f42552205
Create Date: 2022-07-22 07:38:29.422721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba30cfa3503'
down_revision = 'b13f42552205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('General_Attachment', 'size')
    # ### end Alembic commands ###
