"""add circuit Dashboards

Revision ID: 555c5a07d499
Revises: 8adfd8943d24
Create Date: 2022-07-28 08:14:49.467939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555c5a07d499'
down_revision = '8adfd8943d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('aplus_circuit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'aplus_circuit')
    # ### end Alembic commands ###
