"""remove schemas.REMS_Event_Details.event_id

Revision ID: 88870dd53d59
Revises: 724793635bbe
Create Date: 2022-05-31 09:01:58.692676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88870dd53d59'
down_revision = '724793635bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('event_type', sa.Integer(), nullable=True))
    op.drop_column('REMS_Event_Details', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REMS_Event_Details', sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Investigation', 'event_type')
    # ### end Alembic commands ###
