"""Refresh Alembic

Revision ID: 5ccf5a2bbdd0
Revises: 
Create Date: 2022-05-25 03:26:46.193150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ccf5a2bbdd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Charting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('equipment_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('effective_duration', sa.Float(), nullable=True),
    sa.Column('time_usage_code', sa.String(), nullable=True),
    sa.Column('problem', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Charting'))
    )
    op.create_index(op.f('ix_Charting_id'), 'Charting', ['id'], unique=False)
    op.create_table('ChartingREMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_comment', sa.String(), nullable=True),
    sa.Column('functional_location', sa.String(), nullable=True),
    sa.Column('fleet_type', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('equipment_name', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('floc6', sa.String(), nullable=True),
    sa.Column('floc7', sa.String(), nullable=True),
    sa.Column('floc8', sa.String(), nullable=True),
    sa.Column('event_duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ChartingREMS'))
    )
    op.create_index(op.f('ix_ChartingREMS_id'), 'ChartingREMS', ['id'], unique=False)
    op.create_table('Equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('catalog_profile', sa.String(), nullable=True),
    sa.Column('equipment_description', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Equipment'))
    )
    op.create_index(op.f('ix_Equipment_id'), 'Equipment', ['id'], unique=False)
    op.create_table('Event_Details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('tonnes_lost', sa.Float(), nullable=True),
    sa.Column('effective_duration', sa.Float(), nullable=True),
    sa.Column('downtime_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Event_Details'))
    )
    op.create_index(op.f('ix_Event_Details_id'), 'Event_Details', ['id'], unique=False)
    op.create_table('Five_Why_Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_response_id', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_response_id'], ['Five_Why_Response.id'], name=op.f('fk_Five_Why_Response_parent_response_id_Five_Why_Response')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Five_Why_Response'))
    )
    op.create_index(op.f('ix_Five_Why_Response_id'), 'Five_Why_Response', ['id'], unique=False)
    op.create_table('Object_Code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cat_prof_code', sa.String(), nullable=True),
    sa.Column('cat_prof_description', sa.String(), nullable=True),
    sa.Column('catalog', sa.String(), nullable=True),
    sa.Column('code_group', sa.String(), nullable=True),
    sa.Column('code_group_description', sa.String(), nullable=True),
    sa.Column('object_code', sa.String(), nullable=True),
    sa.Column('object_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Object_Code'))
    )
    op.create_index(op.f('ix_Object_Code_id'), 'Object_Code', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User'))
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Investigation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('investigation_type', sa.Integer(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('equipment_description', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('catalog_profile', sa.String(), nullable=True),
    sa.Column('catalog_profiles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('object_part_description', sa.String(), nullable=True),
    sa.Column('damage_code', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['User.id'], name=op.f('fk_Investigation_supervisor_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Investigation'))
    )
    op.create_index(op.f('ix_Investigation_id'), 'Investigation', ['id'], unique=False)
    op.create_table('Five_Why',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('root_response_id', sa.Integer(), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Five_Why_investigation_id_Investigation')),
    sa.ForeignKeyConstraint(['root_response_id'], ['Five_Why_Response.id'], name=op.f('fk_Five_Why_root_response_id_Five_Why_Response')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Five_Why'))
    )
    op.create_index(op.f('ix_Five_Why_id'), 'Five_Why', ['id'], unique=False)
    op.create_table('Flash_Report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(), nullable=True),
    sa.Column('business_impact', sa.String(), nullable=True),
    sa.Column('immediate_action_taken', sa.String(), nullable=True),
    sa.Column('potential_root_causes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Flash_Report_investigation_id_Investigation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Flash_Report'))
    )
    op.create_index(op.f('ix_Flash_Report_id'), 'Flash_Report', ['id'], unique=False)
    op.create_table('Investigation_Owner_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Investigation_Owner_Association_investigation_id_Investigation')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Investigation_Owner_Association_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Investigation_Owner_Association'))
    )
    op.create_index(op.f('ix_Investigation_Owner_Association_id'), 'Investigation_Owner_Association', ['id'], unique=False)
    op.create_table('Relevant_Investigation_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('relevent_investigation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Relevant_Investigation_Association_investigation_id_Investigation')),
    sa.ForeignKeyConstraint(['relevent_investigation_id'], ['Investigation.id'], name=op.f('fk_Relevant_Investigation_Association_relevent_investigation_id_Investigation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Relevant_Investigation_Association'))
    )
    op.create_index(op.f('ix_Relevant_Investigation_Association_id'), 'Relevant_Investigation_Association', ['id'], unique=False)
    op.create_table('Root_Cause_Detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('cause_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('additional_contribution_factors', sa.String(), nullable=True),
    sa.Column('cause_category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Root_Cause_Detail_investigation_id_Investigation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Root_Cause_Detail'))
    )
    op.create_index(op.f('ix_Root_Cause_Detail_id'), 'Root_Cause_Detail', ['id'], unique=False)
    op.create_table('Selected_Event_Details_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('event_details_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_details_id'], ['Event_Details.id'], name=op.f('fk_Selected_Event_Details_Association_event_details_id_Event_Details')),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Selected_Event_Details_Association_investigation_id_Investigation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Selected_Event_Details_Association'))
    )
    op.create_index(op.f('ix_Selected_Event_Details_Association_id'), 'Selected_Event_Details_Association', ['id'], unique=False)
    op.create_table('Action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('five_why_id', sa.Integer(), nullable=True),
    sa.Column('flash_report_id', sa.Integer(), nullable=True),
    sa.Column('root_cause_detail_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['five_why_id'], ['Five_Why.id'], name=op.f('fk_Action_five_why_id_Five_Why')),
    sa.ForeignKeyConstraint(['flash_report_id'], ['Flash_Report.id'], name=op.f('fk_Action_flash_report_id_Flash_Report')),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Action_investigation_id_Investigation')),
    sa.ForeignKeyConstraint(['root_cause_detail_id'], ['Root_Cause_Detail.id'], name=op.f('fk_Action_root_cause_detail_id_Root_Cause_Detail')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['User.id'], name=op.f('fk_Action_supervisor_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action'))
    )
    op.create_index(op.f('ix_Action_id'), 'Action', ['id'], unique=False)
    op.create_table('Action_Owner_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Action_Owner_Association_action_id_Action')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Action_Owner_Association_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action_Owner_Association'))
    )
    op.create_index(op.f('ix_Action_Owner_Association_id'), 'Action_Owner_Association', ['id'], unique=False)
    op.create_table('Attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('five_why_response_id', sa.Integer(), nullable=True),
    sa.Column('flash_report_id', sa.Integer(), nullable=True),
    sa.Column('root_cause_detail_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['Action.id'], name=op.f('fk_Attachment_action_id_Action'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['five_why_response_id'], ['Five_Why_Response.id'], name=op.f('fk_Attachment_five_why_response_id_Five_Why_Response'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flash_report_id'], ['Flash_Report.id'], name=op.f('fk_Attachment_flash_report_id_Flash_Report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_cause_detail_id'], ['Root_Cause_Detail.id'], name=op.f('fk_Attachment_root_cause_detail_id_Root_Cause_Detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Attachment'))
    )
    op.create_index(op.f('ix_Attachment_id'), 'Attachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Attachment_id'), table_name='Attachment')
    op.drop_table('Attachment')
    op.drop_index(op.f('ix_Action_Owner_Association_id'), table_name='Action_Owner_Association')
    op.drop_table('Action_Owner_Association')
    op.drop_index(op.f('ix_Action_id'), table_name='Action')
    op.drop_table('Action')
    op.drop_index(op.f('ix_Selected_Event_Details_Association_id'), table_name='Selected_Event_Details_Association')
    op.drop_table('Selected_Event_Details_Association')
    op.drop_index(op.f('ix_Root_Cause_Detail_id'), table_name='Root_Cause_Detail')
    op.drop_table('Root_Cause_Detail')
    op.drop_index(op.f('ix_Relevant_Investigation_Association_id'), table_name='Relevant_Investigation_Association')
    op.drop_table('Relevant_Investigation_Association')
    op.drop_index(op.f('ix_Investigation_Owner_Association_id'), table_name='Investigation_Owner_Association')
    op.drop_table('Investigation_Owner_Association')
    op.drop_index(op.f('ix_Flash_Report_id'), table_name='Flash_Report')
    op.drop_table('Flash_Report')
    op.drop_index(op.f('ix_Five_Why_id'), table_name='Five_Why')
    op.drop_table('Five_Why')
    op.drop_index(op.f('ix_Investigation_id'), table_name='Investigation')
    op.drop_table('Investigation')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Object_Code_id'), table_name='Object_Code')
    op.drop_table('Object_Code')
    op.drop_index(op.f('ix_Five_Why_Response_id'), table_name='Five_Why_Response')
    op.drop_table('Five_Why_Response')
    op.drop_index(op.f('ix_Event_Details_id'), table_name='Event_Details')
    op.drop_table('Event_Details')
    op.drop_index(op.f('ix_Equipment_id'), table_name='Equipment')
    op.drop_table('Equipment')
    op.drop_index(op.f('ix_ChartingREMS_id'), table_name='ChartingREMS')
    op.drop_table('ChartingREMS')
    op.drop_index(op.f('ix_Charting_id'), table_name='Charting')
    op.drop_table('Charting')
    # ### end Alembic commands ###
