"""feeback schema pass1

Revision ID: 60cf809cb345
Revises: 7578232b2f50
Create Date: 2022-08-31 03:34:03.398712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cf809cb345'
down_revision = '7578232b2f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('replicate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Feedback'))
    )
    op.create_index(op.f('ix_Feedback_id'), 'Feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Feedback_id'), table_name='Feedback')
    op.drop_table('Feedback')
    # ### end Alembic commands ###
