"""title and description in general attachments

Revision ID: 383cfe1e8b0f
Revises: 547fb30b7f2a
Create Date: 2022-09-21 02:29:15.388641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383cfe1e8b0f'
down_revision = '547fb30b7f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('title', sa.String(), nullable=True))
    op.add_column('General_Attachment', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('General_Attachment', 'description')
    op.drop_column('General_Attachment', 'title')
    # ### end Alembic commands ###
