"""Notification add tags option

Revision ID: d70e649ff994
Revises: 5974dae7d87b
Create Date: 2022-06-10 00:52:34.334437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd70e649ff994'
down_revision = '5974dae7d87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notification', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notification', 'tags')
    # ### end Alembic commands ###
