"""date_closed to investigations

Revision ID: ab9cc7dcf6ff
Revises: 840af5b2a6f9
Create Date: 2022-06-30 03:06:29.506996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9cc7dcf6ff'
down_revision = '840af5b2a6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'date_closed')
    # ### end Alembic commands ###
