"""schemas.Logs add fk constraints

Revision ID: 2b3b47744fb2
Revises: c5cec601c17b
Create Date: 2022-09-13 01:11:14.926794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3b47744fb2'
down_revision = 'c5cec601c17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Log', sa.Column('investigation_id', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('flash_report_id', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('five_why_id', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('root_cause_detail_id', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('shared_learning_id', sa.Integer(), nullable=True))
    op.add_column('Log', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Log_five_why_id_Five_Why'), 'Log', 'Five_Why', ['five_why_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Log_root_cause_detail_id_Root_Cause_Detail'), 'Log', 'Root_Cause_Detail', ['root_cause_detail_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Log_action_id_Action'), 'Log', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Log_investigation_id_Investigation'), 'Log', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Log_flash_report_id_Flash_Report'), 'Log', 'Flash_Report', ['flash_report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Log_shared_learning_id_Shared_Learning'), 'Log', 'Shared_Learning', ['shared_learning_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Log_shared_learning_id_Shared_Learning'), 'Log', type_='foreignkey')
    op.drop_constraint(op.f('fk_Log_flash_report_id_Flash_Report'), 'Log', type_='foreignkey')
    op.drop_constraint(op.f('fk_Log_investigation_id_Investigation'), 'Log', type_='foreignkey')
    op.drop_constraint(op.f('fk_Log_action_id_Action'), 'Log', type_='foreignkey')
    op.drop_constraint(op.f('fk_Log_root_cause_detail_id_Root_Cause_Detail'), 'Log', type_='foreignkey')
    op.drop_constraint(op.f('fk_Log_five_why_id_Five_Why'), 'Log', type_='foreignkey')
    op.drop_column('Log', 'action_id')
    op.drop_column('Log', 'shared_learning_id')
    op.drop_column('Log', 'root_cause_detail_id')
    op.drop_column('Log', 'five_why_id')
    op.drop_column('Log', 'flash_report_id')
    op.drop_column('Log', 'investigation_id')
    # ### end Alembic commands ###
