"""specify schemas.REMS_Event_Details.event_id to be pk

Revision ID: e4aee6974a9e
Revises: 734bf86eb2da
Create Date: 2022-05-31 09:44:34.223514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4aee6974a9e'
down_revision = '734bf86eb2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
