"""association tables REMS remove

Revision ID: 69cdf04913d5
Revises: 2c1b13a8c4a3
Create Date: 2022-06-01 02:41:44.093396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69cdf04913d5'
down_revision = '2c1b13a8c4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_REMS_Selected_Event_Details_Association_id', table_name='REMS_Selected_Event_Details_Association')
    op.drop_table('REMS_Selected_Event_Details_Association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('REMS_Selected_Event_Details_Association',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"REMS_Selected_Event_Details_Association_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('investigation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name='fk_REMS_Selected_Event_Details_Association_investigatio_af19', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_REMS_Selected_Event_Details_Association')
    )
    op.create_index('ix_REMS_Selected_Event_Details_Association_id', 'REMS_Selected_Event_Details_Association', ['id'], unique=False)
    # ### end Alembic commands ###
