"""schemas.Investigation_Attachments added

Revision ID: 637d48593414
Revises: 2b3b47744fb2
Create Date: 2022-09-15 00:35:21.789972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637d48593414'
down_revision = '2b3b47744fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('investigation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_General_Attachment_investigation_id_Investigation'), 'General_Attachment', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_General_Attachment_investigation_id_Investigation'), 'General_Attachment', type_='foreignkey')
    op.drop_column('General_Attachment', 'investigation_id')
    # ### end Alembic commands ###
