"""aplus info added to dashboard schema

Revision ID: fb23b80afb6c
Revises: a3c3247e8a4c
Create Date: 2022-06-16 00:55:40.285854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb23b80afb6c'
down_revision = 'a3c3247e8a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('aplus_date_range', sa.String(), nullable=True))
    op.add_column('Dashboard', sa.Column('aplus_site', sa.String(), nullable=True))
    op.add_column('Dashboard', sa.Column('aplus_area', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'aplus_area')
    op.drop_column('Dashboard', 'aplus_site')
    op.drop_column('Dashboard', 'aplus_date_range')
    # ### end Alembic commands ###
