"""add circuit to aplus table

Revision ID: fb7883226067
Revises: adf8268e3c10
Create Date: 2022-07-22 07:14:58.382417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fb7883226067"
down_revision = "adf8268e3c10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Charting", sa.Column("circuit", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Charting", "circuit")
    # ### end Alembic commands ###
