"""historical flag to schemas.Action

Revision ID: 601f4c6723d4
Revises: 555c5a07d499
Create Date: 2022-08-01 11:50:37.936988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601f4c6723d4'
down_revision = '555c5a07d499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_historical', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'is_historical')
    # ### end Alembic commands ###
