"""add cause category column to schemas.Investigation

Revision ID: 1aeaf2a2a347
Revises: 571eff051278
Create Date: 2022-08-08 01:53:53.879804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeaf2a2a347'
down_revision = '571eff051278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('cause_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'cause_code')
    # ### end Alembic commands ###
