"""total_tonnes and total_event_duration in schemas.Investigation

Revision ID: 6fc063549144
Revises: ef25d8dc46d7
Create Date: 2022-06-23 06:00:33.844486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc063549144'
down_revision = 'ef25d8dc46d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('total_effective_duration', sa.Float(), nullable=True))
    op.add_column('Investigation', sa.Column('total_tonnes_lost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'total_tonnes_lost')
    op.drop_column('Investigation', 'total_effective_duration')
    # ### end Alembic commands ###
