"""Notification schema

Revision ID: 5974dae7d87b
Revises: 7c6bb4dc068a
Create Date: 2022-06-09 06:03:52.542228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5974dae7d87b'
down_revision = '7c6bb4dc068a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Notification_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Notification'))
    )
    op.create_index(op.f('ix_Notification_id'), 'Notification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notification_id'), table_name='Notification')
    op.drop_table('Notification')
    # ### end Alembic commands ###
