"""feedback comments

Revision ID: 75464344197d
Revises: d43b6a9a07ea
Create Date: 2022-09-01 07:34:37.591718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75464344197d'
down_revision = 'd43b6a9a07ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback_Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['Feedback.id'], name=op.f('fk_Feedback_Comment_feedback_id_Feedback')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Feedback_Comment_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Feedback_Comment'))
    )
    op.create_index(op.f('ix_Feedback_Comment_id'), 'Feedback_Comment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Feedback_Comment_id'), table_name='Feedback_Comment')
    op.drop_table('Feedback_Comment')
    # ### end Alembic commands ###
