"""upload complete rca fname col

Revision ID: 84995f4cf3a7
Revises: 42826ff1e5c6
Create Date: 2022-08-25 03:14:25.528991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84995f4cf3a7'
down_revision = '42826ff1e5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Root_Cause_Detail', sa.Column('complete_rca_fname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Root_Cause_Detail', 'complete_rca_fname')
    # ### end Alembic commands ###
