"""five_why owners and supervisor added

Revision ID: b31df511e015
Revises: 976bb1a92dac
Create Date: 2022-06-01 06:34:23.041079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31df511e015'
down_revision = '976bb1a92dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Five_Why_Owner_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('five_why_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['five_why_id'], ['Five_Why.id'], name=op.f('fk_Five_Why_Owner_Association_five_why_id_Five_Why'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Five_Why_Owner_Association_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Five_Why_Owner_Association'))
    )
    op.create_index(op.f('ix_Five_Why_Owner_Association_id'), 'Five_Why_Owner_Association', ['id'], unique=False)
    op.add_column('Five_Why', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Five_Why_supervisor_id_User'), 'Five_Why', 'User', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Five_Why_supervisor_id_User'), 'Five_Why', type_='foreignkey')
    op.drop_column('Five_Why', 'supervisor_id')
    op.drop_index(op.f('ix_Five_Why_Owner_Association_id'), table_name='Five_Why_Owner_Association')
    op.drop_table('Five_Why_Owner_Association')
    # ### end Alembic commands ###
