"""is_archived details modular class

Revision ID: 7d6172d8871c
Revises: d88eb458fbaa
Create Date: 2022-08-30 07:20:29.945657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6172d8871c'
down_revision = 'd88eb458fbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('archive_user_id', sa.Integer(), nullable=True))
    op.add_column('Investigation', sa.Column('archive_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'archive_datetime')
    op.drop_column('Investigation', 'archive_user_id')
    # ### end Alembic commands ###
