"""rems date range

Revision ID: 248de09d984e
Revises: 6743b4ff98cb
Create Date: 2022-08-03 02:52:24.598206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '248de09d984e'
down_revision = '6743b4ff98cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('rems_date_range', sa.String(), nullable=True))
    op.drop_column('Dashboard', 'rems_date_start')
    op.drop_column('Dashboard', 'rems_date_due')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('rems_date_due', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Dashboard', sa.Column('rems_date_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Dashboard', 'rems_date_range')
    # ### end Alembic commands ###
