"""is_complete col add to fivewhy

Revision ID: 8c62b36a134c
Revises: 3c6e317e64cb
Create Date: 2022-12-12 03:19:46.550628

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8c62b36a134c"
down_revision = "3c6e317e64cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Five_Why", sa.Column("is_complete", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Five_Why", "is_complete")
    # ### end Alembic commands ###
