"""location_id added to Dachboard schema

Revision ID: a3c3247e8a4c
Revises: 3b6e95838b5e
Create Date: 2022-06-15 08:02:30.024211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c3247e8a4c'
down_revision = '3b6e95838b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Dashboard_location_id_Team'), 'Dashboard', 'Team', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Dashboard_location_id_Team'), 'Dashboard', type_='foreignkey')
    op.drop_column('Dashboard', 'location_id')
    # ### end Alembic commands ###
