"""Event_Details datetime cols remove

Revision ID: 52b6691131f7
Revises: dd7a1adadf47
Create Date: 2022-05-30 08:17:11.401507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b6691131f7'
down_revision = 'dd7a1adadf47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Event_Details', 'start_time')
    op.drop_column('Event_Details', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event_Details', sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Event_Details', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
