"""add sufficient_inventory_levels to Flash Report

Revision ID: ee6a7942976f
Revises: e6df9df53e32
Create Date: 2022-11-14 23:56:33.595512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6a7942976f'
down_revision = 'e6df9df53e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
