"""injest users directly

Revision ID: d4dfacfd73aa
Revises: 55bbced0b863
Create Date: 2022-06-24 06:12:57.641408

"""
import csv

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from app import schemas, crud


# revision identifiers, used by Alembic.
revision = "d4dfacfd73aa"
down_revision = "55bbced0b863"
branch_labels = None
depends_on = None


def ingest_microsoft_users_csv(db):
    csv_file_name = "users.csv"
    full_path = f"/app/app/ingest/{csv_file_name}"

    with open(full_path, encoding="utf-8-sig") as f:
        rows = csv.DictReader(f)
        for r in rows:

            # emails must be non null and lower case
            email = r.get("email")
            if email == "None":
                continue
            email = email.lower()

            # users must have a unique email
            _user = crud.user.get_kw_single(db, email=email)
            if _user:
                continue

            db.add(
                schemas.User(
                    name=r.get("name"),
                    email=email,
                    job_title=r.get("position"),
                    sap_number=None,
                )
            )
        db.commit()


def ingest_sap_users_csv(db):
    csv_file_name = "fmg_employee_table.csv"
    full_path = f"/app/app/ingest/{csv_file_name}"

    with open(full_path, encoding="utf-8-sig") as f:
        rows = csv.DictReader(f)

        for r in rows:

            # ignore terminated users
            if r.get("PositionStatus") == "Terminated":
                continue

            # email must exist
            email = r.get("Email")
            if email == "None":
                continue
            email = email.lower()

            # users must have a unique email
            _user = crud.user.get_kw_single(db, email=email)
            if _user:
                continue

            # users must have a unique sap_number
            sap_number = r.get("Employee_BK")
            _user = crud.user.get_kw_single(db, sap_number=sap_number)
            if _user and _user.sap_number:
                continue

            db.add(
                schemas.User(
                    name=f"{r.get('FirstName')} {r.get('LastName')}",
                    email=email,
                    job_title=r.get("JobTitle"),
                    sap_number=int(sap_number.lstrip("0")),  # strip leading 0s
                )
            )
        db.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # db = Session(op.get_bind())
    # ingest_microsoft_users_csv(db)
    # ingest_sap_users_csv(db)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
