"""add user to feedback table

Revision ID: d19a64764750
Revises: dc929ea2321f
Create Date: 2022-09-01 02:41:31.181531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19a64764750'
down_revision = 'dc929ea2321f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Feedback_creator_id_User'), 'Feedback', 'User', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Feedback_creator_id_User'), 'Feedback', type_='foreignkey')
    op.drop_column('Feedback', 'creator_id')
    # ### end Alembic commands ###
