"""remove unused schemas

Revision ID: 571eff051278
Revises: 248de09d984e
Create Date: 2022-08-05 00:50:12.150687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '571eff051278'
down_revision = '248de09d984e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_REMS_Event_Details_id', table_name='REMS_Event_Details')
    op.drop_table('REMS_Event_Details')
    op.drop_index('ix_Event_Details_id', table_name='Event_Details')
    op.drop_table('Event_Details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event_Details',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Event_Details_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tonnes_lost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effective_duration', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('downtime_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_Event_Details')
    )
    op.create_index('ix_Event_Details_id', 'Event_Details', ['id'], unique=False)
    op.create_table('REMS_Event_Details',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"REMS_Event_Details_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_duration', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('event_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('function_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_REMS_Event_Details')
    )
    op.create_index('ix_REMS_Event_Details_id', 'REMS_Event_Details', ['id'], unique=False)
    # ### end Alembic commands ###
