"""time usage code column

Revision ID: 6c03a7bfec5b
Revises: 547fb30b7f2a
Create Date: 2022-09-20 02:12:41.122507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c03a7bfec5b"
down_revision = "547fb30b7f2a"
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('fk_Attachment_feedback_id_Feedback', 'Attachment', type_='foreignkey')
    # op.drop_column('Attachment', 'feedback_id')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Attachment', sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.create_foreign_key('fk_Attachment_feedback_id_Feedback', 'Attachment', 'Feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
