"""cascade on delet action - comments

Revision ID: fb13be470e1c
Revises: c0565b6865dc
Create Date: 2022-10-27 01:24:24.561995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb13be470e1c'
down_revision = 'c0565b6865dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Action_Comment_action_id_Action', 'Action_Comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Action_Comment_action_id_Action'), 'Action_Comment', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Action_Comment_action_id_Action'), 'Action_Comment', type_='foreignkey')
    op.create_foreign_key('fk_Action_Comment_action_id_Action', 'Action_Comment', 'Action', ['action_id'], ['id'])
    # ### end Alembic commands ###
