"""is_user

Revision ID: c1ea346a16cb
Revises: 84995f4cf3a7
Create Date: 2022-08-26 07:24:44.846284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ea346a16cb'
down_revision = '84995f4cf3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_user')
    # ### end Alembic commands ###
