"""new - flash report action ids in schema.FiveWhy

Revision ID: 94f141577429
Revises: 8c62b36a134c
Create Date: 2022-12-15 03:38:44.651528

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "94f141577429"
down_revision = "8c62b36a134c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Five_Why", sa.Column("flash_report_action_ids", sa.ARRAY(sa.Integer()), nullable=True)
    )
    op.execute('UPDATE "Five_Why" SET flash_report_action_ids = ARRAY[]::integer[]')
    op.alter_column("Five_Why", "flash_report_action_ids", nullable=False)
    # ### end Alembic commands ##


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Five_Why", "flash_report_action_ids")
    # ### end Alembic commands ###
