"""user links to location_id

Revision ID: 48d66558bccb
Revises: 7ba414e3b54a
Create Date: 2022-06-27 14:08:28.105374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d66558bccb'
down_revision = '7ba414e3b54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_User_location_id_Team'), 'User', 'Team', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_User_location_id_Team'), 'User', type_='foreignkey')
    op.drop_column('User', 'location_id')
    # ### end Alembic commands ###
