"""general attachments schema

Revision ID: fb9c9e8c227b
Revises: ff979a65a827
Create Date: 2022-07-15 02:34:19.815038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9c9e8c227b'
down_revision = 'ff979a65a827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('General_Attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_filename', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['User.id'], name=op.f('fk_General_Attachment_deleted_by_User'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['User.id'], name=op.f('fk_General_Attachment_uploaded_by_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_General_Attachment'))
    )
    op.create_index(op.f('ix_General_Attachment_id'), 'General_Attachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_General_Attachment_id'), table_name='General_Attachment')
    op.drop_table('General_Attachment')
    # ### end Alembic commands ###
