"""Event_Details datetime cols add with correct type

Revision ID: 47fba2bdf160
Revises: 52b6691131f7
Create Date: 2022-05-30 08:18:07.091692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fba2bdf160'
down_revision = '52b6691131f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event_Details', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Event_Details', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Event_Details', 'end_time')
    op.drop_column('Event_Details', 'start_time')
    # ### end Alembic commands ###
