"""attachments shcmeas

Revision ID: 91f366846aef
Revises: c2c932e1362f
Create Date: 2022-09-02 07:10:02.315130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f366846aef'
down_revision = 'c2c932e1362f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
