"""feeback fk in schemas.Attachments

Revision ID: dc929ea2321f
Revises: 60cf809cb345
Create Date: 2022-08-31 03:35:04.173484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc929ea2321f'
down_revision = '60cf809cb345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachment', sa.Column('feedback_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Attachment_feedback_id_Feedback'), 'Attachment', 'Feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Attachment_feedback_id_Feedback'), 'Attachment', type_='foreignkey')
    op.drop_column('Attachment', 'feedback_id')
    # ### end Alembic commands ###
