"""status and closure notes

Revision ID: d43b6a9a07ea
Revises: 3799932f584c
Create Date: 2022-09-01 04:02:37.638713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43b6a9a07ea'
down_revision = '3799932f584c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('Feedback', sa.Column('closure_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Feedback', 'closure_notes')
    op.drop_column('Feedback', 'status')
    # ### end Alembic commands ###
