"""add sufficient_inventory_levels col to flash report

Revision ID: e6df9df53e32
Revises: fb13be470e1c
Create Date: 2022-11-09 11:34:49.263832

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6df9df53e32"
down_revision = "fb13be470e1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Flash_Report", sa.Column("sufficient_inventory_levels", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Flash_Report", "sufficient_inventory_levels")
    # ### end Alembic commands ###
