"""Update cascades

Revision ID: fa02235ccee5
Revises: 48961144f462
Create Date: 2022-05-25 07:51:50.797789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02235ccee5'
down_revision = '48961144f462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Action_root_cause_detail_id_Root_Cause_Detail', 'Action', type_='foreignkey')
    op.drop_constraint('fk_Action_flash_report_id_Flash_Report', 'Action', type_='foreignkey')
    op.drop_constraint('fk_Action_five_why_id_Five_Why', 'Action', type_='foreignkey')
    op.drop_constraint('fk_Action_investigation_id_Investigation', 'Action', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Action_investigation_id_Investigation'), 'Action', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Action_root_cause_detail_id_Root_Cause_Detail'), 'Action', 'Root_Cause_Detail', ['root_cause_detail_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Action_flash_report_id_Flash_Report'), 'Action', 'Flash_Report', ['flash_report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Action_five_why_id_Five_Why'), 'Action', 'Five_Why', ['five_why_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Action_Owner_Association_action_id_Action', 'Action_Owner_Association', type_='foreignkey')
    op.drop_constraint('fk_Action_Owner_Association_user_id_User', 'Action_Owner_Association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Action_Owner_Association_user_id_User'), 'Action_Owner_Association', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Action_Owner_Association_action_id_Action'), 'Action_Owner_Association', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Five_Why_root_response_id_Five_Why_Response', 'Five_Why', type_='foreignkey')
    op.drop_constraint('fk_Five_Why_investigation_id_Investigation', 'Five_Why', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Five_Why_investigation_id_Investigation'), 'Five_Why', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Five_Why_root_response_id_Five_Why_Response'), 'Five_Why', 'Five_Why_Response', ['root_response_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Five_Why_Response_parent_response_id_Five_Why_Response', 'Five_Why_Response', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Five_Why_Response_parent_response_id_Five_Why_Response'), 'Five_Why_Response', 'Five_Why_Response', ['parent_response_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Flash_Report_investigation_id_Investigation', 'Flash_Report', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Flash_Report_investigation_id_Investigation'), 'Flash_Report', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Investigation_Owner_Association_user_id_User', 'Investigation_Owner_Association', type_='foreignkey')
    op.drop_constraint('fk_Investigation_Owner_Association_investigation_id_Inv_11c7', 'Investigation_Owner_Association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Investigation_Owner_Association_investigation_id_Investigation'), 'Investigation_Owner_Association', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Investigation_Owner_Association_user_id_User'), 'Investigation_Owner_Association', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Relevant_Investigation_Association_investigation_id__79f7', 'Relevant_Investigation_Association', type_='foreignkey')
    op.drop_constraint('fk_Relevant_Investigation_Association_relevent_investig_6a66', 'Relevant_Investigation_Association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Relevant_Investigation_Association_relevent_investigation_id_Investigation'), 'Relevant_Investigation_Association', 'Investigation', ['relevent_investigation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Relevant_Investigation_Association_investigation_id_Investigation'), 'Relevant_Investigation_Association', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Root_Cause_Detail_investigation_id_Investigation', 'Root_Cause_Detail', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Root_Cause_Detail_investigation_id_Investigation'), 'Root_Cause_Detail', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_Selected_Event_Details_Association_investigation_id__7b85', 'Selected_Event_Details_Association', type_='foreignkey')
    op.drop_constraint('fk_Selected_Event_Details_Association_event_details_id__9c45', 'Selected_Event_Details_Association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Selected_Event_Details_Association_event_details_id_Event_Details'), 'Selected_Event_Details_Association', 'Event_Details', ['event_details_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_Selected_Event_Details_Association_investigation_id_Investigation'), 'Selected_Event_Details_Association', 'Investigation', ['investigation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Selected_Event_Details_Association_investigation_id_Investigation'), 'Selected_Event_Details_Association', type_='foreignkey')
    op.drop_constraint(op.f('fk_Selected_Event_Details_Association_event_details_id_Event_Details'), 'Selected_Event_Details_Association', type_='foreignkey')
    op.create_foreign_key('fk_Selected_Event_Details_Association_event_details_id__9c45', 'Selected_Event_Details_Association', 'Event_Details', ['event_details_id'], ['id'])
    op.create_foreign_key('fk_Selected_Event_Details_Association_investigation_id__7b85', 'Selected_Event_Details_Association', 'Investigation', ['investigation_id'], ['id'])
    op.drop_constraint(op.f('fk_Root_Cause_Detail_investigation_id_Investigation'), 'Root_Cause_Detail', type_='foreignkey')
    op.create_foreign_key('fk_Root_Cause_Detail_investigation_id_Investigation', 'Root_Cause_Detail', 'Investigation', ['investigation_id'], ['id'])
    op.drop_constraint(op.f('fk_Relevant_Investigation_Association_investigation_id_Investigation'), 'Relevant_Investigation_Association', type_='foreignkey')
    op.drop_constraint(op.f('fk_Relevant_Investigation_Association_relevent_investigation_id_Investigation'), 'Relevant_Investigation_Association', type_='foreignkey')
    op.create_foreign_key('fk_Relevant_Investigation_Association_relevent_investig_6a66', 'Relevant_Investigation_Association', 'Investigation', ['relevent_investigation_id'], ['id'])
    op.create_foreign_key('fk_Relevant_Investigation_Association_investigation_id__79f7', 'Relevant_Investigation_Association', 'Investigation', ['investigation_id'], ['id'])
    op.drop_constraint(op.f('fk_Investigation_Owner_Association_user_id_User'), 'Investigation_Owner_Association', type_='foreignkey')
    op.drop_constraint(op.f('fk_Investigation_Owner_Association_investigation_id_Investigation'), 'Investigation_Owner_Association', type_='foreignkey')
    op.create_foreign_key('fk_Investigation_Owner_Association_investigation_id_Inv_11c7', 'Investigation_Owner_Association', 'Investigation', ['investigation_id'], ['id'])
    op.create_foreign_key('fk_Investigation_Owner_Association_user_id_User', 'Investigation_Owner_Association', 'User', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_Flash_Report_investigation_id_Investigation'), 'Flash_Report', type_='foreignkey')
    op.create_foreign_key('fk_Flash_Report_investigation_id_Investigation', 'Flash_Report', 'Investigation', ['investigation_id'], ['id'])
    op.drop_constraint(op.f('fk_Five_Why_Response_parent_response_id_Five_Why_Response'), 'Five_Why_Response', type_='foreignkey')
    op.create_foreign_key('fk_Five_Why_Response_parent_response_id_Five_Why_Response', 'Five_Why_Response', 'Five_Why_Response', ['parent_response_id'], ['id'])
    op.drop_constraint(op.f('fk_Five_Why_root_response_id_Five_Why_Response'), 'Five_Why', type_='foreignkey')
    op.drop_constraint(op.f('fk_Five_Why_investigation_id_Investigation'), 'Five_Why', type_='foreignkey')
    op.create_foreign_key('fk_Five_Why_investigation_id_Investigation', 'Five_Why', 'Investigation', ['investigation_id'], ['id'])
    op.create_foreign_key('fk_Five_Why_root_response_id_Five_Why_Response', 'Five_Why', 'Five_Why_Response', ['root_response_id'], ['id'])
    op.drop_constraint(op.f('fk_Action_Owner_Association_action_id_Action'), 'Action_Owner_Association', type_='foreignkey')
    op.drop_constraint(op.f('fk_Action_Owner_Association_user_id_User'), 'Action_Owner_Association', type_='foreignkey')
    op.create_foreign_key('fk_Action_Owner_Association_user_id_User', 'Action_Owner_Association', 'User', ['user_id'], ['id'])
    op.create_foreign_key('fk_Action_Owner_Association_action_id_Action', 'Action_Owner_Association', 'Action', ['action_id'], ['id'])
    op.drop_constraint(op.f('fk_Action_five_why_id_Five_Why'), 'Action', type_='foreignkey')
    op.drop_constraint(op.f('fk_Action_flash_report_id_Flash_Report'), 'Action', type_='foreignkey')
    op.drop_constraint(op.f('fk_Action_root_cause_detail_id_Root_Cause_Detail'), 'Action', type_='foreignkey')
    op.drop_constraint(op.f('fk_Action_investigation_id_Investigation'), 'Action', type_='foreignkey')
    op.create_foreign_key('fk_Action_investigation_id_Investigation', 'Action', 'Investigation', ['investigation_id'], ['id'])
    op.create_foreign_key('fk_Action_five_why_id_Five_Why', 'Action', 'Five_Why', ['five_why_id'], ['id'])
    op.create_foreign_key('fk_Action_flash_report_id_Flash_Report', 'Action', 'Flash_Report', ['flash_report_id'], ['id'])
    op.create_foreign_key('fk_Action_root_cause_detail_id_Root_Cause_Detail', 'Action', 'Root_Cause_Detail', ['root_cause_detail_id'], ['id'])
    # ### end Alembic commands ###
