"""Add cause column to schemas.Investigation from schemas.Root_Cause_Detail

Revision ID: 063666e94e7b
Revises: fa02235ccee5
Create Date: 2022-05-27 02:00:10.014209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063666e94e7b'
down_revision = 'fa02235ccee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('cause', sa.String(), nullable=True))
    op.drop_column('Root_Cause_Detail', 'cause')
    op.drop_column('Root_Cause_Detail', 'cause_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Root_Cause_Detail', sa.Column('cause_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Root_Cause_Detail', sa.Column('cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Investigation', 'cause')
    # ### end Alembic commands ###
