"""date_closed to actions

Revision ID: 840af5b2a6f9
Revises: 48d66558bccb
Create Date: 2022-06-30 02:07:32.434587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840af5b2a6f9'
down_revision = '48d66558bccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'date_closed')
    # ### end Alembic commands ###
