"""Merge Selected Event Foreign keys

Revision ID: e4484da337f8
Revises: e4aee6974a9e
Create Date: 2022-05-31 09:59:02.759237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4484da337f8'
down_revision = 'e4aee6974a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Selected_Event_Details_Association', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_Selected_Event_Details_Association_event_details_id__9c45', 'Selected_Event_Details_Association', type_='foreignkey')
    op.drop_column('Selected_Event_Details_Association', 'event_details_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Selected_Event_Details_Association', sa.Column('event_details_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_Selected_Event_Details_Association_event_details_id__9c45', 'Selected_Event_Details_Association', 'Event_Details', ['event_details_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Selected_Event_Details_Association', 'event_id')
    # ### end Alembic commands ###
