"""Notification add type

Revision ID: eec478c82895
Revises: d70e649ff994
Create Date: 2022-06-13 02:10:52.348989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec478c82895'
down_revision = 'd70e649ff994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notification', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notification', 'type')
    # ### end Alembic commands ###
