"""add created by and updated by cols

Revision ID: f6468d32deee
Revises: 91f366846aef
Create Date: 2022-09-04 23:45:24.788849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6468d32deee'
down_revision = '91f366846aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('Feedback', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Feedback_updated_by_id_User'), 'Feedback', 'User', ['updated_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_Feedback_created_by_id_User'), 'Feedback', 'User', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Feedback_created_by_id_User'), 'Feedback', type_='foreignkey')
    op.drop_constraint(op.f('fk_Feedback_updated_by_id_User'), 'Feedback', type_='foreignkey')
    op.drop_column('Feedback', 'updated_by_id')
    op.drop_column('Feedback', 'created_by_id')
    # ### end Alembic commands ###
