"""rems info added to dashboard schema

Revision ID: 13188fd2ab77
Revises: fb23b80afb6c
Create Date: 2022-06-16 06:37:11.102812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13188fd2ab77"
down_revision = "fb23b80afb6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Dashboard", sa.Column("rems_date_start", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "Dashboard", sa.Column("rems_date_due", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("Dashboard", sa.Column("rems_site", sa.String(), nullable=True))
    op.add_column("Dashboard", sa.Column("rems_fleet_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Dashboard", "rems_fleet_type")
    op.drop_column("Dashboard", "rems_site")
    op.drop_column("Dashboard", "rems_date_due")
    op.drop_column("Dashboard", "rems_date_start")
    # ### end Alembic commands ###
