"""specify schemas.REMS_Event_Details.event_id

Revision ID: 734bf86eb2da
Revises: 88870dd53d59
Create Date: 2022-05-31 09:19:43.295098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734bf86eb2da'
down_revision = '88870dd53d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REMS_Event_Details', sa.Column('event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('REMS_Event_Details', 'event_id')
    # ### end Alembic commands ###
