"""add user to feedback table name change

Revision ID: 3799932f584c
Revises: d19a64764750
Create Date: 2022-09-01 02:46:39.943247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3799932f584c'
down_revision = 'd19a64764750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_Feedback_creator_id_User', 'Feedback', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Feedback_owner_id_User'), 'Feedback', 'User', ['owner_id'], ['id'])
    op.drop_column('Feedback', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_Feedback_owner_id_User'), 'Feedback', type_='foreignkey')
    op.create_foreign_key('fk_Feedback_creator_id_User', 'Feedback', 'User', ['creator_id'], ['id'])
    op.drop_column('Feedback', 'owner_id')
    # ### end Alembic commands ###
