"""shared learnings image connections

Revision ID: 8adfd8943d24
Revises: 7b2174dba54b
Create Date: 2022-07-27 03:52:34.795976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adfd8943d24'
down_revision = '7b2174dba54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attachment', sa.Column('shared_learning_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Attachment_shared_learning_id_Shared_Learning'), 'Attachment', 'Shared_Learning', ['shared_learning_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Attachment_shared_learning_id_Shared_Learning'), 'Attachment', type_='foreignkey')
    op.drop_column('Attachment', 'shared_learning_id')
    # ### end Alembic commands ###
