"""schemas.REMS_Event_Details

Revision ID: 724793635bbe
Revises: 47fba2bdf160
Create Date: 2022-05-31 02:27:05.589214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724793635bbe'
down_revision = '47fba2bdf160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('REMS_Event_Details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_duration', sa.Float(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('last_comment', sa.String(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('functional_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_REMS_Event_Details'))
    )
    op.create_index(op.f('ix_REMS_Event_Details_id'), 'REMS_Event_Details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_REMS_Event_Details_id'), table_name='REMS_Event_Details')
    op.drop_table('REMS_Event_Details')
    # ### end Alembic commands ###
