"""add 5 why threshold column to dashboard

Revision ID: 1138eb49ec97
Revises: 8c62b36a134c
Create Date: 2022-12-12 08:56:11.166406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1138eb49ec97"
down_revision = "8c62b36a134c"
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(
    #     "ix_Workorder_Investigation_Association_id",
    #     table_name="Workorder_Investigation_Association",
    # )
    # op.drop_table("Workorder_Investigation_Association")
    # op.add_column("Dashboard", sa.Column("threshold_5_why", sa.Integer(), nullable=True))
    # op.add_column("Five_Why", sa.Column("is_complete", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("Five_Why", "is_complete")
    # op.drop_column("Dashboard", "threshold_5_why")
    # op.create_table(
    #     "Workorder_Investigation_Association",
    #     sa.Column(
    #         "id",
    #         sa.INTEGER(),
    #         server_default=sa.text(
    #             "nextval('\"Workorder_Investigation_Association_id_seq\"'::regclass)"
    #         ),
    #         autoincrement=True,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
    #     ),
    #     sa.Column(
    #         "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
    #     ),
    #     sa.Column("investigation_id", sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column("workorder", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column(
    #         "planned_cost",
    #         postgresql.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "actual_cost",
    #         postgresql.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["investigation_id"],
    #         ["Investigation.id"],
    #         name="fk_Workorder_Investigation_Association_investigation_id_19a2",
    #         ondelete="CASCADE",
    #     ),
    #     sa.PrimaryKeyConstraint("id", name="pk_Workorder_Investigation_Association"),
    # )
    # op.create_index(
    #     "ix_Workorder_Investigation_Association_id",
    #     "Workorder_Investigation_Association",
    #     ["id"],
    #     unique=False,
    # )
    # ### end Alembic commands ###
