"""add network_drive_link col to schemas.general_attachment

Revision ID: ed4f18225913
Revises: cc5c0027d4a1
Create Date: 2022-09-29 00:11:02.704020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed4f18225913"
down_revision = "cc5c0027d4a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('fk_Attachment_feedback_id_Feedback', 'Attachment', type_='foreignkey')
    # op.drop_column('Attachment', 'feedback_id')
    op.add_column("General_Attachment", sa.Column("network_drive_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("General_Attachment", "network_drive_link")
    # op.add_column(
    #     "Attachment", sa.Column("feedback_id", sa.INTEGER(), autoincrement=False, nullable=True)
    # )
    # op.create_foreign_key(
    #     "fk_Attachment_feedback_id_Feedback",
    #     "Attachment",
    #     "Feedback",
    #     ["feedback_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # ### end Alembic commands ###
