"""is_archived

Revision ID: d88eb458fbaa
Revises: 8c8342a79410
Create Date: 2022-08-29 06:07:54.923578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88eb458fbaa'
down_revision = '8c8342a79410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'is_archived')
    # ### end Alembic commands ###
