"""schemas.Action has root cause detail actions

Revision ID: 547fb30b7f2a
Revises: 637d48593414
Create Date: 2022-09-15 08:23:48.946468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547fb30b7f2a'
down_revision = '637d48593414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
