"""remove date_created schemas.Actions as added by default now, Root cause details added back

Revision ID: dd7a1adadf47
Revises: 063666e94e7b
Create Date: 2022-05-27 03:46:23.867790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd7a1adadf47'
down_revision = '063666e94e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'date_created')
    op.drop_column('Investigation', 'cause')
    op.add_column('Root_Cause_Detail', sa.Column('cause', sa.String(), nullable=True))
    op.add_column('Root_Cause_Detail', sa.Column('cause_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Root_Cause_Detail', 'cause_code')
    op.drop_column('Root_Cause_Detail', 'cause')
    op.add_column('Investigation', sa.Column('cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Action', sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
