"""association tables REMS add

Revision ID: 976bb1a92dac
Revises: 69cdf04913d5
Create Date: 2022-06-01 02:42:01.002900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976bb1a92dac'
down_revision = '69cdf04913d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('REMS_Selected_Event_Details_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_REMS_Selected_Event_Details_Association_investigation_id_Investigation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_REMS_Selected_Event_Details_Association'))
    )
    op.create_index(op.f('ix_REMS_Selected_Event_Details_Association_id'), 'REMS_Selected_Event_Details_Association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_REMS_Selected_Event_Details_Association_id'), table_name='REMS_Selected_Event_Details_Association')
    op.drop_table('REMS_Selected_Event_Details_Association')
    # ### end Alembic commands ###
