"""remove owner_id col from schemas.Feedback

Revision ID: 33b3a691f894
Revises: f6468d32deee
Create Date: 2022-09-05 00:08:54.930583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b3a691f894'
down_revision = 'f6468d32deee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Feedback_owner_id_User', 'Feedback', type_='foreignkey')
    op.drop_column('Feedback', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_Feedback_owner_id_User', 'Feedback', 'User', ['owner_id'], ['id'])
    # ### end Alembic commands ###
