"""association tables APLUS and REMS

Revision ID: 2c1b13a8c4a3
Revises: e4484da337f8
Create Date: 2022-06-01 02:34:57.767402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c1b13a8c4a3'
down_revision = 'e4484da337f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APLUS_Selected_Event_Details_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_APLUS_Selected_Event_Details_Association_investigation_id_Investigation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_APLUS_Selected_Event_Details_Association'))
    )
    op.create_index(op.f('ix_APLUS_Selected_Event_Details_Association_id'), 'APLUS_Selected_Event_Details_Association', ['id'], unique=False)
    op.create_table('REMS_Selected_Event_Details_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_REMS_Selected_Event_Details_Association_investigation_id_Investigation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_REMS_Selected_Event_Details_Association'))
    )
    op.create_index(op.f('ix_REMS_Selected_Event_Details_Association_id'), 'REMS_Selected_Event_Details_Association', ['id'], unique=False)
    op.drop_index('ix_Selected_Event_Details_Association_id', table_name='Selected_Event_Details_Association')
    op.drop_table('Selected_Event_Details_Association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Selected_Event_Details_Association',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Selected_Event_Details_Association_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('investigation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name='fk_Selected_Event_Details_Association_investigation_id__7b85', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_Selected_Event_Details_Association')
    )
    op.create_index('ix_Selected_Event_Details_Association_id', 'Selected_Event_Details_Association', ['id'], unique=False)
    op.drop_index(op.f('ix_REMS_Selected_Event_Details_Association_id'), table_name='REMS_Selected_Event_Details_Association')
    op.drop_table('REMS_Selected_Event_Details_Association')
    op.drop_index(op.f('ix_APLUS_Selected_Event_Details_Association_id'), table_name='APLUS_Selected_Event_Details_Association')
    op.drop_table('APLUS_Selected_Event_Details_Association')
    # ### end Alembic commands ###
