"""add 5 why threshold column to dashboard

Revision ID: e10dfa326d0e
Revises: 1138eb49ec97
Create Date: 2022-12-12 08:56:51.454789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10dfa326d0e'
down_revision = '1138eb49ec97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
