"""site and department are properties

Revision ID: 42826ff1e5c6
Revises: 1aeaf2a2a347
Create Date: 2022-08-09 00:41:36.674042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42826ff1e5c6'
down_revision = '1aeaf2a2a347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'site')
    op.drop_column('Investigation', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Investigation', sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
