"""shared learnings

Revision ID: cb4b31382f2e
Revises: dba30cfa3503
Create Date: 2022-07-25 06:33:51.999819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4b31382f2e'
down_revision = 'dba30cfa3503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shared_Learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('shared_learning', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name=op.f('fk_Shared_Learning_investigation_id_Investigation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Shared_Learning'))
    )
    op.create_index(op.f('ix_Shared_Learning_id'), 'Shared_Learning', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Shared_Learning_id'), table_name='Shared_Learning')
    op.drop_table('Shared_Learning')
    # ### end Alembic commands ###
