"""attachments shcmeas

Revision ID: c2c932e1362f
Revises: 698d1ded3aa6
Create Date: 2022-09-02 06:32:45.836532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2c932e1362f"
down_revision = "698d1ded3aa6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("General_Attachment", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("General_Attachment", "type")
    # ### end Alembic commands ###
