"""general attachment action_id added

Revision ID: 5b9630bfa9ab
Revises: fb9c9e8c227b
Create Date: 2022-07-15 03:06:57.350787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9630bfa9ab'
down_revision = 'fb9c9e8c227b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_General_Attachment_action_id_Action'), 'General_Attachment', 'Action', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_General_Attachment_action_id_Action'), 'General_Attachment', type_='foreignkey')
    op.drop_column('General_Attachment', 'action_id')
    # ### end Alembic commands ###
