"""schemas.Feedback add title col

Revision ID: cd835b953c16
Revises: 33b3a691f894
Create Date: 2022-09-08 01:05:03.358593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd835b953c16'
down_revision = '33b3a691f894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Feedback', 'title')
    # ### end Alembic commands ###
