"""member association add

Revision ID: ad29618f071a
Revises: ee6a7942976f
Create Date: 2022-11-22 00:34:39.437504

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad29618f071a"
down_revision = "ee6a7942976f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Action_Member_Association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["Action.id"],
            name=op.f("fk_Action_Member_Association_action_id_Action"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
            name=op.f("fk_Action_Member_Association_user_id_User"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Action_Member_Association")),
    )
    op.create_index(
        op.f("ix_Action_Member_Association_id"), "Action_Member_Association", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.drop_table("Action_Member_Association")
    # ### end Alembic commands ###
