"""schemas.User last logged in col

Revision ID: 3b00576a7536
Revises: cd835b953c16
Create Date: 2022-09-08 23:34:08.569489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b00576a7536'
down_revision = 'cd835b953c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('last_logged_in', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_logged_in')
    # ### end Alembic commands ###
