"""size col rem

Revision ID: cb729ed32fb5
Revises: a03236a50253
Create Date: 2022-07-15 08:19:29.797529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb729ed32fb5'
down_revision = 'a03236a50253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('General_Attachment', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
