"""status added to investigation

Revision ID: ef25d8dc46d7
Revises: 13188fd2ab77
Create Date: 2022-06-23 03:48:07.163316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ef25d8dc46d7"
down_revision = "13188fd2ab77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Investigation", sa.Column("status", sa.Integer(), nullable=True))
    # op.drop_column('Investigation', 'total_effective_duration')
    # op.drop_column('Investigation', 'total_tonnes_lost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Investigation', sa.Column('total_tonnes_lost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # op.add_column('Investigation', sa.Column('total_effective_duration', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column("Investigation", "status")
    # ### end Alembic commands ###
