"""size added to General_Attachment

Revision ID: a03236a50253
Revises: 5b9630bfa9ab
Create Date: 2022-07-15 07:10:19.969204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03236a50253'
down_revision = '5b9630bfa9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('General_Attachment', 'size')
    # ### end Alembic commands ###
