"""is_archived details modular class in schemas.Action

Revision ID: 7578232b2f50
Revises: 7d6172d8871c
Create Date: 2022-08-30 07:26:46.242661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7578232b2f50'
down_revision = '7d6172d8871c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('archive_user_id', sa.Integer(), nullable=True))
    op.add_column('Action', sa.Column('archive_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'archive_datetime')
    op.drop_column('Action', 'archive_user_id')
    # ### end Alembic commands ###
