"""schemas.Logs added

Revision ID: c5cec601c17b
Revises: 3b00576a7536
Create Date: 2022-09-13 00:58:14.669117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cec601c17b'
down_revision = '3b00576a7536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Log_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Log'))
    )
    op.create_index(op.f('ix_Log_id'), 'Log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Log_id'), table_name='Log')
    op.drop_table('Log')
    # ### end Alembic commands ###
