"""event_duration

Revision ID: adf8268e3c10
Revises: cb729ed32fb5
Create Date: 2022-07-21 07:34:00.346672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf8268e3c10'
down_revision = 'cb729ed32fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('total_event_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'total_event_duration')
    # ### end Alembic commands ###
