"""Team schema

Revision ID: 3b6e95838b5e
Revises: f586bb1ec9e7
Create Date: 2022-06-15 07:22:05.587848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from app import schemas
from app.schemas.enums import DashboardColorEnum


# revision identifiers, used by Alembic.
revision = "3b6e95838b5e"
down_revision = "f586bb1ec9e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["Team.id"], name=op.f("fk_Team_parent_id_Team"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Team")),
    )
    op.create_index(op.f("ix_Team_id"), "Team", ["id"], unique=False)

    db = Session(op.get_bind())

    db.add_all(
        [
            schemas.Team(
                name="Fixed Plant",
                color=None,
                children=[
                    schemas.Team(
                        name="Iron Bridge",
                        color=None,
                        children=[
                            schemas.Team(name="IB OPF", color=DashboardColorEnum.OTHER),
                        ],
                    ),
                    schemas.Team(
                        name="Solomon",
                        color=None,
                        children=[
                            schemas.Team(name="FT OPF", color=DashboardColorEnum.SHAREPOINT),
                            schemas.Team(name="KV OPF", color=DashboardColorEnum.SHAREPOINT),
                        ],
                    ),
                    schemas.Team(
                        name="Cloudbreak",
                        color=None,
                        children=[
                            schemas.Team(name="CB OPF", color=DashboardColorEnum.SHAREPOINT),
                        ],
                    ),
                    schemas.Team(
                        name="Christmas Creek",
                        color=None,
                        children=[
                            schemas.Team(name="CC OPF1", color=DashboardColorEnum.SHAREPOINT),
                            schemas.Team(name="CC OPF2", color=DashboardColorEnum.SHAREPOINT),
                        ],
                    ),
                    schemas.Team(
                        name="Eliwana",
                        color=None,
                        children=[
                            schemas.Team(name="EW OPF1", color=DashboardColorEnum.SHAREPOINT),
                        ],
                    ),
                    schemas.Team(
                        name="Anderson Point",
                        color=None,
                        children=[
                            schemas.Team(name="AP Inloading", color=DashboardColorEnum.TRELLO),
                            schemas.Team(name="AP Outloading", color=DashboardColorEnum.TRELLO),
                        ],
                    ),
                ],
            ),
            schemas.Team(
                name="HME",
                color=None,
                children=[
                    schemas.Team(
                        name="Solomon",
                        color=None,
                        children=[
                            schemas.Team(name="Haul Truck", color=DashboardColorEnum.BMS),
                            schemas.Team(name="Driggers and Drills", color=DashboardColorEnum.BMS),
                            schemas.Team(name="Ancillary", color=DashboardColorEnum.BMS),
                        ],
                    ),
                    schemas.Team(
                        name="Cloudbreak",
                        color=None,
                        children=[
                            schemas.Team(name="Haul Truck", color=DashboardColorEnum.BMS),
                            schemas.Team(name="Driggers and Drills", color=DashboardColorEnum.BMS),
                            schemas.Team(name="Ancillary", color=DashboardColorEnum.BMS),
                        ],
                    ),
                    schemas.Team(
                        name="Christmas Creek",
                        color=None,
                        children=[
                            schemas.Team(name="Haul Truck", color=DashboardColorEnum.BMS),
                            schemas.Team(name="Driggers and Drills", color=DashboardColorEnum.BMS),
                            schemas.Team(name="Ancillary", color=DashboardColorEnum.BMS),
                        ],
                    ),
                ],
            ),
            schemas.Team(
                name="Energy Operations",
                color=None,
                children=[
                    schemas.Team(name="Iron Bridge", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Solomon", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Cloudbreak", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Christmas Creek", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Eliwana", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Anderson Point", color=DashboardColorEnum.OTHER),
                ],
            ),
            schemas.Team(
                name="Dewatering",
                color=None,
                children=[
                    schemas.Team(name="Iron Bridge", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Solomon", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Chichester", color=DashboardColorEnum.TEAMS),
                    schemas.Team(name="Eliwana", color=DashboardColorEnum.OTHER),
                    schemas.Team(name="Anderson Point", color=DashboardColorEnum.OTHER),
                ],
            ),
            schemas.Team(
                name="Rail",
                color=None,
                children=[
                    schemas.Team(name="Ore Car", color=DashboardColorEnum.TRELLO),
                    schemas.Team(name="Signalling", color=DashboardColorEnum.TRELLO),
                    schemas.Team(name="Locomotives", color=DashboardColorEnum.TRELLO),
                    schemas.Team(name="Track", color=DashboardColorEnum.TRELLO),
                    schemas.Team(name="Track Machine", color=DashboardColorEnum.TRELLO),
                ],
            ),
        ]
    )

    db.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Team_id"), table_name="Team")
    op.drop_table("Team")
    # ### end Alembic commands ###
