"""Add Watched grouped to JSONB

Revision ID: c0565b6865dc
Revises: ed4f18225913
Create Date: 2022-10-25 00:40:05.707893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c0565b6865dc"
down_revision = "ed4f18225913"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index("ix_Test_id", table_name="Test")
    # op.drop_table("Test")
    op.add_column(
        "User", sa.Column("watched_groups", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )

    op.execute(
        f"""
        UPDATE "User" SET watched_groups = jsonb_build_object(
            'sites', NULL,
            'departments', NULL,
            'object_types', NULL,
            'show_all', FALSE
        );
    """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "watched_groups")
    # op.create_table(
    #     "Test",
    #     sa.Column(
    #         "id",
    #         sa.INTEGER(),
    #         server_default=sa.text("nextval('\"Test_id_seq\"'::regclass)"),
    #         autoincrement=True,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
    #     ),
    #     sa.Column(
    #         "updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
    #     ),
    #     sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.PrimaryKeyConstraint("id", name="pk_Test"),
    # )
    # op.create_index("ix_Test_id", "Test", ["id"], unique=False)
    # ### end Alembic commands ###
