"""team name for user

Revision ID: ff979a65a827
Revises: ab9cc7dcf6ff
Create Date: 2022-07-05 01:09:28.759539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff979a65a827'
down_revision = 'ab9cc7dcf6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('team_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'team_name')
    # ### end Alembic commands ###
