"""feedback schema change - add general attachments - remove images

Revision ID: 698d1ded3aa6
Revises: 75464344197d
Create Date: 2022-09-02 05:49:07.028377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698d1ded3aa6'
down_revision = '75464344197d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('feedback_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_General_Attachment_feedback_id_Feedback'), 'General_Attachment', 'Feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_General_Attachment_feedback_id_Feedback'), 'General_Attachment', type_='foreignkey')
    op.drop_column('General_Attachment', 'feedback_id')
    # ### end Alembic commands ###
