"""is_archived

Revision ID: 8c8342a79410
Revises: c1ea346a16cb
Create Date: 2022-08-29 04:29:54.218725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8342a79410'
down_revision = 'c1ea346a16cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Investigation', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Investigation', 'is_archived')
    # ### end Alembic commands ###
