"""Add Description to flash report

Revision ID: 48961144f462
Revises: 5ccf5a2bbdd0
Create Date: 2022-05-25 03:52:48.349430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48961144f462'
down_revision = '5ccf5a2bbdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flash_Report', sa.Column('event_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flash_Report', 'event_description')
    # ### end Alembic commands ###
