"""working folder link field in investigaion

Revision ID: 3c6e317e64cb
Revises: ad29618f071a
Create Date: 2022-12-05 07:13:47.197138

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3c6e317e64cb"
down_revision = "ad29618f071a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Investigation", sa.Column("working_folder_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Investigation", "working_folder_link")
    # ### end Alembic commands ###
