"""aplus circuit association table

Revision ID: 6743b4ff98cb
Revises: 601f4c6723d4
Create Date: 2022-08-02 07:00:11.764569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6743b4ff98cb'
down_revision = '601f4c6723d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aplus_Circuit_Association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('aplus_circuit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['Dashboard.id'], name=op.f('fk_Aplus_Circuit_Association_dashboard_id_Dashboard'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Aplus_Circuit_Association'))
    )
    op.create_index(op.f('ix_Aplus_Circuit_Association_id'), 'Aplus_Circuit_Association', ['id'], unique=False)
    op.drop_column('Dashboard', 'aplus_circuit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('aplus_circuit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Aplus_Circuit_Association_id'), table_name='Aplus_Circuit_Association')
    op.drop_table('Aplus_Circuit_Association')
    # ### end Alembic commands ###
