"""supervisor id in user schema

Revision ID: 3f136902de57
Revises: a496dab490e0
Create Date: 2023-01-30 01:50:52.812894

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3f136902de57"
down_revision = "a496dab490e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("supervisor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_User_supervisor_id_User"), "User", "User", ["supervisor_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_User_supervisor_id_User"), "User", type_="foreignkey")
    op.drop_column("User", "supervisor_id")
    # ### end Alembic commands ###
