"""shared learning upload doc

Revision ID: e81dd1939f8f
Revises: c40041b374af
Create Date: 2023-01-23 02:41:27.733852

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e81dd1939f8f"
down_revision = "c40041b374af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_Workorder_Investigation_Association_id', table_name='Workorder_Investigation_Association')
    # op.drop_table('Workorder_Investigation_Association')
    # op.alter_column('Five_Why', 'flash_report_action_ids',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            nullable=True)
    op.add_column(
        "General_Attachment", sa.Column("shared_learning_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "General_Attachment", sa.Column("is_selected_shared_learning", sa.Boolean(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_General_Attachment_shared_learning_id_Shared_Learning"),
        "General_Attachment",
        "Shared_Learning",
        ["shared_learning_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # op.drop_column('General_Attachment', 'is_selected_news')
    # op.drop_column('General_Attachment', 'selected')
    op.add_column("Shared_Learning", sa.Column("use_custom_report", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Shared_Learning", "use_custom_report")
    # op.add_column('General_Attachment', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.add_column('General_Attachment', sa.Column('is_selected_news', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(
        op.f("fk_General_Attachment_shared_learning_id_Shared_Learning"),
        "General_Attachment",
        type_="foreignkey",
    )
    op.drop_column("General_Attachment", "is_selected_shared_learning")
    op.drop_column("General_Attachment", "shared_learning_id")
    # op.alter_column('Five_Why', 'flash_report_action_ids',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            nullable=False)
    # op.create_table('Workorder_Investigation_Association',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Workorder_Investigation_Association_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    # sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('investigation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('workorder', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('planned_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('actual_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name='fk_Workorder_Investigation_Association_investigation_id_19a2', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='pk_Workorder_Investigation_Association')
    # )
    # op.create_index('ix_Workorder_Investigation_Association_id', 'Workorder_Investigation_Association', ['id'], unique=False)
    # ### end Alembic commands ###
