"""flash report custom

Revision ID: c40041b374af
Revises: 1c6da7b43481
Create Date: 2023-01-17 02:33:51.292543

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c40041b374af"
down_revision = "1c6da7b43481"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Flash_Report", sa.Column("use_custom_report", sa.Boolean(), nullable=True))
    op.add_column("Flash_Report", sa.Column("custom_report_fname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Flash_Report", "custom_report_fname")
    op.drop_column("Flash_Report", "use_custom_report")
    # ### end Alembic commands ###
