"""actions is deletable

Revision ID: 3e8bdf248891
Revises: 0c1b15b40c85
Create Date: 2023-01-12 05:22:16.400545

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3e8bdf248891"
down_revision = "0c1b15b40c85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Action", sa.Column("delete_user_id", sa.Integer(), nullable=True))
    op.add_column("Action", sa.Column("delete_datetime", sa.DateTime(timezone=True), nullable=True))
    op.add_column("Action", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Action", "is_deleted")
    op.drop_column("Action", "delete_datetime")
    op.drop_column("Action", "delete_user_id")
    # ### end Alembic commands ###
