"""flash report attachment

Revision ID: 1c6da7b43481
Revises: 3e8bdf248891
Create Date: 2023-01-16 07:52:58.651444

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c6da7b43481"
down_revision = "3e8bdf248891"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("General_Attachment", sa.Column("flash_report_id", sa.Integer(), nullable=True))
    op.add_column(
        "General_Attachment", sa.Column("is_selected_flash_report", sa.Boolean(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_General_Attachment_flash_report_id_Flash_Report"),
        "General_Attachment",
        "Flash_Report",
        ["flash_report_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_General_Attachment_flash_report_id_Flash_Report"),
        "General_Attachment",
        type_="foreignkey",
    )
    op.drop_column("General_Attachment", "is_selected_flash_report")
    op.drop_column("General_Attachment", "flash_report_id")
    # ### end Alembic commands ###
