"""add is_active to distribution list

Revision ID: 6abd49373d37
Revises: 3f136902de57
Create Date: 2023-02-20 09:08:11.879040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abd49373d37'
down_revision = '3f136902de57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('General_Attachment', sa.Column('is_active_list', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('General_Attachment', 'is_active_list')
    # ### end Alembic commands ###
