"""Dashboard attachment schema

Revision ID: c398d72d6093
Revises: c1cb1365e6cf
Create Date: 2023-01-02 03:29:03.843239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c398d72d6093"
down_revision = "c1cb1365e6cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column("General_Attachment", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("General_Attachment", "is_active")
    # ### end Alembic commands ###
