"""shared learning upload doc

Revision ID: a496dab490e0
Revises: e81dd1939f8f
Create Date: 2023-01-23 02:51:03.113039

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a496dab490e0"
down_revision = "e81dd1939f8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_Workorder_Investigation_Association_id', table_name='Workorder_Investigation_Association')
    # op.drop_table('Workorder_Investigation_Association')
    # op.alter_column('Five_Why', 'flash_report_action_ids',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            nullable=True)
    # op.drop_column('General_Attachment', 'selected')
    # op.drop_column('General_Attachment', 'is_selected_news')
    op.add_column("Shared_Learning", sa.Column("custom_report_fname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Shared_Learning", "custom_report_fname")
    # op.add_column('General_Attachment', sa.Column('is_selected_news', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.add_column('General_Attachment', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.alter_column('Five_Why', 'flash_report_action_ids',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            nullable=False)
    # op.create_table('Workorder_Investigation_Association',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Workorder_Investigation_Association_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    # sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('investigation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('workorder', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('planned_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('actual_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name='fk_Workorder_Investigation_Association_investigation_id_19a2', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='pk_Workorder_Investigation_Association')
    # )
    # op.create_index('ix_Workorder_Investigation_Association_id', 'Workorder_Investigation_Association', ['id'], unique=False)
    # ### end Alembic commands ###
