"""has_completed_rca col

Revision ID: 43e7b11182fe
Revises: a7f367896832
Create Date: 2023-01-12 03:42:18.021267

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "43e7b11182fe"
down_revision = "a7f367896832"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_Workorder_Investigation_Association_id', table_name='Workorder_Investigation_Association')
    # op.drop_table('Workorder_Investigation_Association')
    # op.drop_index('ix_Newsfeed_id', table_name='Newsfeed')
    # op.drop_table('Newsfeed')
    # op.alter_column('Five_Why', 'flash_report_action_ids',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            nullable=True)
    # op.drop_constraint('fk_General_Attachment_newsfeed_id_Newsfeed', 'General_Attachment', type_='foreignkey')
    # op.drop_column('General_Attachment', 'selected')
    # op.drop_column('General_Attachment', 'newsfeed_id')
    op.add_column("Investigation", sa.Column("has_completed_rca", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Investigation", "has_completed_rca")
    # op.add_column('General_Attachment', sa.Column('newsfeed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('General_Attachment', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.create_foreign_key('fk_General_Attachment_newsfeed_id_Newsfeed', 'General_Attachment', 'Newsfeed', ['newsfeed_id'], ['id'], ondelete='CASCADE')
    # op.alter_column('Five_Why', 'flash_report_action_ids',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            nullable=False)
    # op.create_table('Newsfeed',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Newsfeed_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    # sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='pk_Newsfeed')
    # )
    # op.create_index('ix_Newsfeed_id', 'Newsfeed', ['id'], unique=False)
    # op.create_table('Workorder_Investigation_Association',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Workorder_Investigation_Association_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    # sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('investigation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('workorder', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('planned_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('actual_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['investigation_id'], ['Investigation.id'], name='fk_Workorder_Investigation_Association_investigation_id_19a2', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='pk_Workorder_Investigation_Association')
    # )
    # op.create_index('ix_Workorder_Investigation_Association_id', 'Workorder_Investigation_Association', ['id'], unique=False)
    # ### end Alembic commands ###
