"""Dashboard attachment schema extra columns

Revision ID: a7f367896832
Revises: c398d72d6093
Create Date: 2023-01-02 04:57:09.682703

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a7f367896832"
down_revision = "c398d72d6093"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("General_Attachment", sa.Column("dashboard_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_General_Attachment_dashboard_id_Dashboard"),
        "General_Attachment",
        "Dashboard",
        ["dashboard_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_General_Attachment_dashboard_id_Dashboard"),
        "General_Attachment",
        type_="foreignkey",
    )
    op.drop_column("General_Attachment", "dashboard_id")
    # ### end Alembic commands ###
